// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../typedfield/models.js";

/**
 * List is one reusable, named typed dataset. Columns declares its
 * schema (typedfield.Field, ADR-0029); Rows carries its data.
 * 
 * Entries is the PRE-0011 flat key/value shape, kept on the struct
 * for wire/backward compatibility only -- MigrateLegacyEntries
 * (migrate.go) converts any list still carrying it (Columns empty,
 * Entries non-empty) into the typed Columns+Rows shape the first time
 * it's loaded (internal/services/configuresvc's restore()), so
 * list-search/list-lookup execution logic only ever deals with
 * Columns+Rows, never a third code path for the legacy shape. A list
 * persisted before this goal, loaded once, re-persists in the typed
 * shape; Entries is never populated by any code path after that first
 * load -- new lists never populate it at all. DeriveEntries below is
 * the read-side mirror: list-lookup's own execution keeps reading a
 * flat map, computed from any 2+-column typed list's first two
 * columns, so it never needed to change at all.
 */
export interface List {
    "ID": string;
    "Label": string;
    "Description": string;
    "Columns": typedfield$0.Field[] | null;
    "Rows": Row[] | null;
    "Entries": { [_ in string]?: string } | null;

    /**
     * BuiltIn marks a seeded example list -- purely informational,
     * same as httprequest.HTTPRequest.BuiltIn/decision.Decision.BuiltIn:
     * drives a "built-in" badge only, never gates Edit/Delete. A seeded
     * example is an ordinary, fully-editable list from the moment it
     * exists (docs/SPEC.md §2.2's Update note).
     */
    "BuiltIn": boolean;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (SPEC.md
     * §3.2.2's reserved-column pattern), stamped server-side at every
     * persisted mutation (ConfigureService), never trusted from the
     * wire. Zero value means pre-timestamp data -- migration-free.
     */
    "CreatedAt": string;
    "UpdatedAt": string;

    /**
     * Seed is this list's seed provenance (docs/goals/0037) -- zero
     * value means "not of seed origin," migration-free. See
     * composition.Workflow.Seed's doc comment for the full reasoning.
     */
    "Seed": seedorigin$0.Origin;

    /**
     * FieldTombstones records every Columns Key this List has ever
     * deleted (docs/adr/0040 decision 3) -- see decision.Decision's own
     * FieldTombstones doc comment for the full reasoning, applied here
     * to Columns instead of Outputs.
     */
    "FieldTombstones": typedfield$0.FieldTombstone[] | null;

    /**
     * Versions/PublishedVersion give List the same draft/publish
     * lifecycle Decision already has (docs/adr/0040 decision 4,
     * extended to a second entity by goal 0070's demonstrated need --
     * audit-replay against a List a workflow has since edited): Columns/
     * Rows above are this List's own DRAFT, edited in place exactly as
     * before this existed; Versions holds immutable snapshots frozen by
     * Publish (versioning.go), and PublishedVersion (0 = never
     * published) names which snapshot list-lookup/list-search's
     * unpinned "live@N" audit stamp reads. Both zero-valued for every
     * List persisted before this existed, migration-free.
     */
    "Versions": ListVersion[] | null;
    "PublishedVersion": number;
}

/**
 * ListVersion is one immutable snapshot of a List's schema+data
 * (docs/adr/0040 decision 4, goal 0070) -- the same draft/publish shape
 * decision.DecisionVersion gives Decision, built on the shared
 * internal/domain/versioning mechanism rather than a second hand-rolled
 * copy of the numbering/lookup logic.
 */
export interface ListVersion {
    "Version": number;
    "SavedAt": string;
    "Columns": typedfield$0.Field[] | null;
    "Rows": Row[] | null;
}

/**
 * Row is one typed record in a List. Values maps a declared Column's
 * Key to its string value -- the same "every value stays a plain
 * string on the wire" discipline typedfield.Field itself documents;
 * a Column's Type only governs validation/rendering/matching, never
 * the wire shape. CreatedAt/UpdatedAt/Status are platform-owned audit
 * fields, set by the owning service (internal/services/configuresvc),
 * never a user-declared Column.
 */
export interface Row {
    "ID": string;
    "Values": { [_ in string]?: string } | null;
    "CreatedAt": string;
    "UpdatedAt": string;
    "Status": RowStatus;
}

/**
 * RowStatus is a Row's platform-owned lifecycle state -- never a
 * TypedField/user-declared column (goal 0011's audit-column
 * decision: system-managed fields are Go struct fields, not entries
 * in List.Columns).
 */
export enum RowStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RowActive = "active",
    RowExpired = "expired",
};
