// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Capability {
    "ID": string;
    "Label": string;
    "SpecSection": string;
    "Status": Status;
    "View": ViewKind;

    /**
     * EditorPath is only set for backend-only capabilities with no UI at
     * all -- it must point at a file that actually exists today (an ADR,
     * a real source file), never an aspirational package that hasn't been
     * built yet. Enforced by TestList_EditorPathsExist.
     */
    "EditorPath": string;

    /**
     * NavLabel is the terse form shown in the top nav bar (every
     * capability gets a nav entry, built or not -- docs/SPEC.md §2.2).
     * Falls back to Label when empty, which is fine for most placeholder
     * entries; only set this when Label is too long/descriptive for a
     * tab (e.g. "Activity / event log" -> "Activity").
     */
    "NavLabel": string;
}

/**
 * Status mirrors docs/SPEC.md's own LOCKED/OPEN/PARKED convention, but
 * this package is the authoritative, machine-read source for it; SPEC.md's
 * tags remain human-readable commentary, not something anything parses.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusLocked = "LOCKED",
    StatusOpen = "OPEN",
    StatusParked = "PARKED",
};

/**
 * ViewKind identifies which page a capability's entry point navigates to.
 */
export enum ViewKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ViewActivity = "activity",
    ViewReview = "review",
    ViewComposition = "composition",
    ViewConfigure = "configure",
    ViewPlaceholder = "placeholder",
};
