// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Capability {
    "ID": string;
    "Label": string;
    "SpecSection": string;
    "Status": Status;
    "View": ViewKind;

    /**
     * EditorPath is only set for backend-only capabilities with no UI at
     * all -- it must point at a file that actually exists today (an ADR,
     * a real source file), never an aspirational package that hasn't been
     * built yet. Enforced by TestList_EditorPathsExist.
     */
    "EditorPath": string;
}

/**
 * Status mirrors docs/SPEC.md's own LOCKED/OPEN/PARKED convention, but
 * this package is the authoritative, machine-read source for it; SPEC.md's
 * tags remain human-readable commentary, not something anything parses.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusLocked = "LOCKED",
    StatusOpen = "OPEN",
    StatusParked = "PARKED",
};

/**
 * ViewKind identifies which page a capability's entry point navigates to.
 */
export enum ViewKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ViewRunbook = "runbook",
    ViewActivity = "activity",
    ViewPlaceholder = "placeholder",
};
