// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CapabilitiesService is the Wails-bound projection of Mill's own
 * capability registry (internal/domain/capabilities) -- a thin binding
 * layer, same shape as RunbookService/HotkeyService, no logic of its own
 * beyond exposing the domain package's data to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capabilities$0 from "./internal/domain/capabilities/models.js";

export function List(): $CancellablePromise<capabilities$0.Capability[] | null> {
    return $Call.ByID(2179630523);
}

/**
 * RepoPath returns the working directory the binary was launched from,
 * so the frontend can build an editor deep link (vscode://file/...) for
 * capabilities with an EditorPath. Only meaningful in dev mode: task dev
 * launches the binary with the repo root as cwd (confirmed this
 * session), but a real installed build has no source tree to jump to at
 * all -- the frontend gates every call behind import.meta.env.DEV.
 */
export function RepoPath(): $CancellablePromise<string> {
    return $Call.ByID(680259532);
}
