// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompositionService is the Wails-facing layer over the composition
 * domain package -- it holds no domain logic of its own (that's
 * internal/domain/composition), only the state and persistence a
 * stateless package can't own: user-composed workflows, mirroring
 * HotkeyService's already-proven shape (hotkeyservice.go) rather than
 * inventing a new one. See docs/SPEC.md §3's `UX: PROTOTYPE` entry for
 * what this is testing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composition$0 from "./internal/domain/composition/models.js";

/**
 * CreateWorkflow composes and configures a new workflow in one step, per
 * SPEC.md §3: ResolveStepDefaults validates every step's node type and
 * fills in any missing config with that field's default, so the stored
 * workflow is never partially configured.
 */
export function CreateWorkflow(label: string, description: string, steps: composition$0.Step[] | null): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(2784841854, label, description, steps);
}

/**
 * DeleteWorkflow removes a user-composed workflow. Built-in workflows
 * aren't in c.user at all, so a caller can never delete one -- no
 * special-case check needed, the ID space is naturally disjoint.
 */
export function DeleteWorkflow(id: string): $CancellablePromise<void> {
    return $Call.ByID(3977756313, id);
}

export function NodeTypes(): $CancellablePromise<composition$0.NodeType[] | null> {
    return $Call.ByID(966013356);
}

export function RunWorkflow(id: string): $CancellablePromise<string> {
    return $Call.ByID(3042871077, id);
}

/**
 * Workflows returns every built-in workflow followed by every
 * user-composed one, in creation order -- a stable, predictable order
 * for the UI rather than Go's randomized map iteration.
 */
export function Workflows(): $CancellablePromise<composition$0.Workflow[] | null> {
    return $Call.ByID(491101343);
}
