// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecutionService is the Wails-facing layer over
 * internal/adapters/execution's durable-workflow runtime -- it holds no
 * domain logic of its own (that's composition.ExecuteWorkflowWithStepRunner),
 * only the DBOS wiring and the Mill-specific run/step shapes a stateless
 * adapter package can't own, mirroring CompositionService's own split.
 * See docs/adr/0004's Update for the full workflow/step mapping this
 * implements.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetRun returns one run's full per-node step breakdown, joined against
 * its workflow definition's current Nodes (by ID) for display labels --
 * falls back to a bare step list (no labels) if the definition was
 * since edited/deleted, rather than failing the whole call over
 * missing display metadata.
 */
export function GetRun(runID: string): $CancellablePromise<$models.RunDetail> {
    return $Call.ByID(1654451054, runID);
}

/**
 * ListRuns returns recent runs across every workflow, most recent
 * first -- the data behind an Executions-style run-history list.
 */
export function ListRuns(): $CancellablePromise<$models.RunSummary[] | null> {
    return $Call.ByID(1409623953);
}

/**
 * RedriveRun forks runID from the given node's step, reusing every
 * earlier step's checkpointed output instead of re-executing it --
 * Mill's "fix forward" mechanism (docs/adr/0004's Update), most useful
 * after correcting a Connector/List/MCP Server's Configure-page setup
 * in between, since those resolve live at execution time.
 */
export function RedriveRun(runID: string, fromNodeID: string): $CancellablePromise<$models.RunSummary> {
    return $Call.ByID(2286136771, runID, fromNodeID);
}

/**
 * RunWorkflowDurable runs a composed workflow through the durable
 * execution path -- every node's result is checkpointed and the run
 * stays visible/redrivable afterward (ListRuns/GetRun/RedriveRun),
 * unlike CompositionService.RunWorkflow's plain in-memory execution
 * (left untouched -- this is an additive entry point, not a
 * replacement, so the existing Composition/Runbook "Run" button and its
 * e2e coverage are unaffected).
 */
export function RunWorkflowDurable(workflowID: string): $CancellablePromise<$models.RunSummary> {
    return $Call.ByID(4082714576, workflowID);
}
