// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HotkeyService registers global (system-wide) hotkeys that trigger a
 * Runbook action. Assignments persist across restarts via the settings
 * store (see RestoreBindings) -- see docs/SPEC.md §2.2.
 * 
 * The fire path (OS delivers a keypress -> action runs -> clipboard is
 * written) has no UI surface at all, unlike the Run button's inline
 * success/error rendering — a hotkey that's registered but never fires
 * (e.g. the combo is already claimed by another app, or macOS just never
 * delivers it) is otherwise silent and undebuggable. logger makes every
 * stage of that path visible instead of guessing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Assign registers a global hotkey for the given action. mods is any
 * combination of "cmd", "ctrl", "shift", "option"/"alt"; at least one is
 * required so a bare letter never becomes a system-wide hotkey by accident.
 * Returns the human-readable binding label (e.g. "⌘⇧M") on success.
 */
export function Assign(actionID: string, mods: string[] | null, key: string): $CancellablePromise<string> {
    return $Call.ByID(2641493738, actionID, mods, key);
}

export function List(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(4089836139);
}

export function Unassign(actionID: string): $CancellablePromise<void> {
    return $Call.ByID(435179525, actionID);
}
