// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HotkeyActivity is emitted once a triggered workflow resolves (success
 * or failure) -- not just hotkey fires despite the name (kept for the
 * event's own wire compatibility; renaming the event string itself would
 * be a cosmetic-only churn no caller needs). The Go-side slog lines
 * (triggerservice.go) log the same information for terminal/`task dev`
 * visibility; this event is the in-app equivalent, so a headless
 * trigger's outcome is visible without a terminal — added after a real
 * hotkey worked correctly (fired, ran, wrote to the clipboard) but
 * looked from the UI like nothing happened, because nothing in the UI
 * ever said otherwise.
 */
export interface HotkeyActivity {
    "workflowID": string;
    "binding": string;
    "success": boolean;
    "detail": string;

    /**
     * Result is the actual output copied to the clipboard, so the UI can
     * show what a trigger fire actually produced, not just its byte count.
     * Empty on failure -- there's nothing successful to show.
     */
    "result": string;
}

/**
 * RunDetail is a RunSummary plus its full per-node step breakdown.
 */
export interface RunDetail {
    "runID": string;
    "workflowID": string;
    "workflowLabel": string;
    "status": string;
    "kind": RunKind;
    "output": string;
    "startedAt": string;
    "completedAt": string;
    "error": string;
    "steps": RunStep[] | null;
}

/**
 * RunKind classifies why a run started (docs/adr/0008) -- "test" for a
 * manual/UI-driven run (Composition's canvas Run button, the Runs page's
 * own quick-run picker), "triggered" for a real external event
 * (TriggerService's headless listeners; not wired to this path yet, see
 * ADR-0008's own named follow-on). Not a DBOS SetWorkflowAttributes call
 * -- travels in runInput alongside every other per-run value, the
 * existing pattern this struct already uses.
 */
export enum RunKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RunKindTest = "test",
    RunKindTriggered = "triggered",
};

/**
 * RunStep is one node's recorded execution within a run, for the
 * execution-visibility UI (docs/SPEC.md §3.2's "shows through the path
 * ... where it stopped", researched from [decisioning-vendor]/n8n). Status is
 * "succeeded"/"failed"/"pending" -- pending means DBOS has no recorded
 * step yet (the run never reached that node).
 */
export interface RunStep {
    "nodeID": string;
    "nodeTypeID": string;
    "nodeTypeLabel": string;
    "status": string;
    "output": string;
    "error": string;
}

/**
 * RunSummary is one run's headline state -- the row shape for a
 * run-history list.
 */
export interface RunSummary {
    "runID": string;
    "workflowID": string;
    "workflowLabel": string;
    "status": string;
    "kind": RunKind;
    "output": string;
    "startedAt": string;
    "completedAt": string;
    "error": string;
}

/**
 * UpdateCheckResult is CheckForUpdates' Wails-bound result shape.
 */
export interface UpdateCheckResult {
    "updateAvailable": boolean;
    "version": string;
    "notes": string;
}
