// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connector$0 from "./internal/domain/connector/models.js";

/**
 * HotkeyActivity is emitted once a triggered workflow resolves (success
 * or failure) -- not just hotkey fires despite the name (kept for the
 * event's own wire compatibility; renaming the event string itself would
 * be a cosmetic-only churn no caller needs). The Go-side slog lines
 * (triggerservice.go) log the same information for terminal/`task dev`
 * visibility; this event is the in-app equivalent, so a headless
 * trigger's outcome is visible without a terminal — added after a real
 * hotkey worked correctly (fired, ran, wrote to the clipboard) but
 * looked from the UI like nothing happened, because nothing in the UI
 * ever said otherwise.
 */
export interface HotkeyActivity {
    "workflowID": string;
    "binding": string;
    "success": boolean;
    "detail": string;

    /**
     * Result is the actual output copied to the clipboard, so the UI can
     * show what a trigger fire actually produced, not just its byte count.
     * Empty on failure -- there's nothing successful to show.
     */
    "result": string;
}

/**
 * RunDetail is a RunSummary plus its full per-node step breakdown.
 */
export interface RunDetail {
    "runID": string;
    "workflowID": string;
    "workflowLabel": string;
    "status": string;
    "kind": RunKind;
    "output": string;
    "startedAt": string;
    "completedAt": string;
    "error": string;
    "steps": RunStep[] | null;
}

/**
 * RunKind classifies why a run started (docs/adr/0008) -- "test" for a
 * manual/UI-driven run (Composition's canvas Run button, the Runs page's
 * own quick-run picker), "triggered" for a real external event
 * (TriggerService's headless listeners; not wired to this path yet, see
 * ADR-0008's own named follow-on). Not a DBOS SetWorkflowAttributes call
 * -- travels in runInput alongside every other per-run value, the
 * existing pattern this struct already uses.
 */
export enum RunKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RunKindTest = "test",
    RunKindTriggered = "triggered",
};

/**
 * RunStep is one node's recorded execution within a run, for the
 * execution-visibility UI (docs/SPEC.md §3.2's "shows through the path
 * ... where it stopped", researched from [decisioning-vendor]/n8n). Status is
 * "succeeded"/"failed"/"pending" -- pending means DBOS has no recorded
 * step yet (the run never reached that node).
 */
export interface RunStep {
    "nodeID": string;
    "nodeTypeID": string;
    "nodeTypeLabel": string;
    "status": string;
    "output": string;
    "error": string;
}

/**
 * RunSummary is one run's headline state -- the row shape for a
 * run-history list.
 */
export interface RunSummary {
    "runID": string;
    "workflowID": string;
    "workflowLabel": string;
    "status": string;
    "kind": RunKind;
    "output": string;
    "startedAt": string;
    "completedAt": string;
    "error": string;
}

/**
 * TestConnectorRequest carries a connector draft (possibly unsaved --
 * docs/adr/0013) plus the one operation to call and example field
 * values. Config comes as plain values (BaseURL/AuthType/Headers/
 * OpenAPISpec), not a Connector ID, so testing the connector currently
 * on screen works identically whether it's brand-new or mid-edit of an
 * existing one -- the RPC never reads c.connectors for config, only
 * (via ConnectorID, below) as a secret fallback.
 */
export interface TestConnectorRequest {
    /**
     * ConnectorID is optional. Set it when editing an existing connector
     * and Secret is left blank ("keep the existing secret," matching
     * ConnectorForm's own Auth-tab caption) -- the RPC then falls back to
     * this connector's stored keychain secret, the same read
     * resolveConnector already does for a real workflow run.
     */
    "ConnectorID": string;
    "BaseURL": string;
    "AuthType": connector$0.AuthType;
    "Headers": { [_ in string]?: string } | null;

    /**
     * Secret is used as typed, for this call only -- TestConnectorOperation
     * never calls credential.Set, so a tested-then-abandoned draft leaves
     * no keychain trace.
     */
    "Secret": string;
    "OpenAPISpec": string;
    "Path": string;
    "Method": string;

    /**
     * Values is a flat map of example (generated or hand-edited) field
     * values keyed by the operation's declared Field.Name, resolved into
     * path/query/header/body placement by openapispec.BuildRequest.
     */
    "Values": { [_ in string]?: string } | null;
}

/**
 * TestConnectorResult is one test call's outcome. Error carries a
 * transport-level failure (DNS, timeout, connection refused) as a
 * string rather than surfacing it as a Go error -- both this and a
 * real HTTP response (including 4xx/5xx, which httpconnector.Execute
 * already treats as a non-error return, docs/SPEC.md §4) are equally
 * "a test attempt with a result," and the frontend's request/response
 * log (ADR-0013 §6) wants to display either uniformly rather than
 * branching on error-vs-response.
 */
export interface TestConnectorResult {
    "StatusCode": number;
    "Body": string;
    "Headers": { [_ in string]?: string } | null;
    "Error": string;
    "DurationMs": number;
}

/**
 * UpdateCheckResult is CheckForUpdates' Wails-bound result shape.
 */
export interface UpdateCheckResult {
    "updateAvailable": boolean;
    "version": string;
    "notes": string;
}
