// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HotkeyActivity is emitted once a triggered workflow resolves (success
 * or failure) -- not just hotkey fires despite the name (kept for the
 * event's own wire compatibility; renaming the event string itself would
 * be a cosmetic-only churn no caller needs). The Go-side slog lines
 * above log the same information for terminal/`task dev` visibility;
 * this event is the in-app equivalent, so a headless trigger's outcome
 * is visible without a terminal -- added after a real hotkey worked
 * correctly (fired, ran, wrote to the clipboard) but looked from the UI
 * like nothing happened, because nothing in the UI ever said otherwise.
 * Lives with TriggerService (its emitter); main.go imports it for
 * application.RegisterEvent.
 */
export interface HotkeyActivity {
    "workflowID": string;
    "binding": string;
    "success": boolean;
    "detail": string;

    /**
     * Result is the actual output copied to the clipboard, so the UI can
     * show what a trigger fire actually produced, not just its byte count.
     * Empty on failure -- there's nothing successful to show.
     */
    "result": string;
}

export interface PersistedHotkey {
    "mods": string[] | null;
    "key": string;
}
