// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capabilities$0 from "../capabilities/models.js";

/**
 * Approach records whether a capability's mechanism is bought (an
 * existing library) or must stay Mill's own hand-written code, per
 * CLAUDE.md's adopt-over-hand-roll rule. Mixed means a capability splits
 * cleanly into an adoptable mechanism plus a composition rule that can't
 * be bought regardless of mechanism -- see ApproachDetail for which is
 * which.
 */
export enum Approach {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ApproachAdopt = "adopt",
    ApproachBuild = "build",
    ApproachMixed = "mixed",
};

/**
 * ConfigField declares one configurable parameter a node type's nodes
 * can set. A node type with no ConfigFields takes no parameters --
 * legitimately true for some nodes (capture/process here operate on
 * whatever's piped in), not a placeholder to fill in later.
 */
export interface ConfigField {
    "Key": string;
    "Label": string;
    "Description": string;
    "Default": string;
}

/**
 * Edge connects one Node's output to another's input by ID. SourceHandle
 * is reserved for a future Decision node's named branches (e.g. "yes"/
 * "no") -- empty for every edge today, since no node kind branches yet.
 */
export interface Edge {
    "ID": string;
    "Source": string;
    "SourceHandle": string;
    "Target": string;
}

/**
 * MapEntry is one row of Mill's composition capability map -- real Go
 * data mirroring docs/SPEC.md §3.3's table, the same "authoritative
 * machine-read projection, SPEC.md's own tags stay human-readable
 * commentary" relationship internal/domain/capabilities already has to
 * its own SPEC.md sections (§2.2's decision record). SPEC.md §3.3 is the
 * source of the reasoning; this is what the UI reads.
 */
export interface MapEntry {
    "ID": string;
    "Name": string;
    "WhatItDoes": string;
    "Approach": Approach;
    "ApproachDetail": string;
    "Status": capabilities$0.Status;
    "StatusDetail": string;
}

/**
 * Node is one configured instance of a node type inside a workflow's
 * graph. Config is always fully resolved (every ConfigField's key
 * present) by the time a Node is stored or executed -- see
 * ResolveNodeDefaults. Kind is always derived server-side from
 * NodeTypeID (never trusted from the client), so it can't drift out of
 * sync with the node type it names.
 */
export interface Node {
    "ID": string;
    "Kind": NodeKind;
    "NodeTypeID": string;
    "Config": { [_ in string]?: string } | null;
    "Position": Position;
}

/**
 * NodeKind mirrors SPEC.md §2's Capture -> Process -> Apply primitive --
 * today's node types are drawn from that already-locked shape rather
 * than the fuller Ruleset/Decision/... taxonomy ADR-0005 surveys, since
 * only Capture/Process/Apply nodes exist as real code yet. Control-flow
 * node kinds (Decision, Parallel, Child Workflow) stay real future work,
 * not stubbed here speculatively.
 */
export enum NodeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindCapture = "capture",
    KindProcess = "process",
    KindApply = "apply",
};

export interface NodeType {
    "ID": string;
    "Kind": NodeKind;
    "Label": string;
    "Description": string;
    "ConfigFields": ConfigField[] | null;
}

/**
 * Position is a node's canvas coordinates. Ignored by execution entirely
 * -- it exists purely for the React Flow canvas to restore a workflow's
 * layout, matching React Flow's own node shape.
 */
export interface Position {
    "X": number;
    "Y": number;
}

/**
 * Workflow is a node/edge graph -- today always a single unbranched
 * chain in practice (see linearOrder), since Decision/Parallel/Child-
 * Workflow node kinds are real future work per ADR-0005, not invented
 * here ahead of a need for them.
 */
export interface Workflow {
    "ID": string;
    "Label": string;
    "Description": string;
    "Nodes": Node[] | null;
    "Edges": Edge[] | null;

    /**
     * BuiltIn marks a seeded, non-deletable workflow (the two shipped
     * with this prototype) vs. one a user composed and that persisted --
     * the UI badges/protects built-ins accordingly.
     */
    "BuiltIn": boolean;
}
