// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NodeKind mirrors SPEC.md §2's Capture -> Process -> Apply primitive --
 * today's node types are drawn from that already-locked shape rather
 * than the fuller Ruleset/Decision/... taxonomy ADR-0005 surveys, since
 * only Capture/Process/Apply nodes exist as real code yet. Control-flow
 * node kinds (Decision, Parallel, Child Workflow) stay real future work,
 * not stubbed here speculatively.
 */
export enum NodeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindCapture = "capture",
    KindProcess = "process",
    KindApply = "apply",
};

export interface NodeType {
    "ID": string;
    "Kind": NodeKind;
    "Label": string;
    "Description": string;
}

/**
 * Recipe is a flat, ordered pipeline of node type IDs -- enough for
 * today's two real recipes. Branching/parallel composition is real
 * future work per ADR-0005, not invented here ahead of a need for it.
 */
export interface Recipe {
    "ID": string;
    "Label": string;
    "Description": string;
    "NodeIDs": string[] | null;
}
