// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AtlasService holds Atlas's full in-memory state behind one mutex,
 * same shape as GuardrailService/CompositionService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as atlas$0 from "../../domain/atlas/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../../domain/typedfield/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLinkedCard is CreateCardLinkedFrom's own "generic kind" door: the
 * card menu's "Add linked card…" item (goal 0081 slice A4), which
 * links through the built-in relates-to kind rather than naming one --
 * same graceful-fallback resolution CreateLinkedFileCard's own
 * resolveRelatesToLinkKindLocked already establishes, and the same
 * "parent = the linking card's own parent" rule the LOCKED design's
 * card-foremost creation door (§2b) requires: a linked sibling lands
 * beside the card that named it, never wherever the board happens to
 * be scrolled.
 */
export function AddLinkedCard(fromCardID: string, kindID: string, title: string, position: atlas$0.Position | null): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(1483030434, fromCardID, kindID, title, position);
}

/**
 * AddToPerspective adds cardID to perspectiveID, closed under ancestry
 * (ADR-0041): every container between cardID and the perspective's own
 * SpaceID joins with it, so a deeply nested card never appears in a
 * filtered view floating with no visible container. Rejects a cardID
 * that does not actually live inside the perspective's space.
 */
export function AddToPerspective(perspectiveID: string, cardID: string): $CancellablePromise<atlas$0.Perspective> {
    return $Call.ByID(420793018, perspectiveID, cardID);
}

/**
 * AtlasSession returns the persisted state, DEGRADED to what still
 * exists: a fully-gone viewed card falls back to root; a tombstoned
 * one (goal 0093) resolves to its own effective parent -- the same
 * virtual-promotion walk every other read surface applies
 * (atlas.EffectiveParentID) -- so a session parked inside a container
 * deleted just before restart lands one level up, not all the way to
 * root. A deleted (gone or tombstoned) open card is dropped. The
 * caller never has to handle a stale id.
 */
export function AtlasSession(): $CancellablePromise<$models.AtlasSessionState> {
    return $Call.ByID(3581313171);
}

/**
 * BeginUndoMark/EndUndoMark let the frontend group several door calls
 * made within one user gesture into ONE undo step (ADR-0044 decision 2
 * -- "everything inside one mark undoes atomically"): the 0215 gesture
 * engine's own start/end boundaries, and a multi-select group action
 * (delete, paste-landing). Nested calls are supported (depth-counted)
 * so a helper that itself opens/closes a mark can be called from inside
 * an already-open one without splitting it. A door called with no mark
 * open gets its own one-entry mark automatically (recordUndo's
 * markID == 0 branch) -- most doors never need these at all.
 */
export function BeginUndoMark(): $CancellablePromise<void> {
    return $Call.ByID(3659071004);
}

/**
 * CardContextBlock renders cardID's fields/note/links as one stable,
 * paste-ready text block (goal 0063's copy-as-context) -- the Card
 * overlay/chip's "Copy as context" action copies exactly this string.
 */
export function CardContextBlock(cardID: string, withAttachments: boolean): $CancellablePromise<string> {
    return $Call.ByID(4150547692, cardID, withAttachments);
}

/**
 * CardContextEnvelope renders a card as the OUT envelope (goal 0099):
 * its data as items, the reply contract inline. The plain-text
 * CardContextBlock stays for human destinations; this is the
 * machine-readable twin an external AI answers against.
 */
export function CardContextEnvelope(cardID: string): $CancellablePromise<string> {
    return $Call.ByID(1724710751, cardID);
}

/**
 * CardListProjection resolves a projection card's render data. A
 * card without a projection returns the zero value (ListID "");
 * a projection whose List was deleted returns Missing=true with the
 * stored id, never an error -- the card face owns the honest copy.
 */
export function CardListProjection(cardID: string): $CancellablePromise<$models.ListProjection> {
    return $Call.ByID(390246853, cardID);
}

/**
 * CardSourceOffer resolves a card's recognition state: whether its
 * Source URL host matches a configured Integration, and which
 * workflows declare that Integration as their offer target.
 */
export function CardSourceOffer(cardID: string): $CancellablePromise<$models.CardSourceOffer> {
    return $Call.ByID(217270429, cardID);
}

/**
 * Cards returns every LIVE card (goal 0093: a tombstoned card is
 * excluded, and a live child of a tombstoned container carries its
 * resolved effective ParentID -- see liveCardsLocked).
 */
export function Cards(): $CancellablePromise<atlas$0.Card[] | null> {
    return $Call.ByID(4038798409);
}

/**
 * CardsByKind returns every card of kindID -- the apply-atlas-card-find
 * step's own read (goal 0066), via composition.SetAtlasCardFinder.
 */
export function CardsByKind(kindID: string): $CancellablePromise<atlas$0.Card[] | null> {
    return $Call.ByID(1757324970, kindID);
}

/**
 * Contents lists live entries matching filter, sorted by kind then
 * title then id -- a stable order every door shares.
 */
export function Contents(filter: $models.ContentsFilter): $CancellablePromise<$models.ContentEntry[] | null> {
    return $Call.ByID(951604272, filter);
}

/**
 * ConvertHTMLToMarkdown is the paste door's own HTML branch (LOCKED
 * design §2b/§3b): clipboard HTML converts to Markdown through the
 * exact same domain function process-html-to-markdown's workflow node
 * already runs (internal/adapters/markdown.ToMarkdown) before the
 * placement popover ever opens -- never a second, JS-side converter.
 */
export function ConvertHTMLToMarkdown(html: string): $CancellablePromise<string> {
    return $Call.ByID(989919804, html);
}

/**
 * CorrectionEnvelope re-emits the reply contract for the
 * re-ask-the-source loop: validation problems and declined titles ride
 * the instruction line, the schema stays the instruction.
 */
export function CorrectionEnvelope(problems: string[] | null, declinedTitles: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(4009289398, problems, declinedTitles);
}

/**
 * CreateBoardObject makes a new BoardObject of kind, optionally inside
 * parentID ("" for root-level) -- same containment-existence check
 * CreateNote runs. payload is copied so the caller's own map can't
 * mutate stored state after the call returns.
 */
export function CreateBoardObject(kind: string, payload: { [_ in string]?: string } | null, pos: atlas$0.Position, parentID: string): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(1667723317, kind, payload, pos, parentID);
}

/**
 * CreateCard makes a new Card of kindID, optionally inside parentID
 * ("" for root-level). A non-empty parentID must name an existing
 * card; a fresh card can never itself be a cycle (it has no children
 * yet), so no cycle check is needed here -- MoveCard is where
 * reparenting an EXISTING card (which may have its own descendants)
 * needs one.
 */
export function CreateCard(kindID: string, title: string, note: string, fields: { [_ in string]?: string } | null, parentID: string, position: atlas$0.Position | null, viewMode: atlas$0.ViewMode, source: string, mirrorPath: string, refreshWorkflowID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(3093996908, kindID, title, note, fields, parentID, position, viewMode, source, mirrorPath, refreshWorkflowID);
}

/**
 * CreateCardFromFileDrop is the instant single-file landing door
 * (LOCKED design §3b): kind derived from path's extension, MirrorPath
 * set to path itself (mirror-only, decision 4 -- the map never copies
 * file content into its own ownership), no popover. title/parentID/
 * position are the frontend's own resolved values (title from the
 * filename, parent from the drop context's frame/zoomed area, position
 * from the drop point) -- this method only resolves the one piece of
 * seeded-concept knowledge (which Kind) that must never live in
 * frontend source (atlasNoHardcode.test.ts). A duplicate is looked up
 * against path's own checksum BEFORE the card is created, but never
 * blocks creation -- an unreadable path just skips the checksum/
 * duplicate check silently, same fail-open posture the folder-scan
 * backfill takes.
 */
export function CreateCardFromFileDrop(path: string, title: string, parentID: string, position: atlas$0.Position | null): $CancellablePromise<$models.FileDropCreateResult> {
    return $Call.ByID(1912608055, path, title, parentID, position);
}

/**
 * CreateCardLinkedFrom atomically creates a new card AND links it from
 * fromCardID via linkKindID, in one locked critical section (same
 * single-persist/single-rollback shape PromoteNote and
 * CreateLinkedFileCard already establish) -- the slot-drag guided-
 * create door (goal 0081 slice A4, LOCKED design decision D1=B):
 * releasing a link-slot drag on empty canvas names a thing and its
 * relation in one motion, with no partial state -- a card with no
 * link, or a link to nothing -- ever left behind on failure.
 * linkKindID is caller-supplied (the dragged row already named its own
 * kind); parentID/position are the frontend's own resolved "where you
 * are" values, same convention every other canvas-foremost creation
 * door already follows.
 */
export function CreateCardLinkedFrom(fromCardID: string, linkKindID: string, kindID: string, title: string, parentID: string, position: atlas$0.Position | null): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(2183741437, fromCardID, linkKindID, kindID, title, parentID, position);
}

export function CreateKind(label: string, description: string, icon: string, fields: typedfield$0.Field[] | null): $CancellablePromise<atlas$0.Kind> {
    return $Call.ByID(3663898672, label, description, icon, fields);
}

export function CreateLink(fromCardID: string, toCardID: string, linkKindID: string, label: string): $CancellablePromise<atlas$0.Link> {
    return $Call.ByID(3449865750, fromCardID, toCardID, linkKindID, label);
}

export function CreateLinkKind(label: string, description: string): $CancellablePromise<atlas$0.LinkKind> {
    return $Call.ByID(2065966488, label, description);
}

/**
 * CreateLinkedFileCard is card-foremost file drop (D5, LOCKED design):
 * while a card's page is open, a dropped file becomes a LINKED SIBLING
 * -- same parent as the open card, plus the generic association link
 * kind (resolveRelatesToLinkKindLocked) from the open card to the new
 * one -- atomically: the card and the link either both persist or
 * neither does, so the open card's own links section is never observed
 * in a half-written state. The open card itself is never mutated.
 */
export function CreateLinkedFileCard(openCardID: string, path: string, title: string, position: atlas$0.Position | null): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(3955305419, openCardID, path, title, position);
}

/**
 * CreateNote makes a new Note, optionally inside parentID ("" for
 * root-level) -- same containment-existence check CreateCard runs.
 */
export function CreateNote(text: string, pos: atlas$0.Position, parentID: string): $CancellablePromise<atlas$0.Note> {
    return $Call.ByID(1216295546, text, pos, parentID);
}

/**
 * CreatePerspective makes a new Perspective over spaceID ("" for the
 * true root), appended at the end of that space's own ordered set.
 */
export function CreatePerspective(spaceID: string, name: string, description: string): $CancellablePromise<atlas$0.Perspective> {
    return $Call.ByID(3910340284, spaceID, name, description);
}

/**
 * DebugLastOpenedURLs returns every URL osopen's in-memory Port has
 * recorded so far, oldest first. Gated to MILL_OPEN=memory -- the same
 * posture SecretService.DebugCorruptVaultKeyForTests holds against
 * MILL_TEST_KEYRING=memory -- so this can never be called expecting a
 * Host it didn't get.
 */
export function DebugLastOpenedURLs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(797912538);
}

/**
 * DeleteBoardObject soft-deletes a board object (goal 0179/0180) --
 * same tombstone contract as DeleteCard's own seed-tombstone bookkeeping
 * (goal 0223 gives BoardObject the same BuiltIn/Seed provenance Card
 * already carries), minus DeleteCard's link/child blast radius (a
 * board object can be neither a link endpoint nor a container).
 */
export function DeleteBoardObject(id: string): $CancellablePromise<$models.TombstoneResult> {
    return $Call.ByID(309976208, id);
}

/**
 * DeleteCard soft-deletes a card (goal 0093's quick-delete-with-undo
 * guard): stamps DeletedAt and leaves ParentID/children untouched --
 * no data rewrite happens until the boot-time purge; every live child
 * simply resolves its effective parent (atlas.EffectiveParentID) past
 * this tombstone in the meantime, so undo needs nothing more than
 * clearing the stamp back. A built-in card's seed tombstone is
 * recorded immediately, same timing the previous hard-delete already
 * used, since a deleted built-in must not be topped up by reconcile
 * while it's hidden.
 */
export function DeleteCard(id: string): $CancellablePromise<$models.TombstoneResult> {
    return $Call.ByID(3764094639, id);
}

/**
 * DeleteKind removes a Kind, blocked while any Card still references
 * it -- no orphaning (docs/goals/0061's Deletion semantics; goal 0046
 * will refine reference handling further, not duplicated here).
 */
export function DeleteKind(id: string): $CancellablePromise<void> {
    return $Call.ByID(694706355, id);
}

export function DeleteLink(id: string): $CancellablePromise<void> {
    return $Call.ByID(1590515097, id);
}

/**
 * DeleteLinkKind removes a LinkKind, blocked while any Link still
 * references it -- same no-orphaning rule as DeleteKind.
 */
export function DeleteLinkKind(id: string): $CancellablePromise<void> {
    return $Call.ByID(1735554023, id);
}

/**
 * DeleteNote soft-deletes a note -- same tombstone contract as
 * DeleteCard, minus the seed-tombstone bookkeeping (notes carry no
 * seed provenance).
 */
export function DeleteNote(id: string): $CancellablePromise<$models.TombstoneResult> {
    return $Call.ByID(3922503309, id);
}

/**
 * DeletePerspective removes a perspective immediately -- no tombstone/
 * undo lifecycle (ADR-0041): cheap to recreate. A session parked on
 * this perspective degrades to the everything view the next time
 * AtlasSession is read; nothing else references a Perspective's id, so
 * there is no further referential cleanup to do here.
 */
export function DeletePerspective(id: string): $CancellablePromise<void> {
    return $Call.ByID(2541135077, id);
}

/**
 * DetectSyncRoots reports which well-known cloud-sync folders
 * (OneDrive/Dropbox/iCloud Drive) exist on disk, most-likely-first --
 * an os.Stat existence check only, never a listing or a read (goal
 * 0067's "detection is fine, action is not"). The frontend uses the
 * first hit to pre-fill PickFolder's own starting location; only the
 * user's own explicit choice in that dialog authorizes anything to be
 * scanned. A method (rather than a plain function) purely so the Wails
 * binding generator exposes it as a frontend RPC -- it reads no
 * AtlasService state.
 */
export function DetectSyncRoots(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2360667167);
}

/**
 * DiffPerspectives computes what changed moving from fromID's own
 * membership to toID's (goal 0095 slice 3's Compare view): a thin
 * bound wrapper over the pure atlas.DiffPerspectives helper, the same
 * "expose the domain package's own pure function through a read-only
 * accessor" shape Perspectives() itself already takes. Re-parenting is
 * deliberately never expressed here -- ADR-0041's own invariant, since
 * a card carries exactly one ParentID shared by every perspective.
 */
export function DiffPerspectives(fromID: string, toID: string): $CancellablePromise<atlas$0.PerspectiveDiff> {
    return $Call.ByID(3383492038, fromID, toID);
}

export function EndUndoMark(): $CancellablePromise<void> {
    return $Call.ByID(301791156);
}

/**
 * ExportAtlas serializes the whole Atlas graph as an indented, portable
 * JSON string -- share it, commit it to git, or import it into another
 * Mill instance. Read-only: never mutates a's state. Deterministic by
 * construction (every field is already-stored data in stable slice
 * order): exporting twice with no intervening change produces
 * byte-identical bytes, the same guarantee every other exported* shape
 * in this codebase carries.
 */
export function ExportAtlas(): $CancellablePromise<string> {
    return $Call.ByID(1261911391);
}

/**
 * ExportBoardAsDrawio serializes spaceID's own board (its card subtree,
 * any depth, plus its shape/diagram board objects) into a .drawio file.
 * spaceID == "" exports the top-level board. Read-only.
 */
export function ExportBoardAsDrawio(spaceID: string): $CancellablePromise<$models.BoardDrawioExport> {
    return $Call.ByID(1721831298, spaceID);
}

/**
 * ImportAtlas applies ADR-0036 decision 3's uniform import rule to
 * EVERY entity inside jsonData's bundle independently: id absent ->
 * create fresh; id present and known locally -> update in place; id
 * present and unknown locally -> create preserving that id. Order is
 * Kinds/LinkKinds first (Cards reference them by id), then Cards in two
 * passes -- pass one creates/updates every card's own content with no
 * containment yet (so a bundle can list a child before its parent),
 * pass two applies ParentID/Position now that every bundled card exists
 * locally, through the existing MoveCard/SetPosition chokepoints (their
 * own cycle-rejection applies unchanged). A card whose bundle entry
 * omits ParentID is left wherever it already is when updating an
 * EXISTING card -- omitempty can't distinguish "explicitly root" from
 * "field not declared" (the same nil-vs-empty ambiguity
 * UpdateWorkflowFromExport's own doc comment already documents for
 * Attributes/Notes), so import only ever ADDS/changes containment,
 * never implicitly clears it. Links import last, once every card and
 * LinkKind they reference exists.
 */
export function ImportAtlas(jsonData: string): $CancellablePromise<$models.AtlasImportSummary> {
    return $Call.ByID(1577571942, jsonData);
}

/**
 * ImportFolderSuggestions is the only place a folder-scan suggestion
 * becomes a real card -- goal 0067's preview/confirm boundary. It
 * RE-SCANS root itself (bounded, same caps ScanFolder uses) rather
 * than trusting the frontend's own copy of the tree back: a stale
 * preview (the folder changed between scan and confirm) then fails
 * closed on whatever no longer matches AcceptedRelPaths, instead of
 * importing something the user never actually saw. Containers are
 * created before their own children (ordered by path depth) so
 * containment always resolves to a real card id; an accepted entry
 * whose own parent directory was NOT accepted attaches directly under
 * TargetParentID instead of being dropped.
 * 
 * A FILE entry is synced through the same syncMirrorCard primitive
 * SyncLedgerFolder uses (goal 0178 S1): keyed by its own absolute
 * MirrorPath, an existing card there is refreshed in place (checksum
 * updated, and its Kind's coerced frontmatter fields re-merged --
 * atlas.CoerceFrontmatterFields, MergeCardFields -- so a Kind field the
 * file doesn't carry, an owner-owned value like a proposed status,
 * stays untouched by construction, goal 0172 S1), and re-importing an
 * unchanged file is a pure no-op.
 * 
 * The match is scoped to the entry's own freshly-resolved PARENT
 * (scopedMirrorLookup), never the whole atlas: goal 0088 already lets a
 * user import matching content into a DIFFERENT space on purpose (the
 * duplicate flag is advisory, never blocking), and that must keep
 * creating its own independent card there, not silently merge into a
 * card living somewhere else entirely.
 * 
 * A DIRECTORY entry (goal 0178 S2) now carries a MirrorPath too -- its
 * own source folder -- so a container is resolved through the exact
 * same scopedMirrorLookup identity as a file: re-importing a NESTED
 * folder into the same target reuses the existing container's id
 * instead of recreating it, which is what makes everything below it
 * resolve to the SAME parent on every run and therefore idempotent all
 * the way down, not just at the root level. Giving a container a
 * MirrorPath also turns on the mirror-file UI (freshness dot, reveal-
 * in-Finder) for it -- the deliberate S2 design decision, since a
 * container mirroring a folder is just as real a stale-able snapshot
 * as a file mirroring one, more so: a folder can gain and lose members
 * while every file inside it stays byte-identical.
 */
export function ImportFolderSuggestions(req: $models.ImportFolderSuggestionsRequest): $CancellablePromise<$models.FolderImportSummary> {
    return $Call.ByID(2984363720, req);
}

export function Kinds(): $CancellablePromise<atlas$0.Kind[] | null> {
    return $Call.ByID(3099018285);
}

/**
 * Lens returns the persisted lens setting for containerID -- the zero
 * value (no hidden kinds, peek off) when none is set.
 */
export function Lens(containerID: string): $CancellablePromise<atlas$0.LensSetting> {
    return $Call.ByID(1926175606, containerID);
}

export function LinkKinds(): $CancellablePromise<atlas$0.LinkKind[] | null> {
    return $Call.ByID(1481666021);
}

/**
 * Links returns every link whose endpoints are both LIVE cards (goal
 * 0093: a link touching a tombstoned card is hidden, never removed).
 */
export function Links(): $CancellablePromise<atlas$0.Link[] | null> {
    return $Call.ByID(1082434947);
}

/**
 * ListContents is the Wails-bound door onto Contents (plugin SDK
 * api.query, the Contents view). Never nil.
 */
export function ListContents(kind: string, parentID: string): $CancellablePromise<$models.ContentEntry[] | null> {
    return $Call.ByID(804981692, kind, parentID);
}

/**
 * MirrorContent resolves cardID's MirrorPath into a read-only overlay
 * preview: markdown renders to HTML, plain text passes through as-is,
 * an image or a binary spreadsheet becomes base64-encoded bytes paired
 * with its MIME type, and anything else (or anything over
 * mirrorPreviewMaxBytes) reports only its kind and size -- the
 * overlay's existing reveal-file action is what a user reaches for
 * beyond that.
 */
export function MirrorContent(cardID: string): $CancellablePromise<atlas$0.MirrorContent> {
    return $Call.ByID(3797489642, cardID);
}

/**
 * MirrorImageFromPath copies srcPath's own bytes into a fresh file under
 * the captures directory, returning the new file's path -- the
 * data-safety half of a native image drop (goal 0206): the OS may hand
 * a drop event a temp/promise path under /var/folders (a drag from a
 * screenshot thumbnail or another app materializes a file promise
 * there) that it reclaims once the drag completes, so a drop-created
 * object's own MirrorPath must point at a copy Mill owns, never the
 * ephemeral original. Reuses SaveImageBytes's own writer/validation
 * rather than a second copy of either. Bounded by fileread.MaxBytes.
 */
export function MirrorImageFromPath(srcPath: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(3133722493, srcPath, title);
}

/**
 * MirrorRawBytes returns cardID's mirrored file as base64-encoded raw
 * bytes, regardless of MirrorKind (the Export-as "Original file"
 * default every mirror-bearing card gets, ADR-0043 §3/goal 0133).
 * MirrorContent above deliberately withholds content for
 * MirrorKindOther -- a PREVIEW safety gate answering "is this safe to
 * interpret as text/HTML" -- but handing raw bytes back for direct
 * download, never parsed or rendered by Mill itself, carries none of
 * that risk, so this method applies the same size cap without the kind
 * gate.
 */
export function MirrorRawBytes(cardID: string): $CancellablePromise<string> {
    return $Call.ByID(2790462688, cardID);
}

/**
 * MoveBoardObject reparents a board object (drag filing into/out of an
 * area frame) -- same containment-existence check CreateBoardObject
 * runs. A board object can never contain anything, so no cycle check
 * is needed the way MoveCard's atlas.WouldCycle is.
 */
export function MoveBoardObject(id: string, newParentID: string): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(37708762, id, newParentID);
}

/**
 * MoveCard reparents a card (sibling-vs-child move, ADR-0038's
 * create-time framing extended to a later move) -- rejects a
 * newParentID that would make the card its own ancestor
 * (atlas.WouldCycle) and one that doesn't exist.
 */
export function MoveCard(id: string, newParentID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(3045746849, id, newParentID);
}

/**
 * MoveNote reparents a note (drag filing into/out of an area frame,
 * goal 0081 A2) -- same containment-existence check CreateNote runs.
 * A note can never contain anything, so no cycle check is needed the
 * way MoveCard's atlas.WouldCycle is.
 */
export function MoveNote(id: string, newParentID: string): $CancellablePromise<atlas$0.Note> {
    return $Call.ByID(82527447, id, newParentID);
}

/**
 * Notes returns every LIVE quick-capture annotation (goal 0081 slice
 * A1) -- its own family, deliberately never mixed into Cards(); goal
 * 0093's tombstone exclusion applies the same way liveCardsLocked does.
 */
export function Notes(): $CancellablePromise<atlas$0.Note[] | null> {
    return $Call.ByID(1683919391);
}

/**
 * ObjectListProjection is CardListProjection's own counterpart for a
 * board object (goal 0179 S2): resolves objectID's own
 * Payload["listID"] through the identical read logic, so a "table"
 * board object renders its projected List through the exact same door
 * a table CARD's own face/page already uses -- no second projection
 * reader.
 */
export function ObjectListProjection(objectID: string): $CancellablePromise<$models.ListProjection> {
    return $Call.ByID(2057801304, objectID);
}

/**
 * ObjectMirrorContent is MirrorContent's own counterpart for a board
 * object (goal 0179/0180): resolves objectID's Payload["mirrorPath"]
 * through the exact same read/classify logic, so an image and an ink
 * stroke -- both file-backed board objects -- render on the canvas
 * through the identical door a promoted card's own overlay preview
 * already uses.
 */
export function ObjectMirrorContent(objectID: string): $CancellablePromise<atlas$0.MirrorContent> {
    return $Call.ByID(3879091471, objectID);
}

/**
 * Objects returns every LIVE board-local canvas object (goal
 * 0179/0180) -- its own family, deliberately never mixed into Cards()
 * or Notes(); goal 0093's tombstone exclusion applies the same way
 * liveCardsLocked/liveNotesLocked do.
 */
export function Objects(): $CancellablePromise<atlas$0.BoardObject[] | null> {
    return $Call.ByID(3025538390);
}

/**
 * OpenCardMirror launches cardID's own MirrorPath with the OS default
 * application for its file type (goal 0081 slice A4's "Open file"
 * card-menu item, macOS `open`) -- distinct from RevealCardMirror,
 * which selects the file in the file manager instead of launching it.
 */
export function OpenCardMirror(cardID: string): $CancellablePromise<void> {
    return $Call.ByID(3356986203, cardID);
}

/**
 * OpenObjectMirrorInDefaultApp launches a file-backed board object's
 * own mirrored file with the OS default application for its file type
 * (goal 0232 S1's "open in owning app" contract, the registry command
 * object.openInDefaultApp) -- the same OS door OpenCardMirror already
 * uses (internal/adapters/osopen, goal 0081 slice A4's own research:
 * Wails3's BrowserManager.OpenFile covers "launch a path", but this
 * package's Reveal has no Wails equivalent, so both verbs share one
 * tested adapter rather than splitting across two).
 * 
 * Unlike OpenCardMirror, this validates the path still exists on disk
 * FIRST: a board object's mirror is more likely to go stale (goal
 * 0194's own live-watch/re-pick machinery exists because these files
 * move/vanish more often than a card's), and asking the OS to launch a
 * path that no longer resolves would surface nothing back to Mill's
 * own error UI at all -- osopen.Open only reports a failure to START
 * the OS opener, never the opener's own async "no such file" result.
 */
export function OpenObjectMirrorInDefaultApp(id: string): $CancellablePromise<void> {
    return $Call.ByID(442184393, id);
}

/**
 * OpenURL opens url in the system's default browser -- the ONE
 * Mill-bound door every external-link click in the frontend routes
 * through (frontend/src/shared/openExternal.ts), so a click always
 * goes through osopen.New()'s own Port selection rather than the
 * adopted runtime's Browser.OpenURL directly (goal 0356 part 2: a test
 * or an e2e-spawned server must never open a real browser tab on the
 * machine running it).
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(2910617595, url);
}

/**
 * PasteToBoard converts understood clipboard content into entities
 * under parentID, starting placement at (x, y). A user's own paste is
 * a direct edit -- ungated, like every direct create.
 */
export function PasteToBoard(text: string, html: string, parentID: string, x: number, y: number): $CancellablePromise<$models.PasteResult> {
    return $Call.ByID(233648772, text, html, parentID, x, y);
}

/**
 * Perspectives returns every perspective across every space -- the
 * frontend/caller scopes by SpaceID (goal 0095's slice-1 read model
 * mirrors Kinds()/LinkKinds()'s own "return everything, caller
 * filters" shape).
 */
export function Perspectives(): $CancellablePromise<atlas$0.Perspective[] | null> {
    return $Call.ByID(1253153793);
}

/**
 * PickBoardFile opens the native file picker with no extension filter
 * -- the creation dock's "From file…" door (goal 0355). The caller
 * lands the chosen path through the SAME routing a dropped file takes,
 * so this only resolves WHICH file, never what it becomes. Returns ""
 * (no error) when the user cancels.
 */
export function PickBoardFile(): $CancellablePromise<string> {
    return $Call.ByID(2422182103);
}

/**
 * PickDiagramFile opens the native diagram-file picker -- the honest-
 * state "Choose file" action's own path resolution step (goal 0194: a
 * typed path string is developer vocabulary, not a user-facing
 * affordance, same rule PickImageFile already follows). Returns "" (no
 * error) when the user cancels.
 */
export function PickDiagramFile(): $CancellablePromise<string> {
    return $Call.ByID(3026340814);
}

/**
 * PickFolder opens the native folder picker -- goal 0067's consent
 * gate: zero filesystem reads happen before this returns a path the
 * user actually chose. startDir optionally pre-fills the dialog's
 * starting location; passing a DetectSyncRoots hit here is
 * presentation only, never itself a read. Returns "" (no error) when
 * the user cancels.
 */
export function PickFolder(startDir: string): $CancellablePromise<string> {
    return $Call.ByID(3623587391, startDir);
}

/**
 * PickImageFile opens the native image-file picker (goal 0206: a typed
 * path string is developer vocabulary, not a user-facing affordance) --
 * filtered to recognized image extensions. Returns "" (no error) when
 * the user cancels.
 */
export function PickImageFile(): $CancellablePromise<string> {
    return $Call.ByID(913238);
}

/**
 * PreviewClipbridgeReply validates a raw clipboard string against the
 * reply contract (schema-first, then per-action requirements) and
 * annotates it with collision state. Malformed input renders inline --
 * this returns a Go error only for internal faults.
 */
export function PreviewClipbridgeReply(raw: string): $CancellablePromise<$models.ClipbridgeReplyPreview> {
    return $Call.ByID(3851574839, raw);
}

/**
 * PromoteBoardObject is the object's one-way lifecycle event (the same
 * promotion ritual PromoteNote runs): it becomes a typed Card in
 * place -- same position, same parent, title and kind supplied by the
 * caller. Whichever Payload key the object's own Kind carries rides
 * onto the matching Card field: mirrorPath -> MirrorPath (image, ink,
 * shape's own file-backed siblings, and diagram) so the promoted card
 * renders through the exact same mirror-unit path a native file drop
 * already used; listID -> ProjectionListID (table) so it keeps
 * projecting the same List. A Kind that carries neither (shape) simply
 * promotes to a plain card -- both assignments below are no-ops for it.
 * checksum is computed BEFORE the lock is taken (fileChecksum does its
 * own I/O) and never blocks promotion on failure, same fail-open
 * posture CreateCardFromFileDrop takes. Atomic under a.mu: the kind is
 * resolved and the card validated BEFORE the object is touched, so a
 * bad kindID leaves the object completely untouched -- no half-
 * promoted state ever exists.
 */
export function PromoteBoardObject(objectID: string, kindID: string, title: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(1142980517, objectID, kindID, title);
}

/**
 * PromoteNote is the note's one-way lifecycle event (the LOCKED
 * design's "promotion ritual"): it becomes a typed Card in place --
 * same position, same parent, title and kind supplied by the caller
 * (the placement-popover form in promote mode), the note's own text
 * carried onto the new card's Note field. Atomic under a.mu: the kind
 * is resolved and the card validated BEFORE the note is touched, so a
 * bad kindID (or any other validation failure) leaves the note
 * completely untouched -- no half-promoted state ever exists.
 */
export function PromoteNote(noteID: string, kindID: string, title: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(881716522, noteID, kindID, title);
}

/**
 * ReadPasteboardFilePaths returns the real absolute paths of any files
 * on the OS pasteboard (a Finder ⌘C) -- the half of a copied-file
 * paste the web Clipboard API structurally can't deliver (it exposes
 * bytes, never paths), so the board's paste door asks the host and
 * routes the answer through the same landing pipeline a drop uses
 * (goal 0255). Fail-closed: no osascript, no file flavor, or any
 * error at all is an empty list -- the paste gesture then falls back
 * to the pasted bytes or a no-op, never an error the user sees.
 */
export function ReadPasteboardFilePaths(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1957268351);
}

/**
 * Redo re-applies the UI actor's last undone mark, forward, through the
 * same doors (ADR-0044 decision 3: "redo is the inverse's inverse,
 * same rule").
 */
export function Redo(): $CancellablePromise<$models.UndoResult> {
    return $Call.ByID(3243984018);
}

/**
 * RefreshMirrorContainer re-syncs cardID -- which must already carry a
 * MirrorPath from a prior import -- against its own source folder on
 * disk. The folder itself having vanished is reported as an error and
 * marks the container MirrorMissing; anything ELSE gone missing
 * underneath it (a file, a nested folder) is marked the same way but
 * never blocks the rest of the refresh from running.
 */
export function RefreshMirrorContainer(cardID: string): $CancellablePromise<$models.FolderImportSummary> {
    return $Call.ByID(1348921533, cardID);
}

/**
 * RemoveFromPerspective removes cardID from perspectiveID, cascaded to
 * every member descendant cardID currently contains (ADR-0041): a
 * member left behind after its own container drops out of a view would
 * render with no visible parent context.
 */
export function RemoveFromPerspective(perspectiveID: string, cardID: string): $CancellablePromise<atlas$0.Perspective> {
    return $Call.ByID(2634584680, perspectiveID, cardID);
}

/**
 * RenamePerspective replaces a perspective's Name/Description in
 * place -- membership/SpaceID/Order move through their own dedicated
 * calls (AddToPerspective/RemoveFromPerspective/ReorderPerspective),
 * same "one concern per mutator" shape UpdateCard vs. MoveCard takes.
 */
export function RenamePerspective(id: string, name: string, description: string): $CancellablePromise<atlas$0.Perspective> {
    return $Call.ByID(994641070, id, name, description);
}

/**
 * RenderNoteMarkdown converts a card note's markdown source to safe
 * HTML (goal 0145) -- the same GFM renderer + raw-HTML-escaping the
 * mirror preview and Docs view already trust.
 */
export function RenderNoteMarkdown(source: string): $CancellablePromise<string> {
    return $Call.ByID(4275701807, source);
}

/**
 * ReorderPerspective assigns Order = index within orderedIDs to every
 * perspective named -- orderedIDs must name EXACTLY the perspectives
 * currently scoped to spaceID, once each (the same "whole ordered set,
 * not a partial move" shape a drag-reorder list naturally produces).
 */
export function ReorderPerspective(spaceID: string, orderedIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(538428937, spaceID, orderedIDs);
}

/**
 * RepickCardMirror points cardID's own MirrorPath at a newly chosen
 * file -- the honest-state "Choose file" action's own apply step, used
 * both after a vanished-file re-pick and to swap a diagram for a
 * different one outright. Re-arms the live filewatch binding and fires
 * MirrorChangedEvent immediately, so the page that just showed "file
 * not found" refetches without waiting on the next external edit.
 */
export function RepickCardMirror(cardID: string, path: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(3901608483, cardID, path);
}

/**
 * RepickObjectMirror is RepickCardMirror's own counterpart for a board
 * object's Payload["mirrorPath"] entry.
 */
export function RepickObjectMirror(objectID: string, path: string): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(3199155054, objectID, path);
}

/**
 * ResolveFileDropRoute decides what a drop/paste of paths means --
 * stats them (never lists a directory's contents; that's ScanFolder's
 * own job once the caller acts on an "import" route) so the frontend
 * never has to guess file-vs-directory itself. paths must be non-empty.
 */
export function ResolveFileDropRoute(paths: string[] | null): $CancellablePromise<$models.FileDropRoute> {
    return $Call.ByID(1104308202, paths);
}

/**
 * RevealCardMirror selects cardID's own MirrorPath in the OS file
 * manager, WITHOUT opening it -- the card menu/overlay's "Reveal in
 * file manager" action (goal 0081 slice A4, macOS `open -R`), only
 * ever offered once a refresh has actually run and set MirrorPath.
 * Distinct from OpenCardMirror below, which launches the file instead
 * of selecting it.
 */
export function RevealCardMirror(cardID: string): $CancellablePromise<void> {
    return $Call.ByID(2489476102, cardID);
}

/**
 * RevealSpaceFolder lazily creates (if needed) and opens spaceID's own
 * mirror folder in the OS file manager, returning its path -- the
 * space toolbar's "Reveal folder" action, and the one operation that
 * turns the folder into a STANDING reference: reveal once, then drag
 * it into any AI assistant that grounds on a folder, permanently.
 */
export function RevealSpaceFolder(spaceID: string): $CancellablePromise<string> {
    return $Call.ByID(560408095, spaceID);
}

/**
 * RunCardAction fires one of the card's ATTACHED or OFFERED actions --
 * membership is validated here so the bound surface can never run an
 * arbitrary workflow against a card it was never attached to. Offered
 * = the workflow declares this card's recognized Integration as its
 * offer target (goal 0126, atlasrecognition.go) -- exactly as
 * deliberate an authorization as attaching, just declared on the
 * workflow's side. The payload/values convention mirrors
 * trigger-atlas-card's fire exactly (cardId/kindId/cardTitle into
 * declared Attributes), with changeType "action".
 */
export function RunCardAction(cardID: string, workflowID: string): $CancellablePromise<void> {
    return $Call.ByID(3407735559, cardID, workflowID);
}

/**
 * SaveImageBytes decodes base64Data (standard encoding) and writes it to
 * a fresh file under the captures directory, returning the file's own
 * path. ext must be one of atlas.IsImageExtension's recognized image
 * extensions (including its leading "."), checked here so a bad paste
 * never reaches the filesystem. Card creation is a deliberately separate
 * step -- the caller passes the returned path straight to
 * CreateCardFromFileDrop, so a pasted image and a natively dropped one
 * resolve their Kind, duplicate check, and card fields through the
 * exact same logic.
 */
export function SaveImageBytes(base64Data: string, ext: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(74333231, base64Data, ext, title);
}

export function SaveMirrorText(content: string, ext: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(2283998067, content, ext, title);
}

/**
 * ScanFolder performs the bounded, heuristic scan goal 0067 describes:
 * depth/count-capped, hidden entries and symlinks skipped
 * (fileread.Scan), each entry classified into a suggestion category by
 * extension (atlas.ClassifyScanExtension) with a humanized suggested
 * title (atlas.HumanizeFilename), and (goal 0088) flagged when its own
 * content checksum matches an already-mirrored card. Read-only against
 * Atlas's own cards (the opportunistic checksum backfill below is the
 * one write this read-only-looking call makes, and it's additive
 * metadata only, never a content change). root must not hold (or be
 * held by) Mill's own data (SetGuardedDataPaths).
 */
export function ScanFolder(root: string): $CancellablePromise<$models.FolderScanResult> {
    return $Call.ByID(130483307, root);
}

/**
 * SetAtlasSession persists the current session state -- a zero state
 * clears the entry (same no-op-avoidance posture SetLens takes). No
 * dataevent: nothing else renders off this, and emitting would
 * refresh the very view mid-navigation.
 */
export function SetAtlasSession(state: $models.AtlasSessionState): $CancellablePromise<void> {
    return $Call.ByID(1784937459, state);
}

/**
 * SetBoardObjectKind re-types an object in place -- same id, payload,
 * position, size, and parent -- so the board's "paste as … instead"
 * offer (ADR-0051 slice 2) can hand a just-pasted link from one
 * claiming plugin's kind to another's without a delete-and-recreate
 * (which would cost the user two undo steps and the object its id).
 * Both kinds share the url-source payload contract (url + title), which
 * is what makes the payload carry over verbatim; the call itself does
 * not police that -- the frontend only ever offers kinds that were
 * claimants for the same paste. Undoable as one step.
 */
export function SetBoardObjectKind(id: string, kind: string): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(3909090495, id, kind);
}

/**
 * SetBoardObjectPayload merges patch into a board object's Payload --
 * the content-plane write door for a payload-carrying object whose
 * data changes after placement (docs/goals/0249: a plugin object's own
 * fields, written host-mediated so plugin code never touches a
 * binding). A key with an empty value deletes that key; every other
 * key overwrites. mirrorPath changes re-arm the file watch the same
 * way creation does.
 */
export function SetBoardObjectPayload(id: string, patch: { [_ in string]?: string } | null): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(1717906545, id, patch);
}

/**
 * SetBoardObjectPosition updates a board object's placement within its
 * parent's canvas -- the same drag-persistence call cards/notes go
 * through via SetPosition/SetNotePosition.
 */
export function SetBoardObjectPosition(id: string, pos: atlas$0.Position): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(705679206, id, pos);
}

/**
 * SetBoardObjectRotation persists a shape's rotation angle in degrees
 * (goal 0214) -- same scoped-setter shape as SetBoardObjectPosition/
 * SetBoardObjectSize, writing into Payload rather than a dedicated
 * struct field since rotation lives at the same tier as a shape's
 * other style keys (fill/stroke/strokeWidth, shapeTool.ts's own "style
 * lives in Payload" contract). Payload is copied before mutation so a
 * failed persist can roll back to `previous` without also reverting
 * the caller's own map (maps are reference types; mutating the shared
 * map in place would corrupt the rollback). Kind-agnostic like every
 * other setter here -- the frontend decides which Kinds ever call it.
 */
export function SetBoardObjectRotation(id: string, degrees: number): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(1961954755, id, degrees);
}

/**
 * SetBoardObjectSize persists a user-driven resize -- nil until the
 * object's own natural/intrinsic render size is first overridden (S2+;
 * S1 never calls this, but the door exists so a future resize handle
 * costs a frontend call, not a schema change). The floor matches the
 * frontend resize handle's own minWidth/minHeight (AtlasBoardObjectNode's
 * NodeResizer, goal 0199 part B) -- a resize below it is refused here
 * too, never persisted as a degenerate box.
 */
export function SetBoardObjectSize(id: string, size: atlas$0.Dimensions): $CancellablePromise<atlas$0.BoardObject> {
    return $Call.ByID(1403039216, id, size);
}

/**
 * SetCardActions replaces a card's attached actions (goal 0084) --
 * deduplicated, empties dropped; order is the page's display order.
 */
export function SetCardActions(id: string, workflowIDs: string[] | null): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(2051564971, id, workflowIDs);
}

/**
 * SetCardProjectionDensity persists the projection's render mode
 * ("", "grid", "pills") -- validated against the closed set so a bad
 * wire value can't persist.
 */
export function SetCardProjectionDensity(cardID: string, density: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(3542799747, cardID, density);
}

/**
 * SetCardSize persists a card's user-chosen board footprint (the
 * resize handle's commit). Bounds guard against a degenerate drag:
 * anything under 120x80 canvas units can't render a usable face.
 */
export function SetCardSize(cardID: string, w: number, h: number): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(4084337105, cardID, w, h);
}

/**
 * SetLens persists the per-space lens for containerID: which Kind IDs
 * stay hidden when viewing that container's children (ADR-0038's
 * density-is-a-lens-choice principle), and the depth/peek toggle (goal
 * 0061 slice C -- absorbed here from its previous browser-localStorage
 * home). A setting with nothing real in it (no hidden kinds, peek off)
 * clears the container's entry rather than storing a no-op one --
 * keeps the persisted map from growing entries with no real content.
 */
export function SetLens(containerID: string, hiddenKindIDs: string[] | null, peek: boolean): $CancellablePromise<void> {
    return $Call.ByID(1752890006, containerID, hiddenKindIDs, peek);
}

/**
 * SetLinkKind reassigns an existing link to a different LinkKind --
 * the edge menu's own "Change link kind" action (goal 0081 slice A4),
 * distinct from UpdateLink above (which only ever touches Label):
 * re-typing a drawn link is a different edit than re-wording it, so it
 * gets its own referential-existence check against the new kind.
 */
export function SetLinkKind(id: string, linkKindID: string): $CancellablePromise<atlas$0.Link> {
    return $Call.ByID(3745757492, id, linkKindID);
}

/**
 * SetNotePosition updates a note's placement within its parent's canvas
 * -- the same drag-persistence call cards go through via SetPosition.
 */
export function SetNotePosition(id: string, pos: atlas$0.Position): $CancellablePromise<atlas$0.Note> {
    return $Call.ByID(1696067681, id, pos);
}

/**
 * SetNoteSize persists a note's user-chosen board footprint -- the
 * resize handle's commit, same shape as SetCardSize. Bounds guard
 * against a degenerate drag: a note's own default face (STICKY_WIDTH/
 * STICKY_HEIGHT) is smaller than a card's, so the floor is lower too.
 */
export function SetNoteSize(id: string, size: atlas$0.Dimensions): $CancellablePromise<atlas$0.Note> {
    return $Call.ByID(4163810295, id, size);
}

/**
 * SetPosition updates a card's placement within its parent's canvas.
 * A nil position is accepted (clearing it, e.g. after a move to a
 * shelves-mode parent) -- no validation ties Position to the parent's
 * current ViewMode, since a position saved while canvas-mode simply
 * goes unread while shelves-mode is active, exactly as
 * docs/goals/0061 describes it ("only meaningful in canvas-mode
 * containers").
 */
export function SetPosition(id: string, position: atlas$0.Position | null): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(7306901, id, position);
}

/**
 * SetViewMode sets how id's OWN children render (atlas.Card.ViewMode's
 * container-config role) -- id need not currently have any children.
 */
export function SetViewMode(id: string, mode: atlas$0.ViewMode): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(1276916204, id, mode);
}

/**
 * SpaceBundleContext concatenates spaceID's own children's context
 * blocks, each separated by a divider line -- the space toolbar's
 * "Bundle as context" action, one paste covering everything currently
 * in the viewed space (goal 0063). spaceID == "" names the true root
 * (every card whose ParentID is "").
 */
export function SpaceBundleContext(spaceID: string, withAttachments: boolean): $CancellablePromise<string> {
    return $Call.ByID(1197881783, spaceID, withAttachments);
}

/**
 * SpaceContextEnvelope renders spaceID's own children as one OUT
 * envelope (goal 0101): the companion panel's system context on every
 * turn, scoped to whatever the user is currently looking at rather
 * than the whole map. Same child-listing loop as SpaceBundleContext's
 * plain-text sibling (spaceID == "" names the true root), each child
 * converted through the identical per-card path CardContextEnvelope
 * uses for a single card.
 */
export function SpaceContextEnvelope(spaceID: string): $CancellablePromise<string> {
    return $Call.ByID(1944161179, spaceID);
}

/**
 * SpaceLinksList lists every Source URL set on spaceID's own children,
 * one per line, in a.cards' own stored order -- the space toolbar's
 * "Copy links" action.
 */
export function SpaceLinksList(spaceID: string): $CancellablePromise<string> {
    return $Call.ByID(979138081, spaceID);
}

/**
 * TableProjectionExport serializes cardID's projected List into format
 * ("csv", "tsv", "markdown", or "xlsx") and returns it ready to
 * download. An unresolvable card/list, an unrecognized format, or a
 * serialization error all fail closed with an actionable message --
 * never a silent empty download.
 */
export function TableProjectionExport(cardID: string, format: string): $CancellablePromise<$models.TableProjectionExportResult> {
    return $Call.ByID(161507377, cardID, format);
}

/**
 * Undo pops the UI actor's last mark and applies every entry's inverse,
 * through the same mutation doors that made the original changes
 * (ADR-0044 decision 3) -- never a state rollback. Entries within a
 * mark apply in REVERSE recording order (last change undone first),
 * mirroring how a multi-step gesture must unwind. The whole mark then
 * moves onto the redo stack UNCHANGED, so Redo() can replay it forward.
 */
export function Undo(): $CancellablePromise<$models.UndoResult> {
    return $Call.ByID(1977819576);
}

/**
 * UndoDelete reverses one or more DeleteCard/DeleteNote/
 * DeleteBoardObject calls: clears DeletedAt on exactly the ids named (a
 * no-op for any id that's no longer tombstoned, e.g. already purged)
 * and clears a built-in card's or board object's seed tombstone too, so
 * top-up seeding can reach it again. cardIDs/noteIDs/objectIDs are the
 * exact TombstoneResult(s) the original delete call(s) returned.
 */
export function UndoDelete(cardIDs: string[] | null, noteIDs: string[] | null, objectIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4101274755, cardIDs, noteIDs, objectIDs);
}

export function UndoState(): $CancellablePromise<$models.UndoState> {
    return $Call.ByID(3693129693);
}

export function UpdateCard(id: string, title: string, note: string, fields: { [_ in string]?: string } | null, source: string, mirrorPath: string, refreshWorkflowID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(1443506165, id, title, note, fields, source, mirrorPath, refreshWorkflowID);
}

/**
 * UpdateKind enforces ADR-0040's field-evolution grammar on Fields --
 * the same chokepoint configuresvc.UpdateDecision/UpdateList already
 * apply to Outputs/Columns (typedfield.ValidateFieldEvolution's own
 * doc comment has the full rule). newFieldTombstones names any Key+
 * Type this call is deleting from Fields right now -- the explicit,
 * UI-declared half of the evolution check.
 */
export function UpdateKind(id: string, label: string, description: string, icon: string, fields: typedfield$0.Field[] | null, newFieldTombstones: typedfield$0.FieldTombstone[] | null): $CancellablePromise<atlas$0.Kind> {
    return $Call.ByID(3208528841, id, label, description, icon, fields, newFieldTombstones);
}

export function UpdateLink(id: string, label: string): $CancellablePromise<atlas$0.Link> {
    return $Call.ByID(81165703, id, label);
}

export function UpdateLinkKind(id: string, label: string, description: string): $CancellablePromise<atlas$0.LinkKind> {
    return $Call.ByID(4253754605, id, label, description);
}

/**
 * UpdateNoteText replaces a Note's own text in place.
 */
export function UpdateNoteText(id: string, text: string): $CancellablePromise<atlas$0.Note> {
    return $Call.ByID(2597186212, id, text);
}

/**
 * UpdateNow runs cardID's RefreshWorkflowID through workflowRunner and
 * stamps ReceiptRunID as soon as a run id exists -- the "on run start"
 * half of ADR-0038 decision 4's stamping rule. When workflowRunner
 * ALSO already knows the run succeeded (the common, non-approval-gated
 * case -- RunWorkflow blocks until completion, so this is true by the
 * time the call returns), LastSyncedAt is stamped right here too,
 * deliberately NOT left to NotifyRunCompleted alone: that hook fires
 * from INSIDE the same blocking RunWorkflow call, before ReceiptRunID
 * is set on this card, so its own id-match would find nothing for a
 * synchronous run -- a real ordering bug, not a hypothetical one, found
 * while writing this. NotifyRunCompleted (below) remains the only path
 * for a run that PARKS on guardrail approval and resolves long after
 * this call has already returned, since by then ReceiptRunID has been
 * set and the match succeeds.
 */
export function UpdateNow(cardID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(2019874317, cardID);
}

/**
 * WriteObjectMirror overwrites objectID's own mirrored file with
 * content -- the embedded editor engine's save/autosave path (goal
 * 0237 S1) and the sheet quick-edit's csv commit (goal 0239 S2), both
 * whole-file text writes. The file is the SAME mirror armMirrorWatch
 * already watches, so this deliberately does not emit
 * MirrorChangedEvent itself: the write lands on disk, the existing
 * fsnotify watch (goal 0194) picks it up on its own debounce, and the
 * board preview refreshes through that one path -- never a second,
 * race-prone signal alongside the watch's own.
 */
export function WriteObjectMirror(objectID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3607737869, objectID, content);
}
