// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AtlasService holds Atlas's full in-memory state behind one mutex,
 * same shape as GuardrailService/CompositionService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as atlas$0 from "../../domain/atlas/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../../domain/typedfield/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CardContextBlock renders cardID's fields/note/links as one stable,
 * paste-ready text block (goal 0063's copy-as-context) -- the Card
 * overlay/chip's "Copy as context" action copies exactly this string.
 */
export function CardContextBlock(cardID: string, withAttachments: boolean): $CancellablePromise<string> {
    return $Call.ByID(4150547692, cardID, withAttachments);
}

export function Cards(): $CancellablePromise<atlas$0.Card[] | null> {
    return $Call.ByID(4038798409);
}

/**
 * CardsByKind returns every card of kindID -- the apply-atlas-card-find
 * step's own read (goal 0066), via composition.SetAtlasCardFinder.
 */
export function CardsByKind(kindID: string): $CancellablePromise<atlas$0.Card[] | null> {
    return $Call.ByID(1757324970, kindID);
}

/**
 * CreateCard makes a new Card of kindID, optionally inside parentID
 * ("" for root-level). A non-empty parentID must name an existing
 * card; a fresh card can never itself be a cycle (it has no children
 * yet), so no cycle check is needed here -- MoveCard is where
 * reparenting an EXISTING card (which may have its own descendants)
 * needs one.
 */
export function CreateCard(kindID: string, title: string, note: string, fields: { [_ in string]?: string } | null, parentID: string, position: atlas$0.Position | null, viewMode: atlas$0.ViewMode, source: string, mirrorPath: string, refreshWorkflowID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(3093996908, kindID, title, note, fields, parentID, position, viewMode, source, mirrorPath, refreshWorkflowID);
}

export function CreateKind(label: string, description: string, icon: string, fields: typedfield$0.Field[] | null): $CancellablePromise<atlas$0.Kind> {
    return $Call.ByID(3663898672, label, description, icon, fields);
}

export function CreateLink(fromCardID: string, toCardID: string, linkKindID: string, label: string): $CancellablePromise<atlas$0.Link> {
    return $Call.ByID(3449865750, fromCardID, toCardID, linkKindID, label);
}

export function CreateLinkKind(label: string, description: string): $CancellablePromise<atlas$0.LinkKind> {
    return $Call.ByID(2065966488, label, description);
}

/**
 * DeleteCard removes a card, blocked while it still has children --
 * no orphaning, explicit per docs/goals/0061 (goal 0046 will refine
 * this further, not duplicated here). Deleting a card removes every
 * link touching it.
 */
export function DeleteCard(id: string): $CancellablePromise<void> {
    return $Call.ByID(3764094639, id);
}

/**
 * DeleteKind removes a Kind, blocked while any Card still references
 * it -- no orphaning (docs/goals/0061's Deletion semantics; goal 0046
 * will refine reference handling further, not duplicated here).
 */
export function DeleteKind(id: string): $CancellablePromise<void> {
    return $Call.ByID(694706355, id);
}

export function DeleteLink(id: string): $CancellablePromise<void> {
    return $Call.ByID(1590515097, id);
}

/**
 * DeleteLinkKind removes a LinkKind, blocked while any Link still
 * references it -- same no-orphaning rule as DeleteKind.
 */
export function DeleteLinkKind(id: string): $CancellablePromise<void> {
    return $Call.ByID(1735554023, id);
}

/**
 * ExportAtlas serializes the whole Atlas graph as an indented, portable
 * JSON string -- share it, commit it to git, or import it into another
 * Mill instance. Read-only: never mutates a's state. Deterministic by
 * construction (every field is already-stored data in stable slice
 * order): exporting twice with no intervening change produces
 * byte-identical bytes, the same guarantee every other exported* shape
 * in this codebase carries.
 */
export function ExportAtlas(): $CancellablePromise<string> {
    return $Call.ByID(1261911391);
}

/**
 * ImportAtlas applies ADR-0036 decision 3's uniform import rule to
 * EVERY entity inside jsonData's bundle independently: id absent ->
 * create fresh; id present and known locally -> update in place; id
 * present and unknown locally -> create preserving that id. Order is
 * Kinds/LinkKinds first (Cards reference them by id), then Cards in two
 * passes -- pass one creates/updates every card's own content with no
 * containment yet (so a bundle can list a child before its parent),
 * pass two applies ParentID/Position now that every bundled card exists
 * locally, through the existing MoveCard/SetPosition chokepoints (their
 * own cycle-rejection applies unchanged). A card whose bundle entry
 * omits ParentID is left wherever it already is when updating an
 * EXISTING card -- omitempty can't distinguish "explicitly root" from
 * "field not declared" (the same nil-vs-empty ambiguity
 * UpdateWorkflowFromExport's own doc comment already documents for
 * Attributes/Notes), so import only ever ADDS/changes containment,
 * never implicitly clears it. Links import last, once every card and
 * LinkKind they reference exists.
 */
export function ImportAtlas(jsonData: string): $CancellablePromise<$models.AtlasImportSummary> {
    return $Call.ByID(1577571942, jsonData);
}

export function Kinds(): $CancellablePromise<atlas$0.Kind[] | null> {
    return $Call.ByID(3099018285);
}

/**
 * Lens returns the persisted lens setting for containerID -- the zero
 * value (no hidden kinds, peek off) when none is set.
 */
export function Lens(containerID: string): $CancellablePromise<atlas$0.LensSetting> {
    return $Call.ByID(1926175606, containerID);
}

export function LinkKinds(): $CancellablePromise<atlas$0.LinkKind[] | null> {
    return $Call.ByID(1481666021);
}

export function Links(): $CancellablePromise<atlas$0.Link[] | null> {
    return $Call.ByID(1082434947);
}

/**
 * MoveCard reparents a card (sibling-vs-child move, ADR-0038's
 * create-time framing extended to a later move) -- rejects a
 * newParentID that would make the card its own ancestor
 * (atlas.WouldCycle) and one that doesn't exist.
 */
export function MoveCard(id: string, newParentID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(3045746849, id, newParentID);
}

/**
 * RevealCardMirror opens cardID's own MirrorPath in the OS file
 * manager -- the card overlay/chip's "Reveal file" action, only ever
 * offered once a refresh has actually run and set MirrorPath.
 */
export function RevealCardMirror(cardID: string): $CancellablePromise<void> {
    return $Call.ByID(2489476102, cardID);
}

/**
 * RevealSpaceFolder lazily creates (if needed) and opens spaceID's own
 * mirror folder in the OS file manager, returning its path -- the
 * space toolbar's "Reveal folder" action, and the one operation that
 * turns the folder into a STANDING reference: reveal once, then drag
 * it into any AI assistant that grounds on a folder, permanently.
 */
export function RevealSpaceFolder(spaceID: string): $CancellablePromise<string> {
    return $Call.ByID(560408095, spaceID);
}

/**
 * SetLens persists the per-space lens for containerID: which Kind IDs
 * stay hidden when viewing that container's children (ADR-0038's
 * density-is-a-lens-choice principle), and the depth/peek toggle (goal
 * 0061 slice C -- absorbed here from its previous browser-localStorage
 * home). A setting with nothing real in it (no hidden kinds, peek off)
 * clears the container's entry rather than storing a no-op one --
 * keeps the persisted map from growing entries with no real content.
 */
export function SetLens(containerID: string, hiddenKindIDs: string[] | null, peek: boolean): $CancellablePromise<void> {
    return $Call.ByID(1752890006, containerID, hiddenKindIDs, peek);
}

/**
 * SetPosition updates a card's placement within its parent's canvas.
 * A nil position is accepted (clearing it, e.g. after a move to a
 * shelves-mode parent) -- no validation ties Position to the parent's
 * current ViewMode, since a position saved while canvas-mode simply
 * goes unread while shelves-mode is active, exactly as
 * docs/goals/0061 describes it ("only meaningful in canvas-mode
 * containers").
 */
export function SetPosition(id: string, position: atlas$0.Position | null): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(7306901, id, position);
}

/**
 * SetViewMode sets how id's OWN children render (atlas.Card.ViewMode's
 * container-config role) -- id need not currently have any children.
 */
export function SetViewMode(id: string, mode: atlas$0.ViewMode): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(1276916204, id, mode);
}

/**
 * SpaceBundleContext concatenates spaceID's own children's context
 * blocks, each separated by a divider line -- the space toolbar's
 * "Bundle as context" action, one paste covering everything currently
 * in the viewed space (goal 0063). spaceID == "" names the true root
 * (every card whose ParentID is "").
 */
export function SpaceBundleContext(spaceID: string, withAttachments: boolean): $CancellablePromise<string> {
    return $Call.ByID(1197881783, spaceID, withAttachments);
}

/**
 * SpaceLinksList lists every Source URL set on spaceID's own children,
 * one per line, in a.cards' own stored order -- the space toolbar's
 * "Copy links" action.
 */
export function SpaceLinksList(spaceID: string): $CancellablePromise<string> {
    return $Call.ByID(979138081, spaceID);
}

/**
 * UpdateCard replaces a Card's editable content in place -- ParentID/
 * Position move through MoveCard/SetPosition instead, so a plain
 * content edit never has to re-run the cycle check. sourceRunID is
 * always "" here (a manual Atlas UI edit); MergeCardFields is the
 * run-driven counterpart apply-atlas-card-update uses.
 */
export function UpdateCard(id: string, title: string, note: string, fields: { [_ in string]?: string } | null, source: string, mirrorPath: string, refreshWorkflowID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(1443506165, id, title, note, fields, source, mirrorPath, refreshWorkflowID);
}

/**
 * UpdateKind enforces ADR-0040's field-evolution grammar on Fields --
 * the same chokepoint configuresvc.UpdateDecision/UpdateList already
 * apply to Outputs/Columns (typedfield.ValidateFieldEvolution's own
 * doc comment has the full rule). newFieldTombstones names any Key+
 * Type this call is deleting from Fields right now -- the explicit,
 * UI-declared half of the evolution check.
 */
export function UpdateKind(id: string, label: string, description: string, icon: string, fields: typedfield$0.Field[] | null, newFieldTombstones: typedfield$0.FieldTombstone[] | null): $CancellablePromise<atlas$0.Kind> {
    return $Call.ByID(3208528841, id, label, description, icon, fields, newFieldTombstones);
}

export function UpdateLink(id: string, label: string): $CancellablePromise<atlas$0.Link> {
    return $Call.ByID(81165703, id, label);
}

export function UpdateLinkKind(id: string, label: string, description: string): $CancellablePromise<atlas$0.LinkKind> {
    return $Call.ByID(4253754605, id, label, description);
}

/**
 * UpdateNow runs cardID's RefreshWorkflowID through workflowRunner and
 * stamps ReceiptRunID as soon as a run id exists -- the "on run start"
 * half of ADR-0038 decision 4's stamping rule. When workflowRunner
 * ALSO already knows the run succeeded (the common, non-approval-gated
 * case -- RunWorkflow blocks until completion, so this is true by the
 * time the call returns), LastSyncedAt is stamped right here too,
 * deliberately NOT left to NotifyRunCompleted alone: that hook fires
 * from INSIDE the same blocking RunWorkflow call, before ReceiptRunID
 * is set on this card, so its own id-match would find nothing for a
 * synchronous run -- a real ordering bug, not a hypothetical one, found
 * while writing this. NotifyRunCompleted (below) remains the only path
 * for a run that PARKS on guardrail approval and resolves long after
 * this call has already returned, since by then ReceiptRunID has been
 * set and the match succeeds.
 */
export function UpdateNow(cardID: string): $CancellablePromise<atlas$0.Card> {
    return $Call.ByID(2019874317, cardID);
}
