// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AtlasImportSummary counts what ImportAtlas did, per family -- the
 * frontend's own pre-import preview computes its "will update" warning
 * client-side (existing entity ids, same shape useImportConfirm already
 * reads for every other import surface), so this return value is purely
 * informational for a post-import confirmation, not load-bearing for
 * the uniform-semantics preview itself.
 */
export interface AtlasImportSummary {
    "KindsCreated": number;
    "KindsUpdated": number;
    "LinkKindsCreated": number;
    "LinkKindsUpdated": number;
    "CardsCreated": number;
    "CardsUpdated": number;
    "LinksCreated": number;
    "LinksUpdated": number;
}
