// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPAuditService wraps the storage adapter and provides the two audit
 * middleware constructors plus the bound read API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListMCPCalls is the bound read API Activity's "MCP calls" section
 * calls -- newest first, filterable by direction/tool, limit/offset
 * paged (the design contract's own words).
 */
export function ListMCPCalls(req: $models.ListMCPCallsRequest): $CancellablePromise<$models.ListMCPCallsResponse> {
    return $Call.ByID(624143641, req);
}
