// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Kind is the vocabulary of paired-credential SHAPES a Ref can be --
 * distinct from remoteauthsvc's own storage-level kind strings (""/
 * "browser"/"hook"), which are an implementation detail the
 * remoteauthsvc adapter translates away from.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindPhone = "phone",
    KindBrowser = "browser",
    KindWebhookToken = "webhook-token",
};

/**
 * Ref is one paired credential's read model for composition: enough to
 * label it in a picker and decide whether it can receive a given
 * event. Never carries the credential itself (remoteauthsvc's own
 * DeviceInfo already excludes that) -- this is a directory entry, not
 * an auth artifact.
 */
export interface Ref {
    "id": string;
    "label": string;
    "kind": Kind;
    "lastSeenAt": string;

    /**
     * Accepts names the event kinds this device can receive (Home
     * Assistant's per-device capability discovery, docs/goals/0372
     * decision 3 -- v1 vocabulary: only "notification" is ever actually
     * delivered). A ref whose Accepts doesn't intersect a field's own
     * Needs is never offered by that field's picker. Empty means this
     * device accepts nothing composition can address yet (a webhook
     * token is an inbound-only credential).
     */
    "accepts": string[] | null;
}
