// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandBlockPreview is PreviewCommandBlock's full return shape.
 */
export interface CommandBlockPreview {
    "steps": CommandBlockPreviewStep[] | null;
    "shell": string;
    "dir": string;

    /**
     * GuardrailVerdict is "allow" | "ask" | "deny" -- one verdict for
     * the whole block, since S1's guardrail plane evaluates per NODE,
     * not per parsed line (every step shares the seed's own single
     * process-shell-command node). A future allow/deny pattern-list
     * slice (goal 0240 S3) is what would ever make per-step verdicts
     * differ; nothing in this preview's own shape needs to change for
     * that to land.
     */
    "guardrailVerdict": string;

    /**
     * WorkflowID/NodeID name which real seeded workflow/node the
     * frontend will call RunWorkflowWithPayload/ResolveApproval
     * against -- never hardcoded client-side, so a future seed-ID
     * change can't silently desync the two sides.
     */
    "workflowID": string;
    "nodeID": string;

    /**
     * SecretRequirements is every env-var-style secret placeholder this
     * block references (goal 0240 S2), each with its resolution source --
     * the Confirm screen's own design contract ("secrets it will need
     * with their resolution source: vault name / env var / you'll type
     * it"). Empty for a block that references none.
     */
    "secretRequirements": SecretRequirementView[] | null;
}

/**
 * CommandBlockPreviewStep is one parsed step, in the exact shape the
 * Confirm screen renders -- Join mirrors composition.CommandJoin's own
 * string values ("" | "newline" | "and") so the frontend needs no
 * second enum.
 */
export interface CommandBlockPreviewStep {
    "index": number;
    "text": string;
    "join": string;
    "looksLikeSecretPlaceholder": boolean;
}

/**
 * SecretRequirementView is composition.SecretRequirement with JSON tags
 * added -- same "adapter/service type stays free of a frontend-JSON
 * concern living in the domain type" split every other *View/*Record
 * shape in this codebase already follows (e.g. secretsvc.
 * SecretAccessRecord).
 */
export interface SecretRequirementView {
    "varName": string;
    "source": string;
    "vaultLabel"?: string;
}
