// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandBlockPreview is PreviewCommandBlock's full return shape.
 */
export interface CommandBlockPreview {
    "steps": CommandBlockPreviewStep[] | null;
    "shell": string;
    "dir": string;

    /**
     * EnvironmentLabel names the Configure-authored execution
     * environment the seeded shell step is configured to run inside
     * (docs/goals/0240 S4) -- empty in the default real-login-shell
     * posture, where Shell/Dir above already tell the whole story.
     */
    "environmentLabel": string;

    /**
     * GuardrailVerdict is "allow" | "ask" | "deny" -- the block-level
     * gate decision (goal 0240 S3): the MOST RESTRICTIVE of every step's
     * own Verdict below, since the block still checkpoints/pauses as ONE
     * DBOS step (composition/executeshellcommand.go's own one-step-per-
     * node design). Each CommandBlockPreviewStep now carries its OWN
     * verdict too -- this field is what actually decides whether Run
     * pauses for approval, the per-step ones are display only.
     */
    "guardrailVerdict": string;

    /**
     * WorkflowID/NodeID name which real seeded workflow/node the
     * frontend will call RunWorkflowWithPayload/ResolveApproval
     * against -- never hardcoded client-side, so a future seed-ID
     * change can't silently desync the two sides.
     */
    "workflowID": string;
    "nodeID": string;

    /**
     * SecretRequirements is every env-var-style secret placeholder this
     * block references (goal 0240 S2), each with its resolution source --
     * the Confirm screen's own design contract ("secrets it will need
     * with their resolution source: vault name / env var / you'll type
     * it"). Empty for a block that references none.
     */
    "secretRequirements": SecretRequirementView[] | null;
}

/**
 * CommandBlockPreviewStep is one parsed step, in the exact shape the
 * Confirm screen renders -- Join mirrors composition.CommandJoin's own
 * string values ("" | "newline" | "and") so the frontend needs no
 * second enum.
 */
export interface CommandBlockPreviewStep {
    "index": number;
    "text": string;
    "join": string;
    "looksLikeSecretPlaceholder": boolean;

    /**
     * Verdict/RuleLabel (goal 0240 S3) are this ONE step's own guardrail
     * verdict -- "allow" | "ask" | "deny", matching CommandBlockPreview's
     * own GuardrailVerdict values. RuleLabel is empty when the
     * effect-class default decided (no allow/deny-list pattern matched);
     * the Confirm screen only renders a per-step badge when it's
     * non-empty, so an unlisted step stays exactly as quiet as it was
     * before this slice.
     */
    "verdict": string;
    "ruleLabel"?: string;
}

/**
 * SecretRequirementView is composition.SecretRequirement with JSON tags
 * added -- same "adapter/service type stays free of a frontend-JSON
 * concern living in the domain type" split every other *View/*Record
 * shape in this codebase already follows (e.g. secretsvc.
 * SecretAccessRecord).
 */
export interface SecretRequirementView {
    "varName": string;
    "source": string;
    "vaultLabel"?: string;
}
