package docsgen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// commandDeclaration mirrors one entry of
// frontend/src/shared/commandsDeclaration.json -- the command registry's
// own generation source (goal 0231), the same tfplugindocs shape
// docsgen_nouns.go already established for the noun declaration table.
// Unlike that JSON (one entry per TYPE FIELD, checked with a `satisfies`
// type assertion), this JSON is one entry per live COMMAND INSTANCE --
// commandsDeclaration.test.ts is the other half of the freshness chain,
// asserting this file's content equals the real COMMANDS array (across
// shared/commands.ts and every satellite file it spreads in), sorted the
// same way (by id) this file commits it.
type commandDeclaration struct {
	ID      string   `json:"id"`
	Label   string   `json:"label"`
	Binding *string  `json:"binding"`
	Surface []string `json:"surface"`
	Enabled bool     `json:"enabled"`
	// The target kind a command requires (goal 0343): a command with
	// one never runs without a row/selection to act on, so its
	// enablement column says what it needs rather than claiming the
	// command is always available.
	Needs string `json:"needs"`
}

// Markers bounding the one generated region inside the otherwise
// hand-authored userdocs/reference/commands.md -- same shape as
// docsgen_nouns.go's NounFieldTableBeginMarker/EndMarker: only the
// region between these two lines is regenerated by `go generate
// ./internal/docsgen` and diff-checked by
// TestCommandsPage_TableMatchesCommitted.
const (
	CommandTableBeginMarker = "<!-- BEGIN GENERATED: command registry (source: frontend/src/shared/commandsDeclaration.json) -->"
	CommandTableEndMarker   = "<!-- END GENERATED -->"
)

// GenerateCommandTable renders every registered command as a markdown
// table, read from the committed JSON at
// <frontendSharedDir>/commandsDeclaration.json, sorted by id (matching
// the committed file's own sort order so a regeneration never reorders
// rows the JSON itself didn't move).
func GenerateCommandTable(frontendSharedDir string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(frontendSharedDir, "commandsDeclaration.json")) // #nosec G304 -- caller-controlled fixed path, never external input
	if err != nil {
		return "", fmt.Errorf("read commandsDeclaration.json: %w", err)
	}
	var commands []commandDeclaration
	if err := json.Unmarshal(raw, &commands); err != nil {
		return "", fmt.Errorf("parse commandsDeclaration.json: %w", err)
	}
	sort.Slice(commands, func(i, j int) bool { return commands[i].ID < commands[j].ID })
	var b strings.Builder
	b.WriteString("| ID | Label | Default binding | Surface | Enablement |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, c := range commands {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n",
			c.ID, c.Label, describeBinding(c.Binding), describeSurface(c.Surface), describeEnablement(c.Enabled, c.Needs))
	}
	return b.String(), nil
}

func describeBinding(binding *string) string {
	if binding == nil {
		return "—"
	}
	return fmt.Sprintf("`%s`", *binding)
}

func describeSurface(surface []string) string {
	if len(surface) == 0 {
		return "Global"
	}
	return strings.Join(surface, ", ")
}

// The noun a targeted command needs, in the reader's vocabulary --
// never the context kind's own identifier.
var targetNouns = map[string]string{
	"workflow": "workflow",
	"run":      "run",
	"entry":    "clipboard entry",
	"card":     "card",
	"entity":   "entity",
	"listGrid": "table rows",
	"jsonNode": "tree row",
	"tab":      "tab",
}

// The kinds whole "selected X" phrasing would garble ("the selected
// selection"), each given its own full sentence instead.
var targetPhrases = map[string]string{
	"selection":     "Acts on the board's current selection",
	"canvasElement": "Acts on the item you clicked",
}

func describeEnablement(enabled bool, needs string) string {
	if needs != "" {
		if phrase, ok := targetPhrases[needs]; ok {
			return phrase
		}
		noun, ok := targetNouns[needs]
		if !ok {
			noun = needs
		}
		return fmt.Sprintf("Acts on the selected %s", noun)
	}
	if enabled {
		return "Conditional — available only in a matching state"
	}
	return "Always available"
}
