package docsgen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// declarationField mirrors one entry of
// frontend/src/atlas/atlasNounDeclarationFields.json -- the noun
// registry contract table's own source data (goal 0211). Go has no
// TypeScript parser, so extracting the table straight from
// AtlasToolShape's own .ts declaration was disproportionate; this JSON
// is the generation source instead, and
// atlasNounDeclarationFields.test.ts is the other half of the
// freshness chain, `satisfies`-checking a literal field-key list
// against the real type at TS compile time and comparing this JSON's
// own field set against that list at test time. Neither half alone
// would catch drift on its own language's side.
type declarationField struct {
	Field       string `json:"field"`
	LegalValues string `json:"legalValues"`
	Meaning     string `json:"meaning"`
}

// Markers bounding the one generated region inside the otherwise
// hand-authored userdocs/reference/extending-the-canvas.md -- naming
// the exact source keeps the page honest about what freshness is (and
// is not) enforced: only the region between these two lines is
// regenerated by `go generate ./internal/docsgen` and diff-checked by
// TestExtendingCanvasPage_NounFieldTableMatchesCommitted; the prose
// around it carries no such promise.
const (
	NounFieldTableBeginMarker = "<!-- BEGIN GENERATED: noun declaration fields (source: frontend/src/atlas/atlasNounDeclarationFields.json) -->"
	NounFieldTableEndMarker   = "<!-- END GENERATED -->"
)

// GenerateNounFieldTable renders every AtlasToolShape declaration
// field as a markdown table, read from the committed JSON at
// <frontendAtlasDir>/atlasNounDeclarationFields.json. `commit` is
// skipped -- it is the one AtlasToolShape member that is runtime code,
// not inert declaration, and the page's "How it loads" section
// documents it separately under the declaration-vs-code split.
func GenerateNounFieldTable(frontendAtlasDir string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(frontendAtlasDir, "atlasNounDeclarationFields.json")) // #nosec G304 -- caller-controlled fixed path, never external input
	if err != nil {
		return "", fmt.Errorf("read atlasNounDeclarationFields.json: %w", err)
	}
	var fields []declarationField
	if err := json.Unmarshal(raw, &fields); err != nil {
		return "", fmt.Errorf("parse atlasNounDeclarationFields.json: %w", err)
	}
	var b strings.Builder
	b.WriteString("| Field | Legal values | Meaning |\n")
	b.WriteString("|---|---|---|\n")
	for _, f := range fields {
		if f.Field == "commit" {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", f.Field, f.LegalValues, f.Meaning)
	}
	return b.String(), nil
}

// ReplaceMarkedRegion swaps the text strictly between beginMarker and
// endMarker (both kept, byte-identical, in doc) for replacement --
// gen/main.go uses this to regenerate extending-the-canvas.md's one
// generated table in place without touching the hand-authored prose
// around it; the freshness test below does the same splice to compare
// against the committed file.
func ReplaceMarkedRegion(doc, beginMarker, endMarker, replacement string) (string, error) {
	start := strings.Index(doc, beginMarker)
	if start == -1 {
		return "", fmt.Errorf("begin marker %q not found", beginMarker)
	}
	contentStart := start + len(beginMarker)
	end := strings.Index(doc[contentStart:], endMarker)
	if end == -1 {
		return "", fmt.Errorf("end marker %q not found after begin marker", endMarker)
	}
	end += contentStart
	return doc[:contentStart] + "\n\n" + replacement + "\n" + doc[end:], nil
}
