package docsgen

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/alicoding/mill/internal/adapters/settings"
	"github.com/alicoding/mill/internal/domain/atlas"
	"github.com/alicoding/mill/internal/domain/capabilities"
	"github.com/alicoding/mill/internal/domain/composition"
	"github.com/alicoding/mill/internal/services/mcpsvc"
	"github.com/alicoding/mill/internal/services/pluginsvc"
)

// Markers bounding the README's one generated region -- the "What Mill
// does today" inventory. Only the text between them is regenerated by
// `go generate ./internal/docsgen` and diff-checked by
// TestREADME_MatchesGenerated; the hand-written sections around it
// carry no such promise.
const (
	ReadmeInventoryBeginMarker = "<!-- mill:inventory:start -->"
	ReadmeInventoryEndMarker   = "<!-- mill:inventory:end -->"
)

// GenerateReadmeInventory renders the README's capability inventory
// straight off the registries: one bullet per sidebar capability (its
// nav label, linked to its concept page, plus that page's opening
// sentence or the registry's own Summary), a counts line, and one
// bullet each for the two reaches that are not sidebar pages -- MCP
// and the browser bridge -- pointing at their docs. docsRoot is the
// userdocs tree; store backs the bare MCP server the tool count comes
// from.
func GenerateReadmeInventory(docsRoot string, store settings.Store) (string, error) {
	var b strings.Builder
	for _, c := range capabilities.List() {
		if c.HiddenFromNav {
			continue
		}
		label := c.NavLabel
		if label == "" {
			label = c.Label
		}
		if c.ConceptPage == "" {
			fmt.Fprintf(&b, "- **%s** — %s\n", label, c.Summary)
			continue
		}
		page, ok := PageByRel(c.ConceptPage)
		if !ok {
			return "", fmt.Errorf("capability %q names a concept page outside the docs index: %s", c.ID, c.ConceptPage)
		}
		sentence, err := firstSentence(docsRoot, page)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "- **[%s](userdocs/%s)** — %s\n", label, page.Rel, sentence)
	}
	tools, err := mcpsvc.BuiltInToolNames(store)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "\n%d step types · %d board object kinds · %d extension contribution families · %d MCP tools\n\n",
		len(composition.NodeTypes()), len(atlas.BuiltInBoardObjectKinds()), len(pluginsvc.ContributionKindNames()), len(tools))
	for _, rel := range []string{"agents/connect-mcp.md", "reference/browser-extension.md"} {
		page, ok := PageByRel(rel)
		if !ok {
			return "", fmt.Errorf("README reach bullet names a page outside the docs index: %s", rel)
		}
		fmt.Fprintf(&b, "- **[%s](userdocs/%s)** — %s.\n", page.Title, page.Rel, upperFirst(page.Note))
	}
	return b.String(), nil
}

// firstSentence is the opening sentence of a page's first paragraph
// after its title -- the hook every concept page leads with -- with
// the source's soft line wraps joined.
func firstSentence(docsRoot string, page DocPage) (string, error) {
	body, err := readPageBody(docsRoot, page)
	if err != nil {
		return "", err
	}
	var paragraph []string
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "#"):
			continue
		case trimmed == "":
			if len(paragraph) > 0 {
				return cutSentence(strings.Join(paragraph, " ")), nil
			}
		default:
			paragraph = append(paragraph, trimmed)
		}
	}
	if len(paragraph) == 0 {
		return "", fmt.Errorf("%s has no opening paragraph to quote", page.Rel)
	}
	return cutSentence(strings.Join(paragraph, " ")), nil
}

// cutSentence ends text at the first sentence terminator that is
// followed by a space (an inline "e.g." or a version number keeps
// going), or returns the whole text when it holds a single sentence.
func cutSentence(text string) string {
	runes := []rune(text)
	for i, r := range runes {
		if (r == '.' || r == '!' || r == '?') && i+1 < len(runes) && unicode.IsSpace(runes[i+1]) {
			return string(runes[:i+1])
		}
	}
	return text
}

func upperFirst(s string) string {
	runes := []rune(s)
	if len(runes) == 0 {
		return s
	}
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}
