// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

/**
 * Tool is one tool a configured MCP server exposes -- Mill's own shape,
 * not mcp.Tool, so a caller (ConfigureService) never needs the SDK type.
 */
export interface Tool {
    "Name": string;
    "Description": string;

    /**
     * InputSchema is the tool's raw JSON Schema, shown as-is in Configure
     * (docs/SPEC.md §3.6's "List tools" reference view) -- Mill doesn't
     * interpret it, so there's nothing to lose by keeping it opaque.
     */
    "InputSchema": json$0.RawMessage;
}
