// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RuleTestResult is one dry-run's outcome for the Configure tester.
 */
export interface RuleTestResult {
    "effect": string;
    "ruleID": string;
    "ruleLabel": string;

    /**
     * EffectClass is the tested node type's declared side-effect class,
     * so the tester can explain a default verdict ("external steps ask
     * by default").
     */
    "effectClass": string;
}
