// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as guardrail$0 from "../../domain/guardrail/models.js";

/**
 * Decision is RequestGuardedAction's outcome. Approved is what every
 * caller branches on; Effect/RuleID/RuleLabel identify what decided it
 * (the original verdict, even after a human resolves an ask -- Effect
 * stays "ask", Approved carries the human's actual answer).
 */
export interface Decision {
    "Approved": boolean;
    "Effect": guardrail$0.Effect;
    "RuleID": string;
    "RuleLabel": string;
}

/**
 * GuardedAction is what a non-workflow caller -- an agent today, a
 * plugin once the out-of-tree loader ships (docs/adr/0047 §5) -- asks
 * the guardrail to judge. Attributes is evaluated by the exact same
 * rule conditions (guardrail.ConditionEnv) a workflow step's own
 * Attributes already are.
 */
export interface GuardedAction {
    /**
     * Kind names the action class for rule targeting (fills
     * Step.NodeTypeID -- see EvaluateAction).
     */
    "Kind": string;

    /**
     * Attributes is the same map[string]string vocabulary a workflow
     * step's rules already evaluate.
     */
    "Attributes": { [_ in string]?: string } | null;

    /**
     * Description feeds the approval UI (Review, the floating prompt).
     */
    "Description": string;

    /**
     * Source names who's asking (an agent id, a future plugin id) --
     * carried onto the parked PendingGuardedAction's own Source field.
     */
    "Source": string;
}

/**
 * PendingGuardedAction is a parked, not-yet-resolved GuardedAction --
 * the non-workflow analogue of executionsvc.PendingApproval (docs/adr/0047
 * §5 point 3): additive, never reshaping the workflow park it is meant
 * to one day render alongside.
 */
export interface PendingGuardedAction {
    "ID": string;
    "Kind": string;
    "Attributes": { [_ in string]?: string } | null;
    "Description": string;
    "Source": string;
    "CreatedAt": string;
}

/**
 * RuleTestResult is one dry-run's outcome for the Configure tester.
 */
export interface RuleTestResult {
    "effect": string;
    "ruleID": string;
    "ruleLabel": string;

    /**
     * EffectClass is the tested node type's declared side-effect class,
     * so the tester can explain a default verdict ("external steps ask
     * by default").
     */
    "effectClass": string;

    /**
     * Source mirrors the deciding rule's guardrail.Source (SourceDebug
     * for a breakpoint, "" for policy) -- docs/adr/0031: the canvas's
     * nothing-hidden badge uses this to render the distinct debug badge
     * instead of the policy shield when a breakpoint is what's actually
     * asking.
     */
    "source"?: string;
}
