// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../typedfield/models.js";

/**
 * Card is one instance of a Kind, placed inside another card's
 * containment (or at the root, ParentID == ""). Every structural
 * capability below is optional and exists on every card regardless of
 * Kind (ADR-0038 Decision 2: structure, not concept) -- a card either
 * uses a given attribute or leaves it at its zero value.
 */
export interface Card {
    "ID": string;
    "KindID": string;
    "Title": string;
    "Note": string;

    /**
     * Fields holds this card's values against its Kind's declared
     * schema, keyed by typedfield.Field.Key -- same "every value stays
     * a plain string on the wire" discipline typedfield.Field's own
     * doc comment establishes.
     */
    "Fields": { [_ in string]?: string } | null;

    /**
     * ParentID is the containment primitive: "" means root-level,
     * otherwise the containing card's ID. Every card can contain
     * (ADR-0038 Decision 3); there is no separate "space" type.
     */
    "ParentID": string;

    /**
     * Position is this card's placement within ParentID's canvas, nil
     * unless the parent is in canvas mode.
     */
    "Position": Position | null;

    /**
     * ViewMode governs how CardID's own children render -- see the
     * type's doc comment above.
     */
    "ViewMode": ViewMode;

    /**
     * Source is an optional URL this card mirrors/projects.
     */
    "Source": string;

    /**
     * MirrorPath is an optional local file path this card's content is
     * synced to -- empty until a refresh has actually run once.
     */
    "MirrorPath": string;

    /**
     * MirrorChecksum is the SHA-256 (lowercase hex) of MirrorPath's
     * content at capture/refresh time -- empty until first computed.
     */
    "MirrorChecksum": string;

    /**
     * RefreshWorkflowID optionally names the workflow that refreshes
     * this card's mirror -- "Update now" runs it through the normal
     * guardrail gate (ADR-0038 Decision 4); resolution/existence of the
     * referenced workflow is a service-layer concern, not checked here.
     */
    "RefreshWorkflowID": string;

    /**
     * ActionWorkflowIDs are the card's attached actions (goal 0084):
     * callable workflows a user runs against this card from its page
     * or menu, each receiving the card's identity through the same
     * declared-Attributes convention trigger-atlas-card fires with.
     * Supersedes the single RefreshWorkflowID (migrated on restore;
     * the old field stays on the wire for import compatibility).
     */
    "ActionWorkflowIDs": string[] | null;

    /**
     * LastSyncedAt is when a refresh action last completed for this
     * card -- zero value means never synced.
     */
    "LastSyncedAt": string;

    /**
     * ReceiptRunID optionally names the run whose receipt produced this
     * card's current mirrored content -- provenance for a machine-made
     * write (ADR-0038's integration map).
     */
    "ReceiptRunID": string;
    "CreatedAt": string;
    "UpdatedAt": string;
    "BuiltIn": boolean;
    "Seed": seedorigin$0.Origin;
}

/**
 * Kind is a user-declared card type: a name, an optional description/
 * emoji glyph, and a field schema via typedfield.Field -- the exact
 * canonical vocabulary list.Column and decision.OutputField already
 * converge on (ADR-0029), reused here rather than a fourth near-
 * duplicate. Icon is a bare emoji string (e.g. "🧭"), optional --
 * rendering/validity of the glyph itself is a frontend concern, not
 * checked here.
 */
export interface Kind {
    "ID": string;
    "Label": string;
    "Description": string;
    "Icon": string;
    "Fields": typedfield$0.Field[] | null;

    /**
     * FieldTombstones records every Fields Key this Kind has ever
     * deleted (docs/adr/0040 decision 3), the same evolution ledger
     * decision.Decision.FieldTombstones/list.List.FieldTombstones
     * already carry for their own schema-carrying field sets --
     * typedfield.ValidateFieldEvolution's own doc comment has the full
     * rule this enforces at the atlassvc.UpdateKind chokepoint.
     */
    "FieldTombstones": typedfield$0.FieldTombstone[] | null;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (the
     * reserved-column pattern list.List/decision.Decision already
     * follow), stamped server-side at every persisted mutation, never
     * trusted from the wire.
     */
    "CreatedAt": string;
    "UpdatedAt": string;

    /**
     * BuiltIn marks a seeded example Kind -- informational only, same
     * as list.List.BuiltIn: drives a badge, never gates edit/delete.
     */
    "BuiltIn": boolean;

    /**
     * Seed is this Kind's seed provenance (docs/goals/0037), the same
     * insert/upgrade/leave-alone-once-Modified reconcile discipline
     * every other seeded entity in this codebase already carries.
     */
    "Seed": seedorigin$0.Origin;
}

/**
 * LensSetting is one container card's per-space density filter (ADR-
 * 0038's design principles): which Kind IDs stay hidden, and whether
 * this level's children peek into THEIR own children too (docs/goals/
 * 0061's "this level only vs peek into children" toggle, absorbed here
 * from its previous browser-localStorage home so it round-trips across
 * sessions/devices like every other Atlas preference).
 */
export interface LensSetting {
    "HiddenKindIDs": string[] | null;
    "Peek": boolean;
}

/**
 * Link is a typed, owner-authored relation between two cards -- binds
 * by card ID (a key), never by title (ADR-0038 Decision 3), so a card
 * rename can never silently break a relation.
 */
export interface Link {
    "ID": string;
    "FromCardID": string;
    "ToCardID": string;
    "LinkKindID": string;
    "Label": string;
    "CreatedAt": string;
    "UpdatedAt": string;
    "BuiltIn": boolean;
    "Seed": seedorigin$0.Origin;
}

/**
 * LinkKind is a user-declared relation type (the "rope" binding two
 * cards) -- a name and description only; the relation itself (Link)
 * carries the endpoints.
 */
export interface LinkKind {
    "ID": string;
    "Label": string;
    "Description": string;
    "CreatedAt": string;
    "UpdatedAt": string;
    "BuiltIn": boolean;
    "Seed": seedorigin$0.Origin;
}

/**
 * MirrorContent is a card's MirrorPath resolved into a read-only
 * overlay preview (docs/goals/0064), returned by atlassvc.AtlasService.
 * MirrorContent. Size is always populated (even when TooLarge or
 * Kind==MirrorKindOther) so the overlay's type+size+reveal fallback
 * always has something to show. Content holds rendered HTML for
 * MirrorKindMarkdown, raw text for MirrorKindText, or base64-encoded
 * bytes (paired with MimeType) for MirrorKindImage -- empty for
 * MirrorKindOther or whenever TooLarge is true.
 */
export interface MirrorContent {
    "Kind": MirrorKind;
    "MimeType": string;
    "Size": number;
    "Content": string;
    "TooLarge": boolean;
}

/**
 * MirrorKind classifies a mirrored file for the card overlay's preview
 * (docs/goals/0064): a pure, extension-only decision, no I/O -- the
 * service layer (atlassvc) is what actually stats/reads the file this
 * classifies.
 */
export enum MirrorKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * MirrorKindMarkdown renders through the markdown adapter to HTML.
     */
    MirrorKindMarkdown = "markdown",

    /**
     * MirrorKindText renders as plain, preformatted text.
     */
    MirrorKindText = "text",

    /**
     * MirrorKindImage renders inline as an image.
     */
    MirrorKindImage = "image",

    /**
     * MirrorKindOther never has its content loaded -- the overlay shows
     * only its kind and size, plus the existing reveal-file action.
     */
    MirrorKindOther = "other",
};

/**
 * Note is a quick-capture annotation on the Atlas board (goal 0081
 * slice A1's LOCKED design): structurally excluded from every semantic
 * mechanism a Card participates in -- no KindID, no Fields, no links.
 * It is its own collection, never registered in projections, the
 * traceability matrix, coverage, or jump results, so nothing jotted
 * here can accidentally become data. PromoteNote (atlassvc) is the
 * only path from a Note to a Card -- one-way, never a soft/reversible
 * conversion.
 */
export interface Note {
    "ID": string;
    "Text": string;
    "Position": Position;

    /**
     * ParentID is the containment primitive a Note shares with Card
     * (spatial filing only -- a note in an area carries no semantic
     * weight from that placement, per the LOCKED design's "containment
     * is location, not meaning").
     */
    "ParentID": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

/**
 * Position is a card's location within its PARENT's canvas -- only
 * meaningful when the parent's EffectiveViewMode is ViewModeCanvas;
 * nil for a card whose parent renders as shelves (or for a root card,
 * which has no parent canvas to be positioned on).
 */
export interface Position {
    "X": number;
    "Y": number;
}

/**
 * ScanCategory is the heuristic bucket a synced-folder scan's own
 * suggestion preview groups an entry under (docs/goals/0067) -- a
 * presentation grouping only, never a Kind: which real Kind each
 * bucket's accepted entries become is a choice the user makes in the
 * preview (ADR-0038 Decision 2 -- nothing may assume a specific seeded
 * Kind exists, since every Kind is user-owned, editable, deletable
 * data).
 */
export enum ScanCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ScanCategoryContainer is a directory -- becomes a container card
     * (ViewMode shelves) holding whatever of its own contents were
     * accepted.
     */
    ScanCategoryContainer = "container",

    /**
     * ScanCategoryImage is a file whose extension is a common image
     * format.
     */
    ScanCategoryImage = "image",

    /**
     * ScanCategoryFile is every other file -- text/markdown/office/PDF
     * documents and anything unrecognized alike, since an unfamiliar
     * extension is still worth suggesting as a plain reference rather
     * than silently excluded.
     */
    ScanCategoryFile = "file",
};

/**
 * ViewMode governs how a container card's CHILDREN render, not the
 * card itself -- ADR-0038 Decision 3's "space view mode is per-
 * container" call, resolved as a field ON Card rather than a separate
 * space/container type: every card can contain (ParentID is the one
 * containment primitive, structural regardless of Kind), so a card
 * that never gains a child simply never has its ViewMode read. Storing
 * it up front means drilling into a previously-childless card later
 * needs no schema migration.
 */
export enum ViewMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ViewModeCanvas renders children at their saved Position (React
     * Flow, per ADR-0038 Decision 4).
     */
    ViewModeCanvas = "canvas",

    /**
     * ViewModeShelves renders children auto-grouped by Kind, no
     * position needed -- the default (EffectiveViewMode below), since
     * an empty ViewMode on a freshly-created card must resolve to
     * something rather than rendering nothing.
     */
    ViewModeShelves = "shelves",
};
