// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindEnv reads a dotenv file (KEY=value lines): a project's own
     * .env, or a Bruno collection's -- Bruno's documented secrets
     * channel is exactly this file at the collection root.
     */
    KindEnv = "env",

    /**
     * KindBruno reads a Bruno collection (its folder, or its
     * bruno.json): the .env at the collection root supplies values, the
     * environments' `vars:secret` blocks name what the collection
     * expects, and bruno.json names it (goal 0306 slice 2).
     */
    KindBruno = "bruno",
};

export interface Source {
    "ID": string;
    "Label": string;
    "Kind": Kind;
    "Path": string;
    "BuiltIn": boolean;
    "Seed": seedorigin$0.Origin;
    "CreatedAt": string;
    "UpdatedAt": string;
}
