// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthConfig bundles the non-secret config for whichever AuthType an
 * HTTPRequest actually uses -- one additive, optional field (nil for
 * every request using none of these three), same "additive pointer
 * field" shape OpenAPISpec's own history already proved safe
 * (ADR-0007).
 */
export interface AuthConfig {
    "OAuth2": OAuth2Config | null;
    "HMAC": HMACConfig | null;
    "OAuth1": OAuth1Config | null;
}

/**
 * AuthType is how a request authenticates against the HTTPRequest's
 * BaseURL. Grew from the original 3 to the full 7-option catalogue a
 * reference-platform review found real (docs/SPEC.md §4.1, ADR-0015) --
 * each type's actual request-mutation logic is a registered
 * AuthStrategy (internal/domain/composition), not a switch here; this
 * package only owns the type identifier and its config shape.
 * AuthOAuth1Vendor and AuthMTLS are real, registered AuthTypes whose
 * strategy deliberately returns "not yet implemented" (ADR-0015's own
 * research checkpoint: OAuth1Vendor's exact vendor quirk and mTLS's
 * full field set were both left unresolved even by the fuller research
 * pass) -- proving the strategy registry accepts a new AuthType as a
 * pure addition, without implementing behavior that was never actually
 * specified.
 */
export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthNone = "none",
    AuthAPIKey = "apikey",
    AuthBearer = "bearer",

    /**
     * AuthHMAC signs the request (method+path+timestamp+body) with
     * HMAC-SHA256, sent as X-Signature/X-Timestamp headers -- Mill's own
     * defensible default (ADR-0015's research checkpoint found no single
     * universal HMAC-auth convention to adopt instead).
     */
    AuthHMAC = "hmac",

    /**
     * AuthOAuth1 is the real RFC 5849 standard, HMAC-SHA1 signature
     * method -- covers what the reference-platform research called
     * "OAuth 1.0 HMAC."
     */
    AuthOAuth1 = "oauth1",

    /**
     * AuthOAuth1Vendor is the reference-platform research's own
     * "vendor-specific OAuth 1.0a variant" -- its actual quirk was never
     * confirmed (ADR-0015), so its strategy is a stub, not a guess.
     */
    AuthOAuth1Vendor = "oauth1vendor",

    /**
     * AuthOAuth2 implements the client_credentials grant via
     * golang.org/x/oauth2/clientcredentials (already an indirect
     * dependency, promoted to direct).
     */
    AuthOAuth2 = "oauth2",

    /**
     * AuthQueryParam places the resolved secret in the URL's query
     * string instead of a header.
     */
    AuthQueryParam = "queryparam",

    /**
     * AuthMTLS is a real, registered AuthType whose strategy is a stub
     * -- explicitly out of scope for implementation this goal (decided
     * directly with the user), proving the seam accepts it as a pure
     * addition for whenever it is built.
     */
    AuthMTLS = "mtls",
};

/**
 * HMACConfig is AuthHMAC's non-secret configuration. The signing key
 * itself is the request's keychain secret.
 */
export interface HMACConfig {
    /**
     * HeaderName defaults to "X-Signature" when empty.
     */
    "HeaderName": string;
}

/**
 * HTTPRequest is one reusable, named way to reach an external API
 * (ADR-0016 -- named Connector before this ADR). Headers are static,
 * always-sent headers (e.g. "Accept": "application/json") -- distinct
 * from the AuthType-driven Authorization header, which
 * internal/adapters/httpconnector adds itself from the resolved
 * secret, never stored here. Method/Params/Body land in Phase B
 * (ADR-0016) -- this pass is a pure rename, no shape change beyond
 * dropping the now-redundant Type field below.
 */
export interface HTTPRequest {
    "ID": string;
    "Label": string;
    "BaseURL": string;

    /**
     * Method is the HTTP method this request uses -- ADR-0016 Phase B's
     * entity half: Method and URL are peers on the request object
     * (Postman/Bruno's own shape), not something buried inside schema
     * authoring. Open text, never a closed enum (RFC 10008's QUERY, a
     * vendor verb) -- any string is sent as-is. Empty means GET, which
     * also covers every request saved before this field existed. An
     * integration-http node may still override it per-step (its own
     * method config field wins when non-empty).
     */
    "Method": string;
    "AuthType": AuthType;
    "Headers": { [_ in string]?: string } | null;

    /**
     * Body is an optional raw request body sent as-is when the schema's
     * bound body fields don't produce one -- request-level, not
     * workflow-node-level, by direct user decision ("form fields that
     * should not be done at the workflow level"): transport and payload
     * shape belong to the Integration; a workflow node only binds data.
     * ADR-0016 Phase B's body half in its minimal raw form; the typed
     * body-type picker (form-data/GraphQL/...) remains named future work.
     */
    "Body": string;

    /**
     * Description is free-text explaining what this request is/does --
     * optional. Particularly useful for a seeded example (BuiltIn below):
     * explaining what it demonstrates, and any honest caveat (e.g. "not
     * independently validated by the target server" or "bring your own
     * credentials").
     */
    "Description": string;

    /**
     * OpenAPISpec is the raw OpenAPI 3.x document (JSON or YAML) this
     * request's operations are declared against -- optional (ADR-0007).
     * Parsed via internal/adapters/openapispec. An HTTPRequest with no
     * spec behaves exactly as before this field existed.
     */
    "OpenAPISpec": string;

    /**
     * Auth is the non-secret config for AuthOAuth2/AuthHMAC/AuthOAuth1
     * (ADR-0015) -- nil for AuthNone/AuthAPIKey/AuthBearer and every
     * request saved before this field existed.
     */
    "Auth": AuthConfig | null;

    /**
     * JOSE is the optional request/response encryption layer (Phase 3)
     * -- nil for every request saved before this field existed, and for
     * any request not using it.
     */
    "JOSE": JOSEConfig | null;

    /**
     * BuiltIn marks a seeded example request (BuiltIn() below) --
     * purely informational, same as composition.Workflow.BuiltIn: it
     * drives a "built-in" badge in the UI only, never gates Edit/Delete.
     * A seeded example is an ordinary, fully-editable/deletable request
     * from the moment it exists (docs/SPEC.md §2.2's Update note -- the
     * same Zapier/n8n-precedented pattern, applied here to HTTPRequests
     * instead of Workflows).
     */
    "BuiltIn": boolean;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (SPEC.md
     * §3.2.2's reserved-column pattern), stamped server-side at every
     * persisted mutation (ConfigureService), never trusted from the
     * wire. Zero value means pre-timestamp data -- migration-free.
     */
    "CreatedAt": string;
    "UpdatedAt": string;
}

/**
 * JOSEConfig is Phase 3's request/response encryption layer (ADR-0015's
 * own follow-up, docs/SPEC.md §3.2's Update: "JOSE Encryption ...
 * encrypts what [Mill] sends to the vendor, and optionally decrypts
 * what it receives back (JWE)"). Deliberately independent of AuthType
 * -- a request can combine JOSE with any auth scheme, since the two
 * solve different problems (who's calling vs. what the call's own body
 * looks like on the wire). RecipientPublicKeyPEM is not a secret (a
 * public key), so it lives here in plain config, same as Headers;
 * Mill's own private key (needed only when DecryptResponse is true)
 * stays in the OS keychain, a second, JOSE-specific keychain entry
 * alongside whatever AuthType's own secret already uses (ADR-0015 §3's
 * same reasoning: a scheme needing a secret-shaped value distinct from
 * AuthType's own secret gets its own storage, not smuggled into the
 * same slot).
 */
export interface JOSEConfig {
    "Enabled": boolean;

    /**
     * Algorithm is the JWE key-encryption algorithm (e.g.
     * "RSA-OAEP-256"). Empty defaults to Mill's own stated default at
     * execution time (internal/domain/composition/jose.go), not
     * enforced here -- same "default applied at use, not required at
     * save" shape HMACConfig.HeaderName already has.
     */
    "Algorithm": string;

    /**
     * ContentEncryption is the JWE content-encryption algorithm (e.g.
     * "A256GCM"). Same empty-defaults-at-use-time shape as Algorithm.
     */
    "ContentEncryption": string;

    /**
     * RecipientPublicKeyPEM is the vendor's RSA public key (PEM,
     * PKIX or PKCS1), used to encrypt the outgoing request body.
     */
    "RecipientPublicKeyPEM": string;

    /**
     * DecryptResponse, if true, decrypts the response body as a JWE
     * using Mill's own private key (keychain) before it's processed as
     * the workflow payload -- optional, matching the reference
     * platform's own "optionally decrypts" framing.
     */
    "DecryptResponse": boolean;
}

/**
 * OAuth1Config is AuthOAuth1's non-secret configuration (RFC 5849).
 * ConsumerSecret/TokenSecret are JSON-encoded into the request's one
 * keychain secret slot rather than Mill inventing a multi-secret-per-
 * request storage model (ADR-0015 §3) -- Token itself is optional per
 * RFC 5849 (2-legged OAuth omits it).
 */
export interface OAuth1Config {
    "ConsumerKey": string;
    "Token": string;
}

/**
 * OAuth2Config is AuthOAuth2's non-secret configuration -- ClientSecret
 * itself stays in the OS keychain (internal/adapters/credential), same
 * as every other AuthType's secret.
 */
export interface OAuth2Config {
    /**
     * GrantType is fixed to "client_credentials" this pass -- the only
     * grant the reference-platform research actually specified fields
     * for (docs/SPEC.md §4.1). Kept as a field, not hardcoded, so a
     * second grant type is a config addition later, not a schema change.
     */
    "GrantType": string;
    "TokenURL": string;
    "ClientID": string;
    "Scope": string;
    "ContentType": string;
}
