// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildInfo is what's actually running, not what the source tree looks
 * like -- the two silently diverged this session (a desktop app process
 * stayed up across an entire session's worth of commits, showing hours-
 * stale UI, with nothing anywhere flagging it). Wails3's own SDK reads
 * the identical runtime/debug.ReadBuildInfo() data (application_debug.go)
 * but only wires it up under `!production` and never exposes it to the
 * frontend -- this is Mill's own copy, unconditional on any build tag,
 * specifically so it's visible in every build, not just dev.
 */
export interface BuildInfo {
    /**
     * Revision is the short (12-char) git commit hash the running binary
     * was built from, or "" if `go build` couldn't determine one (e.g.
     * building outside a git checkout, or with -buildvcs=false).
     */
    "Revision": string;

    /**
     * Modified is true when the working tree had uncommitted changes at
     * build time -- the single most useful bit here: it's the difference
     * between "this binary is an old commit" (rebuild it) and "this
     * binary has changes that were never committed at all" (a different,
     * more concerning kind of stale).
     */
    "Modified": boolean;

    /**
     * Server is true in the `server` build (headless HTTP mode) -- the
     * AUTHORITATIVE native-vs-server signal for the frontend. Found the
     * hard way (goal 0021 dogfooding): `'_wails' in window` is true in a
     * plain browser tab on the server-mode interface too (the Wails JS
     * runtime injects it in every mode), so frontend-side detection was
     * silently wrong -- native-only chrome (the titlebar traffic-light
     * inset) rendered in server mode, and the INSTALLED/SERVER badge
     * split never actually worked. The build tag is the one place that
     * genuinely knows.
     */
    "Server": boolean;

    /**
     * BuiltAt is the unix-millis mtime of THIS PROCESS'S OWN executable
     * file -- when it was actually linked, not when its source was last
     * committed. Deliberately not vcs.time (goal 0029, dev-liveness
     * honesty): vcs.time reflects the last COMMIT's timestamp, which
     * stays frozen across every `wails3 dev` relink of an uncommitted
     * change (vcs.modified just goes true) -- exactly the case a wedged
     * or slow rebuild watcher needs distinguished from "healthy." A
     * binary's own mtime moves on every real relink regardless of git
     * state, so the frontend can compare it against the newest mtime of
     * internal/** /*.go (vite's dev-only middleware, vite.config.ts) to
     * tell "rebuilt after this save" from "still running the old one."
     */
    "BuiltAt": number;
}

/**
 * UpdateCheckResult is CheckForUpdates' Wails-bound result shape.
 */
export interface UpdateCheckResult {
    "updateAvailable": boolean;
    "version": string;
    "notes": string;
}
