// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CardDraft is one to-be-created card parsed from a valid create-cards
 * reply -- exactly what the review surface previews.
 */
export interface CardDraft {
    "title": string;
    "kind"?: string;
    "note"?: string;
    "summary"?: string;
}
