// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as atlas$0 from "../../domain/atlas/models.js";

/**
 * CanvasObjectContribution claims the ingestion doors for one canvas
 * object kind: which dropped-file extensions and which clipboard
 * shapes land as this plugin's object. Payload shape is not declared
 * here -- it derives from the object's own registered source (a
 * fileExtensions claim requires a file-backed object landing
 * mirrorPath+title; PastesURLs requires a url-backed one landing
 * url+title), enforced host-side at registration.
 */
export interface CanvasObjectContribution {
    "kind": string;
    "fileExtensions": string[] | null;
    "pastesURLs": boolean;
}

/**
 * ContentWriter is the seam pluginsvc writes through; nil until wired.
 */
export type ContentWriter = any;

/**
 * GuardedActionDecision is RequestGuardedAction's wire shape.
 */
export interface GuardedActionDecision {
    "Approved": boolean;
    "Effect": string;
    "RuleLabel": string;

    /**
     * Performed is true when Mill executed the approved action itself
     * (the plugin never receives the primitive).
     */
    "Performed": boolean;
}

/**
 * Manifest is the converged plugin manifest shape (docs/adr/0047 §1:
 * identity metadata + a declared capability set). Rendering
 * contributions happen at activate() time through the host API, so
 * they are not restated here; INGESTION claims are the deliberate
 * exception (docs/goals/0251) -- both ingestion chains must consult
 * them without running plugin code, so they live in Contributes.
 */
export interface Manifest {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "minMillVersion": string;
    "capabilities": string[] | null;
    "contributes": ManifestContributes;
}

/**
 * ManifestContributes is the manifest's declarative contribution
 * point (docs/goals/0251, the VSCode-shaped convention): data other
 * parts of Mill read to ROUTE to a plugin, distinct from capabilities
 * (what a plugin may ask to do).
 */
export interface ManifestContributes {
    "canvasObjects": CanvasObjectContribution[] | null;

    /**
     * Settings (docs/goals/0258 slice 1): the plugin's own declared
     * user settings, the same declare -> host renders/stores/serves
     * contract compiled-in nouns use. Declared in the manifest, not
     * at activate() time, so the Extensions row can render them
     * without running plugin code and validation fails the LOAD.
     */
    "settings": SettingContribution[] | null;

    /**
     * Network (docs/goals/0288): the hosts a plugin may fetch from,
     * declared so the Extensions row can state them before the plugin
     * runs and so an undeclared host is refused before any rule. Only
     * meaningful with the "fetch" capability.
     */
    "network": NetworkContribution[] | null;
}

/**
 * NetworkContribution names one host (lowercase, optional :port) and
 * the HTTP methods a plugin may use against it. An empty Methods means
 * GET only -- the read-only default.
 */
export interface NetworkContribution {
    "host": string;
    "methods": string[] | null;
}

/**
 * PluginContentWrite is one ask. Op is "note", "card", "card-update",
 * or "list-row"; the other fields apply per op.
 */
export interface PluginContentWrite {
    "op": string;
    "text": string;
    "title": string;
    "note": string;
    "kindId": string;
    "cardId": string;
    "parentId": string;
    "listId": string;
    "fields": { [_ in string]?: string } | null;
    "values": { [_ in string]?: string } | null;
    "position": atlas$0.Position | null;
}

/**
 * PluginContentWriteResult carries the decision and, when performed,
 * the created/updated entity's id.
 */
export interface PluginContentWriteResult {
    "approved": boolean;
    "effect": string;
    "ruleLabel": string;
    "id": string;
}

/**
 * PluginFetchRequest is what a plugin asks for; Headers and Body are
 * the plugin's own (a credential belongs in the vault -- goal 0281's
 * secretRef -- never here; nothing stops a plugin from passing a
 * token it holds, but the description in Review names the host so
 * whoever decides in Review sees where it goes).
 */
export interface PluginFetchRequest {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string } | null;
    "body": string;
}

/**
 * PluginFetchResult carries the guardrail decision and, when
 * approved and performed, the response.
 */
export interface PluginFetchResult {
    "approved": boolean;
    "effect": string;
    "ruleLabel": string;
    "status": number;
    "headers": { [_ in string]?: string } | null;
    "body": string;
}

/**
 * PluginInfo is one scanned plugin as the Extensions surface and the
 * loader see it. Error is a load-blocking validation problem stated
 * for the human (the row renders it; the loader skips the plugin) --
 * a plugin is either fully valid or visibly broken, never silently
 * half-loaded. Builtin marks a plugin embedded in the binary
 * (pluginservice_builtin.go): same loader and disable list as any
 * plugin, but nothing on disk to reveal or delete.
 */
export interface PluginInfo {
    "Manifest": Manifest;
    "Dir": string;
    "Error": string;
    "Builtin": boolean;
}

/**
 * SettingContribution is one declared plugin setting. Type is the
 * four-type floor every declarative settings platform shares:
 * "boolean", "string", "number", "enum". Default is the value in
 * effect until the user touches the control (the converged
 * `default` spelling), decoded as whatever JSON scalar the manifest
 * wrote; validateContributes pins it to Type. Options is enum-only;
 * Min/Max are number-only, both optional.
 */
export interface SettingContribution {
    "key": string;
    "type": string;
    "label": string;
    "description": string;
    "default": any;
    "options": SettingOption[] | null;
    "min": number | null;
    "max": number | null;
}

/**
 * SettingOption is one enum choice: the stored value and its
 * user-facing label.
 */
export interface SettingOption {
    "value": string;
    "label": string;
}
