// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CanvasObjectContribution claims the ingestion doors for one canvas
 * object kind: which dropped-file extensions and which clipboard
 * shapes land as this plugin's object. Payload shape is not declared
 * here -- it derives from the object's own registered source (a
 * fileExtensions claim requires a file-backed object landing
 * mirrorPath+title; PastesURLs requires a url-backed one landing
 * url+title), enforced host-side at registration.
 */
export interface CanvasObjectContribution {
    "kind": string;
    "fileExtensions": string[] | null;
    "pastesURLs": boolean;
}

/**
 * GuardedActionDecision is RequestGuardedAction's wire shape.
 */
export interface GuardedActionDecision {
    "Approved": boolean;
    "Effect": string;
    "RuleLabel": string;

    /**
     * Performed is true when Mill executed the approved action itself
     * (the plugin never receives the primitive).
     */
    "Performed": boolean;
}

/**
 * Manifest is the converged plugin manifest shape (docs/adr/0047 §1:
 * identity metadata + a declared capability set). Rendering
 * contributions happen at activate() time through the host API, so
 * they are not restated here; INGESTION claims are the deliberate
 * exception (docs/goals/0251) -- both ingestion chains must consult
 * them without running plugin code, so they live in Contributes.
 */
export interface Manifest {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "minMillVersion": string;
    "capabilities": string[] | null;
    "contributes": ManifestContributes;
}

/**
 * ManifestContributes is the manifest's declarative contribution
 * point (docs/goals/0251, the VSCode-shaped convention): data other
 * parts of Mill read to ROUTE to a plugin, distinct from capabilities
 * (what a plugin may ask to do).
 */
export interface ManifestContributes {
    "canvasObjects": CanvasObjectContribution[] | null;

    /**
     * Settings (docs/goals/0258 slice 1): the plugin's own declared
     * user settings, the same declare -> host renders/stores/serves
     * contract compiled-in nouns use. Declared in the manifest, not
     * at activate() time, so the Extensions row can render them
     * without running plugin code and validation fails the LOAD.
     */
    "settings": SettingContribution[] | null;
}

/**
 * PluginInfo is one scanned plugin as the Extensions surface and the
 * loader see it. Error is a load-blocking validation problem stated
 * for the human (the row renders it; the loader skips the plugin) --
 * a plugin is either fully valid or visibly broken, never silently
 * half-loaded. Builtin marks a plugin embedded in the binary
 * (pluginservice_builtin.go): same loader and disable list as any
 * plugin, but nothing on disk to reveal or delete.
 */
export interface PluginInfo {
    "Manifest": Manifest;
    "Dir": string;
    "Error": string;
    "Builtin": boolean;
}

/**
 * SettingContribution is one declared plugin setting. Type is the
 * four-type floor every declarative settings platform shares:
 * "boolean", "string", "number", "enum". Default is the value in
 * effect until the user touches the control (the converged
 * `default` spelling), decoded as whatever JSON scalar the manifest
 * wrote; validateContributes pins it to Type. Options is enum-only;
 * Min/Max are number-only, both optional.
 */
export interface SettingContribution {
    "key": string;
    "type": string;
    "label": string;
    "description": string;
    "default": any;
    "options": SettingOption[] | null;
    "min": number | null;
    "max": number | null;
}

/**
 * SettingOption is one enum choice: the stored value and its
 * user-facing label.
 */
export interface SettingOption {
    "value": string;
    "label": string;
}
