// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as atlas$0 from "../../domain/atlas/models.js";

/**
 * BrowseEntry is one offering in the Browse tab: the index's own
 * description of a plugin, plus which marketplace it came from and
 * whether it is already installed.
 */
export interface BrowseEntry {
    "Marketplace": string;
    "Owner": string;
    "ID": string;
    "Name": string;
    "Description": string;
    "Version": string;
    "Author": string;
    "Kinds": string[] | null;
    "Installed": boolean;

    /**
     * Tier is what installing this entry would earn, before any
     * download -- "hash-pinned" when the index declares a hash,
     * "unverified" when it does not.
     */
    "Tier": string;
}

/**
 * CanvasObjectContribution claims the ingestion doors for one canvas
 * object kind: which dropped-file extensions and which clipboard
 * shapes land as this plugin's object. Payload shape is not declared
 * here -- it derives from the object's own registered source (a
 * fileExtensions claim requires a file-backed object landing
 * mirrorPath+title; PastesURLs requires a url-backed one landing
 * url+title), enforced host-side at registration.
 */
export interface CanvasObjectContribution {
    "kind": string;
    "fileExtensions": string[] | null;
    "pastesURLs": boolean;
}

/**
 * CaptureContribution is one declared capture.
 */
export interface CaptureContribution {
    "id": string;
    "label": string;
    "description": string;
}

/**
 * CommandContribution declares one palette command the plugin
 * registers at activate() time. Declaring it is what lets a tool name
 * it; api.registerCommand still works for an undeclared id (the host
 * warns once), so this is required only for automation reach.
 */
export interface CommandContribution {
    "id": string;
    "label": string;

    /**
     * Menu seats this command in the native menu bar (goal 0335): the
     * host cross-references this declaration by id when the plugin
     * actually registers the command, since the manifest carries no
     * run() to seat directly. Restricted to the three menus a plugin's
     * own contributions can plausibly belong to -- never "app" or
     * "file", which stay Mill's own.
     */
    "menu"?: CommandMenuContribution | null;
}

/**
 * CommandMenuContribution is a plugin-contributed command's menu seat.
 * Group/Order default to 0 when omitted -- a single-command plugin
 * never needs to think about band position.
 */
export interface CommandMenuContribution {
    "path": string;
    "group": number;
    "order": number;
}

/**
 * ContentWriter is the seam pluginsvc writes through; nil until wired.
 */
export type ContentWriter = any;

/**
 * GuardedActionDecision is RequestGuardedAction's wire shape.
 */
export interface GuardedActionDecision {
    "Approved": boolean;
    "Effect": string;
    "RuleLabel": string;

    /**
     * Performed is true when Mill executed the approved action itself
     * (the plugin never receives the primitive).
     */
    "Performed": boolean;
}

/**
 * InstallPreview is what the user is shown BEFORE anything downloads:
 * who the extension is, what installing it would earn for trust, and
 * what it can do once it runs. Every permission-shaped fact a manifest
 * declares is here, so the prompt never has to re-derive one.
 */
export interface InstallPreview {
    "ID": string;
    "Name": string;
    "Version": string;
    "Author": string;
    "Description": string;
    "Marketplace": string;
    "Tier": string;

    /**
     * Capabilities are the manifest's declared capability ids
     * (pluginservice.go's vocabulary), rendered as sentences by the
     * surface that shows them.
     */
    "Capabilities": string[] | null;

    /**
     * NetworkHosts are the hosts contributes.network declares; AnyHost
     * is true when it declares "*".
     */
    "NetworkHosts": string[] | null;
    "AnyHost": boolean;

    /**
     * Kinds are the contribution families the manifest fills.
     */
    "Kinds": string[] | null;

    /**
     * UsesSecrets is true when the manifest declares a setting that
     * holds a secret reference -- the plugin never sees the secret, it
     * names one.
     */
    "UsesSecrets": boolean;

    /**
     * AlreadyInstalled reports an existing folder with this id, so the
     * prompt can say "reinstall" rather than "install".
     */
    "AlreadyInstalled": boolean;
}

/**
 * InstallRecord is that receipt: where the folder came from, what it
 * hashed to when it landed, and which tier that earned.
 */
export interface InstallRecord {
    "source": PluginSource;
    "marketplace": string;
    "version": string;
    "contentHash": string;
    "tier": string;
    "installedAt": string;
}

/**
 * Manifest is the converged plugin manifest shape (docs/adr/0047 §1:
 * identity metadata + a declared capability set). Rendering
 * contributions happen at activate() time through the host API, so
 * they are not restated here; INGESTION claims are the deliberate
 * exception (docs/goals/0251) -- both ingestion chains must consult
 * them without running plugin code, so they live in Contributes.
 */
export interface Manifest {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "minMillVersion": string;

    /**
     * Icon names this plugin's 128x128 icon file, relative to its own
     * folder (the standard's identity rule -- pluginsvc/conform_standard.go
     * checks it decodes to exactly that size). A sibling file with
     * "@dark" inserted before the extension, when present, is the
     * dark-appearance variant.
     */
    "icon": string;
    "capabilities": string[] | null;
    "contributes": ManifestContributes;
}

/**
 * ManifestContributes is the manifest's declarative contribution
 * point (docs/goals/0251, the VSCode-shaped convention): data other
 * parts of Mill read to ROUTE to a plugin, distinct from capabilities
 * (what a plugin may ask to do).
 */
export interface ManifestContributes {
    "canvasObjects": CanvasObjectContribution[] | null;

    /**
     * Steps (ADR-0051 §5, pluginservice_steps.go): workflow steps the
     * plugin implements in steps.js, declared here so the catalog and
     * the Extensions row know them before any code runs.
     */
    "steps": StepContribution[] | null;

    /**
     * Captures (goal 0309, pluginservice_captures.go): quick-capture
     * surfaces the plugin renders in the capture window.
     */
    "captures": CaptureContribution[] | null;

    /**
     * Settings (docs/goals/0258 slice 1): the plugin's own declared
     * user settings, the same declare -> host renders/stores/serves
     * contract compiled-in nouns use. Declared in the manifest, not
     * at activate() time, so the Extensions row can render them
     * without running plugin code and validation fails the LOAD.
     */
    "settings": SettingContribution[] | null;

    /**
     * Network (docs/goals/0288): the hosts a plugin may fetch from,
     * declared so the Extensions row can state them before the plugin
     * runs and so an undeclared host is refused before any rule. Only
     * meaningful with the "fetch" capability.
     */
    "network": NetworkContribution[] | null;

    /**
     * Views (docs/goals/0290): the work tabs a plugin may open, declared
     * so the Extensions row can state them before the plugin runs and
     * so activate-time registerView is checked against a declaration.
     */
    "views": ViewContribution[] | null;

    /**
     * Commands (docs/goals/0324): the palette commands the plugin
     * registers at activate() time. Declaring one is what lets a tool
     * name it; an undeclared registerCommand still works.
     */
    "commands": CommandContribution[] | null;

    /**
     * Themes (docs/goals/0342): color themes the plugin ships as CSS
     * data files. Declared here because the picker lists them before
     * any plugin code runs, and a theme needs no code at all.
     */
    "themes": ThemeContribution[] | null;

    /**
     * Tools (docs/goals/0324): the automation-reachable surface --
     * which of this plugin's commands, steps and reads an agent may
     * call over MCP, each with its own typed input contract.
     */
    "tools": ToolContribution[] | null;
}

/**
 * MarketplaceSource is one place Mill reads an index from, as the user
 * added it. Kind is "github" (owner/repo[@ref]), "git" (a repository
 * URL), "url" (a direct index address) or "path" (a folder on this
 * Mac). Name is filled in from the index the first time it parses.
 */
export interface MarketplaceSource {
    "name": string;
    "kind": string;
    "locator": string;
    "ref": string;
    "addedAt": string;
}

/**
 * NetworkContribution names one host (lowercase, optional :port) and
 * the HTTP methods a plugin may use against it. An empty Methods means
 * GET only -- the read-only default.
 */
export interface NetworkContribution {
    "host": string;
    "methods": string[] | null;
}

/**
 * PluginCapture is one runnable plugin's declared capture as the Quick
 * Panel and the palette list it.
 */
export interface PluginCapture {
    "pluginId": string;
    "pluginName": string;
    "id": string;
    "label": string;
    "description": string;
}

/**
 * PluginContentWrite is one ask. Op is "note", "card", "card-update",
 * "list-row", or "list"; the other fields apply per op.
 */
export interface PluginContentWrite {
    "op": string;
    "text": string;
    "title": string;
    "note": string;
    "kindId": string;
    "cardId": string;
    "parentId": string;
    "listId": string;
    "fields": { [_ in string]?: string } | null;
    "values": { [_ in string]?: string } | null;
    "position": atlas$0.Position | null;

    /**
     * The "list" op: Title names the list; Rows are keyed by column
     * name (or derived key).
     */
    "description": string;
    "columns": PluginListColumn[] | null;
    "rows": ({ [_ in string]?: string } | null)[] | null;
}

/**
 * PluginContentWriteResult carries the decision and, when performed,
 * the created/updated entity's id.
 */
export interface PluginContentWriteResult {
    "approved": boolean;
    "effect": string;
    "ruleLabel": string;
    "id": string;
}

/**
 * PluginFetchRequest is what a plugin asks for; Headers and Body are
 * the plugin's own (a credential belongs in the vault -- goal 0281's
 * secretRef -- never here; nothing stops a plugin from passing a
 * token it holds, but the description in Review names the host so
 * whoever decides in Review sees where it goes).
 */
export interface PluginFetchRequest {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string } | null;
    "body": string;

    /**
     * Secret names a declared secretRef setting whose vault entry Mill
     * attaches host-side (pluginservice_fetch_secret.go); nil sends
     * the request exactly as given.
     */
    "secret": PluginFetchSecret | null;
}

/**
 * PluginFetchResult carries the guardrail decision and, when
 * approved and performed, the response.
 */
export interface PluginFetchResult {
    "approved": boolean;
    "effect": string;
    "ruleLabel": string;
    "status": number;
    "headers": { [_ in string]?: string } | null;
    "body": string;
}

/**
 * PluginFetchSecret is api.fetch's init.secret: WHICH setting names
 * the entry, and how it travels (default: Authorization: Bearer …).
 */
export interface PluginFetchSecret {
    "settingKey": string;
    "header": string;
    "prefix": string;
}

/**
 * PluginFileEntry is one listed entry.
 */
export interface PluginFileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
}

/**
 * PluginInfo is one scanned plugin as the Extensions surface and the
 * loader see it. Error is a load-blocking validation problem stated
 * for the human (the row renders it; the loader skips the plugin) --
 * a plugin is either fully valid or visibly broken, never silently
 * half-loaded. Builtin marks a plugin embedded in the binary
 * (pluginservice_builtin.go): same loader and disable list as any
 * plugin, but nothing on disk to reveal or delete.
 */
export interface PluginInfo {
    "Manifest": Manifest;
    "Dir": string;
    "Error": string;
    "Builtin": boolean;

    /**
     * ContentHash is the folder's current content hash
     * (pluginservice_hash.go), "" for a built-in or an invalid plugin
     * -- what the lock compares against.
     */
    "ContentHash": string;

    /**
     * SigningPolicy reports whether an administrator pinned signing
     * keys; Signed whether this folder's signature verified against one
     * (pluginservice_signing.go). Both false with no policy.
     */
    "SigningPolicy": boolean;
    "Signed": boolean;

    /**
     * Tier is the install trust tier (trust.go, docs/goals/0349): what
     * actually checked these bytes when they landed. "" for a built-in.
     */
    "Tier": string;

    /**
     * Marketplace names the index this folder was installed from, ""
     * when it arrived some other way.
     */
    "Marketplace": string;
}

/**
 * PluginListColumn is one column of a plugin-created list: a display
 * name (its key is derived) and an optional type from listColumnTypes
 * (text when empty).
 */
export interface PluginListColumn {
    "name": string;
    "type": string;
}

/**
 * PluginListDirResult carries the verdict and, when approved, the
 * entries.
 */
export interface PluginListDirResult {
    "approved": boolean;
    "effect": string;
    "ruleLabel": string;
    "entries": PluginFileEntry[] | null;
}

/**
 * PluginSource is where one marketplace entry's files come from. Kind
 * is "path" (a folder relative to the index), "github" (a repository's
 * releases) or "archive" (a direct zip URL). SHA256 is the bare hex
 * digest of the downloaded archive when the publisher declares one --
 * declaring it is what earns the hash-pinned tier.
 */
export interface PluginSource {
    "kind": string;
    "path": string;
    "repo": string;
    "ref": string;
    "sha": string;
    "url": string;
    "sha256": string;
}

/**
 * SettingContribution is one declared plugin setting. Type is the
 * four-type floor every declarative settings platform shares --
 * "boolean", "string", "number", "enum" -- plus "secretRef" (ADR-0048):
 * the user picks a vault entry, the stored value is that entry's id,
 * and the plugin only ever reads its title. Default is the value in
 * effect until the user touches the control (the converged
 * `default` spelling), decoded as whatever JSON scalar the manifest
 * wrote; validateContributes pins it to Type. Options is enum-only;
 * Min/Max are number-only, both optional.
 */
export interface SettingContribution {
    "key": string;
    "type": string;
    "label": string;
    "description": string;
    "default": any;
    "options": SettingOption[] | null;
    "min": number | null;
    "max": number | null;
}

/**
 * SettingOption is one enum choice: the stored value and its
 * user-facing label.
 */
export interface SettingOption {
    "value": string;
    "label": string;
}

/**
 * StepConfigContribution is one authored field of a declared step --
 * text or a fixed option list, the two shapes a no-build plugin can
 * state as data.
 */
export interface StepConfigContribution {
    "key": string;
    "label": string;
    "description": string;
    "type": string;
    "default": string;
    "options": string[] | null;
}

/**
 * StepContribution is one declared step.
 */
export interface StepContribution {
    "id": string;
    "label": string;
    "description": string;
    "config": StepConfigContribution[] | null;
}

/**
 * ThemeContribution declares one color theme: an id unique within the
 * plugin, the label the picker lists, which appearance family it
 * belongs to, and the CSS file relative to the plugin's own folder.
 */
export interface ThemeContribution {
    "id": string;
    "label": string;
    "family": string;
    "file": string;
}

/**
 * ToolContribution declares one agent-reachable tool. InputSchema is
 * the tool's own JSON Schema, carried verbatim to the MCP tool list --
 * the plugin author writes the contract the agent reads. Effect is the
 * consent layer's input, not the schema's: "write" routes through the
 * write gate and the approval park, "read" answers directly.
 */
export interface ToolContribution {
    "name": string;
    "description": string;
    "inputSchema": json$0.RawMessage;
    "effect": string;
    "run": ToolRun;
}

/**
 * ToolRun says WHAT a tool runs. Kind "command" runs a declared
 * palette command in the webview (argument-less: Command.run takes
 * none); "step" runs one of the plugin's own declared workflow steps;
 * "query" reads the board's contents through the host's own content
 * index.
 */
export interface ToolRun {
    "kind": string;
    "commandId"?: string;
    "stepId"?: string;
}

/**
 * ViewContribution declares one plugin-owned work tab: a slug id
 * unique within the plugin and the tab's title.
 */
export interface ViewContribution {
    "id": string;
    "title": string;
}
