// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService is Wails-bound. openURL is injected so tests never
 * shell out to the real OS handler. appVersion is the build-stamped
 * Mill version minMillVersion enforcement compares against.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composition$0 from "../../domain/composition/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMarketplaceSource adds one source and reads its index once, so a
 * wrong address is refused while the user is still looking at the
 * field rather than silently listing nothing later.
 */
export function AddMarketplaceSource(input: string): $CancellablePromise<$models.MarketplaceSource> {
    return $Call.ByID(2765695395, input);
}

/**
 * AssetMiddleware serves GET /plugins/<id>/<file> from the scanned
 * plugins directory (built-in plugins serve from the embedded bundle
 * behind it -- the same shadowing rule resolvePlugin applies) and
 * passes every other request through.
 */
export function AssetMiddleware(): $CancellablePromise<any> {
    return $Call.ByID(3587145368);
}

/**
 * BrowseMarketplaces lists every cached index's entries plus Mill's
 * own bundled examples, sorted by marketplace then name. Reads only
 * what is already on disk: opening Browse never fetches.
 */
export function BrowseMarketplaces(): $CancellablePromise<$models.BrowseEntry[] | null> {
    return $Call.ByID(3648359538);
}

/**
 * Captures lists every runnable plugin's declared captures, by plugin
 * then capture id.
 */
export function Captures(): $CancellablePromise<$models.PluginCapture[] | null> {
    return $Call.ByID(3991103051);
}

/**
 * CheckForUpdates refreshes every source, then resolves the latest
 * version for each installed extension that carries an install
 * receipt. Built-ins and hand-copied folders have no source to ask.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateCheck> {
    return $Call.ByID(2916006759);
}

/**
 * ContentHashOf answers the current hash of an installed plugin by id
 * ("" for a built-in or an unreadable folder) -- the run policy's
 * comparison input.
 */
export function ContentHashOf(id: string): $CancellablePromise<string> {
    return $Call.ByID(3013757580, id);
}

/**
 * ContributionKindsFor answers one installed plugin's filled families,
 * so the list can filter by them without re-deriving the rule.
 */
export function ContributionKindsFor(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1699212088, id);
}

/**
 * ContributionVocabulary is the bound form of ContributionKindNames.
 */
export function ContributionVocabulary(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2126103322);
}

/**
 * ConvertHTMLToMarkdown is the plugin SDK's convert door (goal 0282):
 * the same HTML-to-Markdown conversion every workflow convert step and
 * paste already uses, offered to a plugin as a pure transform. No
 * capability gates it -- it reaches nothing outside its own input --
 * and no plugin id is taken for the same reason.
 */
export function ConvertHTMLToMarkdown(html: string): $CancellablePromise<string> {
    return $Call.ByID(3842719554, html);
}

/**
 * ExportPluginAudit assembles the document and returns it as JSON text
 * (the frontend saves it through the same download door every other
 * export uses).
 */
export function ExportPluginAudit(): $CancellablePromise<string> {
    return $Call.ByID(233730988);
}

/**
 * FetchForPlugin performs one guarded fetch. Refusals that need no
 * rule -- undeclared capability, undeclared host, undeclared method,
 * a non-http(s) URL -- happen BEFORE the guardrail is consulted.
 */
export function FetchForPlugin(pluginID: string, req: $models.PluginFetchRequest): $CancellablePromise<$models.PluginFetchResult> {
    return $Call.ByID(1434947460, pluginID, req);
}

/**
 * InstallFromLink installs from whatever the user pasted: a
 * repository, an archive address, or a folder on this Mac.
 */
export function InstallFromLink(input: string): $CancellablePromise<$models.InstallRecord> {
    return $Call.ByID(2627079723, input);
}

/**
 * InstallFromMarketplace installs one index entry.
 */
export function InstallFromMarketplace(marketplace: string, id: string): $CancellablePromise<$models.InstallRecord> {
    return $Call.ByID(4085175482, marketplace, id);
}

/**
 * ListDirForPlugin lists dir for pluginID under the "list-files"
 * capability.
 */
export function ListDirForPlugin(pluginID: string, dir: string): $CancellablePromise<$models.PluginListDirResult> {
    return $Call.ByID(3623751117, pluginID, dir);
}

/**
 * ListMarketplaceSources answers the sources the user added, oldest
 * first. Mill's own bundled examples are not one of them -- they need
 * no source and cannot be removed.
 */
export function ListMarketplaceSources(): $CancellablePromise<$models.MarketplaceSource[] | null> {
    return $Call.ByID(416375847);
}

/**
 * ListPlugins scans the plugins directory fresh on every call (the
 * Extensions page's Rescan is just another call) and returns every
 * plugin folder with its manifest -- valid ones ready to load,
 * invalid ones carrying their human-readable Error.
 */
export function ListPlugins(): $CancellablePromise<$models.PluginInfo[] | null> {
    return $Call.ByID(1757683504);
}

/**
 * ListUpdates answers the last check as it was recorded -- never a
 * fetch.
 */
export function ListUpdates(): $CancellablePromise<$models.UpdateCheck> {
    return $Call.ByID(3557701958);
}

/**
 * PluginsDir returns the directory plugins are installed into --
 * the Extensions page's install story shows and reveals it. The
 * directory is created on first ask so "open the folder" never lands
 * on a missing path.
 */
export function PluginsDir(): $CancellablePromise<string> {
    return $Call.ByID(1345088799);
}

/**
 * PreviewInstall answers the prompt's contents for a marketplace
 * entry. It reads only the cached index -- previewing never downloads.
 */
export function PreviewInstall(marketplace: string, id: string): $CancellablePromise<$models.InstallPreview> {
    return $Call.ByID(611162871, marketplace, id);
}

/**
 * PreviewInstalled answers the same "what it can do" list for a plugin
 * already on disk -- the Verification tab shows exactly what the
 * install prompt showed.
 */
export function PreviewInstalled(id: string): $CancellablePromise<$models.InstallPreview> {
    return $Call.ByID(3921789238, id);
}

/**
 * PreviewUpdate answers the install prompt's contents for an update:
 * what the newer version can do, and the tier applying it would earn.
 * Reads only what is cached -- previewing never downloads.
 */
export function PreviewUpdate(id: string): $CancellablePromise<$models.InstallPreview> {
    return $Call.ByID(353136909, id);
}

/**
 * ReadMarketplaceDoc answers the overview a Browse row shows before
 * installing. Only the bundled examples can answer it without a
 * download; every other entry falls back to its index description.
 */
export function ReadMarketplaceDoc(marketplace: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(2684134419, marketplace, id);
}

/**
 * ReadPluginDoc returns an installed plugin's overview or changelog,
 * or "" when it ships neither -- an absent document is a normal state
 * the tab states in words, never an error.
 */
export function ReadPluginDoc(id: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(947921979, id, name);
}

/**
 * RefreshMarketplaceSources re-reads every source's index. A source
 * that cannot be read keeps the index it had, and its reason is
 * returned -- one unreachable host never empties the whole tab.
 */
export function RefreshMarketplaceSources(): $CancellablePromise<string[] | null> {
    return $Call.ByID(946746504);
}

/**
 * RemoveMarketplaceSource drops one source and its cached index.
 * Extensions already installed from it stay installed.
 */
export function RemoveMarketplaceSource(name: string): $CancellablePromise<void> {
    return $Call.ByID(1307149838, name);
}

/**
 * RequestGuardedAction is the plugin plane's one door to a primitive
 * the plugin does not hold (docs/adr/0047 §2). The manifest must
 * DECLARE the capability (an undeclared kind is refused here, before
 * any rule runs); a declared one is evaluated per-action by the
 * guardrail rule core -- allow/deny resolve immediately, ask parks for
 * a human and blocks this call until resolved (the same park the MCP
 * write plane uses). On approval Mill performs the action itself.
 */
export function RequestGuardedAction(pluginID: string, kind: string, attributes: { [_ in string]?: string } | null, description: string): $CancellablePromise<$models.GuardedActionDecision> {
    return $Call.ByID(2237721377, pluginID, kind, attributes, description);
}

/**
 * ResolveMCPServer answers one declared server as a Configure entity's
 * fields. A secretRef env entry reads the setting the user picked in
 * the extension's Settings tab; an unpicked one refuses, naming the
 * setting, rather than creating an entity that would fail at spawn.
 */
export function ResolveMCPServer(pluginID: string, serverID: string): $CancellablePromise<$models.MCPServerConfig> {
    return $Call.ByID(1716232451, pluginID, serverID);
}

/**
 * RevealPluginsDir opens the plugins directory in the OS file manager.
 */
export function RevealPluginsDir(): $CancellablePromise<void> {
    return $Call.ByID(4165393810);
}

/**
 * SecretSourceKinds lists every runnable installed plugin's declared
 * secret sources, sorted by label -- what the Kind picker offers after
 * the built-in kinds. A plugin that may not run, or whose manifest is
 * broken, contributes nothing.
 */
export function SecretSourceKinds(): $CancellablePromise<$models.SecretSourceKindInfo[] | null> {
    return $Call.ByID(3945528212);
}

/**
 * SignedOK is the run policy's question: with no policy every plugin
 * passes; with one, only a verified signature does.
 */
export function SignedOK(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1767199442, id);
}

/**
 * SigningPolicyActive reports whether any key is pinned.
 */
export function SigningPolicyActive(): $CancellablePromise<boolean> {
    return $Call.ByID(1203437115);
}

/**
 * StepNodeTypes synthesizes every runnable plugin's declared steps as
 * external node types -- the provider composition reads through
 * SetExternalNodeTypeLookup. A plugin whose steps.js fails to load
 * contributes nothing (its Extensions row states the load error via
 * StepPackProblem).
 */
export function StepNodeTypes(): $CancellablePromise<composition$0.ExternalNodeType[] | null> {
    return $Call.ByID(3703519807);
}

/**
 * StepPackProblem reports why a plugin's declared steps are not
 * available ("" when they are): the Extensions row's honest line.
 */
export function StepPackProblem(id: string): $CancellablePromise<string> {
    return $Call.ByID(3840929602, id);
}

/**
 * UpdatePlugin applies one recorded candidate through the same install
 * door the extension first came through, then drops it from the list.
 */
export function UpdatePlugin(id: string): $CancellablePromise<$models.InstallRecord> {
    return $Call.ByID(1395208446, id);
}

/**
 * VersionOf answers an installed plugin's manifest version ("" when
 * unknown) -- recorded beside the hash in the lock.
 */
export function VersionOf(id: string): $CancellablePromise<string> {
    return $Call.ByID(1443551781, id);
}

/**
 * WireContentWrites installs the writer (composition root only).
 */
export function WireContentWrites(w: $models.ContentWriter): $CancellablePromise<void> {
    return $Call.ByID(794793522, w);
}

/**
 * WriteContentForPlugin performs one guarded content write. Refusals
 * that need no rule -- undeclared capability, unknown op, a malformed
 * ask -- happen BEFORE the guardrail is consulted.
 */
export function WriteContentForPlugin(pluginID: string, req: $models.PluginContentWrite): $CancellablePromise<$models.PluginContentWriteResult> {
    return $Call.ByID(3781653108, pluginID, req);
}
