// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService is Wails-bound. openURL is injected so tests never
 * shell out to the real OS handler. appVersion is the build-stamped
 * Mill version minMillVersion enforcement compares against.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composition$0 from "../../domain/composition/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssetMiddleware serves GET /plugins/<id>/<file> from the scanned
 * plugins directory (built-in plugins serve from the embedded bundle
 * behind it -- the same shadowing rule resolvePlugin applies) and
 * passes every other request through.
 */
export function AssetMiddleware(): $CancellablePromise<any> {
    return $Call.ByID(3587145368);
}

/**
 * ContentHashOf answers the current hash of an installed plugin by id
 * ("" for a built-in or an unreadable folder) -- the run policy's
 * comparison input.
 */
export function ContentHashOf(id: string): $CancellablePromise<string> {
    return $Call.ByID(3013757580, id);
}

/**
 * ConvertHTMLToMarkdown is the plugin SDK's convert door (goal 0282):
 * the same HTML-to-Markdown conversion every workflow convert step and
 * paste already uses, offered to a plugin as a pure transform. No
 * capability gates it -- it reaches nothing outside its own input --
 * and no plugin id is taken for the same reason.
 */
export function ConvertHTMLToMarkdown(html: string): $CancellablePromise<string> {
    return $Call.ByID(3842719554, html);
}

/**
 * ExportPluginAudit assembles the document and returns it as JSON text
 * (the frontend saves it through the same download door every other
 * export uses).
 */
export function ExportPluginAudit(): $CancellablePromise<string> {
    return $Call.ByID(233730988);
}

/**
 * FetchForPlugin performs one guarded fetch. Refusals that need no
 * rule -- undeclared capability, undeclared host, undeclared method,
 * a non-http(s) URL -- happen BEFORE the guardrail is consulted.
 */
export function FetchForPlugin(pluginID: string, req: $models.PluginFetchRequest): $CancellablePromise<$models.PluginFetchResult> {
    return $Call.ByID(1434947460, pluginID, req);
}

/**
 * ListPlugins scans the plugins directory fresh on every call (the
 * Extensions page's Rescan is just another call) and returns every
 * plugin folder with its manifest -- valid ones ready to load,
 * invalid ones carrying their human-readable Error.
 */
export function ListPlugins(): $CancellablePromise<$models.PluginInfo[] | null> {
    return $Call.ByID(1757683504);
}

/**
 * PluginsDir returns the directory plugins are installed into --
 * the Extensions page's install story shows and reveals it. The
 * directory is created on first ask so "open the folder" never lands
 * on a missing path.
 */
export function PluginsDir(): $CancellablePromise<string> {
    return $Call.ByID(1345088799);
}

/**
 * RequestGuardedAction is the plugin plane's one door to a primitive
 * the plugin does not hold (docs/adr/0047 §2). The manifest must
 * DECLARE the capability (an undeclared kind is refused here, before
 * any rule runs); a declared one is evaluated per-action by the
 * guardrail rule core -- allow/deny resolve immediately, ask parks for
 * a human and blocks this call until resolved (the same park the MCP
 * write plane uses). On approval Mill performs the action itself.
 */
export function RequestGuardedAction(pluginID: string, kind: string, attributes: { [_ in string]?: string } | null, description: string): $CancellablePromise<$models.GuardedActionDecision> {
    return $Call.ByID(2237721377, pluginID, kind, attributes, description);
}

/**
 * RevealPluginsDir opens the plugins directory in the OS file manager.
 */
export function RevealPluginsDir(): $CancellablePromise<void> {
    return $Call.ByID(4165393810);
}

/**
 * SignedOK is the run policy's question: with no policy every plugin
 * passes; with one, only a verified signature does.
 */
export function SignedOK(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1767199442, id);
}

/**
 * SigningPolicyActive reports whether any key is pinned.
 */
export function SigningPolicyActive(): $CancellablePromise<boolean> {
    return $Call.ByID(1203437115);
}

/**
 * StepNodeTypes synthesizes every runnable plugin's declared steps as
 * external node types -- the provider composition reads through
 * SetExternalNodeTypeLookup. A plugin whose steps.js fails to load
 * contributes nothing (its Extensions row states the load error via
 * StepPackProblem).
 */
export function StepNodeTypes(): $CancellablePromise<composition$0.ExternalNodeType[] | null> {
    return $Call.ByID(3703519807);
}

/**
 * StepPackProblem reports why a plugin's declared steps are not
 * available ("" when they are): the Extensions row's honest line.
 */
export function StepPackProblem(id: string): $CancellablePromise<string> {
    return $Call.ByID(3840929602, id);
}

/**
 * VersionOf answers an installed plugin's manifest version ("" when
 * unknown) -- recorded beside the hash in the lock.
 */
export function VersionOf(id: string): $CancellablePromise<string> {
    return $Call.ByID(1443551781, id);
}

/**
 * WireContentWrites installs the writer (composition root only).
 */
export function WireContentWrites(w: $models.ContentWriter): $CancellablePromise<void> {
    return $Call.ByID(794793522, w);
}

/**
 * WriteContentForPlugin performs one guarded content write. Refusals
 * that need no rule -- undeclared capability, unknown op, a malformed
 * ask -- happen BEFORE the guardrail is consulted.
 */
export function WriteContentForPlugin(pluginID: string, req: $models.PluginContentWrite): $CancellablePromise<$models.PluginContentWriteResult> {
    return $Call.ByID(3781653108, pluginID, req);
}
