package contract

import (
	"embed"
	"encoding/json"
	"fmt"

	"github.com/alicoding/mill/internal/domain/composition"
)

// CommittedDocument embeds the generated, committed root contract
// document (goal 0052 item 6) -- the whole agent-facing surface in one
// file, for the transport form an MCP-denied environment needs (a
// far-side agent gets one file over the clipboard/file bridge and needs
// nothing else). Regenerated by `go generate ./internal/contract`
// alongside the per-family schemas; drift-checked the same way
// (document_test.go).
//
//go:embed contract.json
var CommittedDocument embed.FS

// ImportContract states goal 0052 item 6's import/update rule as data,
// not prose (ADR-0036 decision 3) -- an external agent reads this
// instead of re-deriving the rule from the schemas alone.
type ImportContract struct {
	IDAbsent                   string   `json:"idAbsent"`
	IDPresentUnknownLocally    string   `json:"idPresentUnknownLocally"`
	IDPresentKnownLocally      string   `json:"idPresentKnownLocally"`
	ReadersIgnoreUnknownFields bool     `json:"readersIgnoreUnknownFields"`
	SupportedSchemas           []string `json:"supportedSchemas"`
}

// Document is the root contract document's committed, static half:
// every registered family's schema, the full step-type catalog, and
// the import contract. It deliberately OMITS the manifest (app
// version/commit/mode) -- ADR-0036 decision 4 requires the manifest
// stay a live sibling injected only at serve/export time
// (ServedDocument below), never baked into a byte that would then
// churn on every app upgrade regardless of whether the contract itself
// changed.
type Document struct {
	Schemas   map[string]json.RawMessage `json:"schemas"`
	StepTypes []composition.NodeType     `json:"stepTypes"`
	// NodeTypes is the legacy alias of StepTypes, kept forever
	// (ADR-0036's within-major rule is additive-only, a key is never
	// removed) -- same slice, same bytes, so an existing consumer
	// reading "nodeTypes" never breaks.
	NodeTypes []composition.NodeType `json:"nodeTypes"`
	Import    ImportContract         `json:"import"`
}

// ServedDocument is what mill://contract and the UI's Export contract
// action actually return: Document plus the live Manifest. Never
// committed to disk -- assembled fresh from CommittedDocument at
// request time (Served, below).
type ServedDocument struct {
	Document
	Manifest Manifest `json:"manifest"`
}

// buildImportContract derives ImportContract from the same registry
// GenerateAll/SchemaID already read, so the supported-schema list can
// never list a family the schemas themselves don't cover.
func buildImportContract() ImportContract {
	families := Families()
	supported := make([]string, 0, len(families))
	for _, f := range families {
		supported = append(supported, SchemaID(f))
	}
	return ImportContract{
		IDAbsent:                   "create a fresh local id",
		IDPresentUnknownLocally:    "create, preserving the given id",
		IDPresentKnownLocally:      "update in place through the existing chokepoint",
		ReadersIgnoreUnknownFields: true,
		SupportedSchemas:           supported,
	}
}

// GenerateDocument reflects the current registry (every family's
// schema via GenerateAll, plus composition.NodeTypes() -- the exact
// function list_step_types itself calls, so the document's catalog and
// the live MCP tool's catalog can never carry two independent
// implementations) into the committed document's bytes. Deterministic
// for the same reason GenerateAll is: sorted family keys, a map with
// string keys (encoding/json sorts those too), and NodeTypes()'s own
// stable sort. StepTypes and NodeTypes are always the same slice, so
// the alias can never drift from its primary.
func GenerateDocument() ([]byte, error) {
	schemas, err := GenerateAll()
	if err != nil {
		return nil, err
	}
	schemaMap := make(map[string]json.RawMessage, len(schemas))
	for family, data := range schemas {
		schemaMap[family] = json.RawMessage(data)
	}
	stepTypes := composition.NodeTypes()
	doc := Document{
		Schemas:   schemaMap,
		StepTypes: stepTypes,
		NodeTypes: stepTypes,
		Import:    buildImportContract(),
	}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal root contract document: %w", err)
	}
	return append(data, '\n'), nil
}

// Served decodes the committed document and attaches manifest -- the
// one function mill://contract and the UI's Export contract action
// both call, so the served/exported form can never drift from what
// TestRootContractDocument_MatchCommitted (document_test.go) already
// proved matches the registry.
func Served(manifest Manifest) ([]byte, error) {
	raw, err := CommittedDocument.ReadFile("contract.json")
	if err != nil {
		return nil, fmt.Errorf("contract: read committed document: %w", err)
	}
	var doc Document
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("contract: decode committed document: %w", err)
	}
	served := ServedDocument{Document: doc, Manifest: manifest}
	data, err := json.MarshalIndent(served, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal served contract document: %w", err)
	}
	return append(data, '\n'), nil
}
