// Package clipboard wraps macOS clipboard I/O behind Mill's own names, so
// swapping the underlying mechanism (osascript today) never touches domain
// logic — the CLAUDE.md ports/adapters rule applied to this one commodity
// concern.
//
// Every caller reaches the clipboard through Port, never through Host
// directly: New selects Host (the real pasteboard, host.go) or Memory
// (an in-memory stand-in, memory.go) by the MILL_CLIPBOARD environment
// variable, defaulting to Memory inside a `go test` binary — goal 0356,
// closing a class of bug where a seeded workflow test's own
// apply-clipboard-write step landed on the machine running the test,
// not a fixture. A `go test` binary that deliberately needs the real
// pasteboard (this package's own round-trip tests) opts back in with
// MILL_CLIPBOARD_HOST_OK=1; see NewHost's own doc comment.
package clipboard

import (
	"os"
	"sync"
	"testing"
	"time"
)

// Port is every clipboard operation a service or a composition node
// depends on — Host and Memory both implement it in full, so a caller
// never knows or cares which one it holds.
type Port interface {
	ReadText() (string, error)
	WriteText(text string) error
	ReadHTML() (string, error)
	WriteHTML(html string) error
	WritePNG(data []byte) error
	Info() (string, error)
	Types() ([]string, error)
	ReadFileURLs() ([]string, error)
	IsConcealed() (bool, error)
	// ConsumeSelfWrite reports whether text matches this Port's own most
	// recent WriteText call, clearing the marker on a match — goal
	// 0234's self-echo guard; see selfWriteTracker's own doc comment.
	ConsumeSelfWrite(text string) bool
	// WatchChanges polls the clipboard's plain-text flavor on the given
	// interval and calls fn with the new text whenever it differs from
	// the last-seen value. Returns a stop func.
	WatchChanges(interval time.Duration, fn func(text string)) (stop func())
}

var (
	hostOnce sync.Once
	hostInst *Host

	memOnce sync.Once
	memInst *Memory
)

// New returns the Port the current process should use: MILL_CLIPBOARD
// picks explicitly ("host" or "memory"); left unset, a `go test` binary
// gets Memory (testing.Testing() is a link-time flag, true from the
// first line any test binary runs, including a package-level var
// initializer) and every other binary — the real app, or an e2e spec's
// spawned bin/mill-server, which is a normal build, not a test binary —
// gets Host. e2e servers must set MILL_CLIPBOARD=memory explicitly
// (frontend/e2e/fixtures/server.ts), since testing.Testing() can't see
// them. New always returns the SAME instance within one process: every
// caller must observe the same clipboard, exactly as every caller of
// the real Host already shares the one OS-wide pasteboard.
func New() Port {
	switch os.Getenv("MILL_CLIPBOARD") {
	case "memory":
		return ForTests()
	case "host":
		return sharedHost()
	default:
		if testing.Testing() {
			return ForTests()
		}
		return sharedHost()
	}
}

// ForTests returns the process-wide in-memory Port, regardless of
// MILL_CLIPBOARD — the explicit seam for a test (or a future
// constructor taking Port by injection) that wants Memory without
// depending on New's own environment-driven default.
func ForTests() Port {
	memOnce.Do(func() { memInst = NewMemory() })
	return memInst
}

func sharedHost() Port {
	hostOnce.Do(func() { hostInst = NewHost() })
	return hostInst
}

// concealedTypes are the nspasteboard.org convention's own markers
// (https://nspasteboard.org) a password manager or transient-content
// source sets on the pasteboard to declare "don't record this in a
// clipboard history" — the same three types Maccy itself checks
// (goal 0234's own research). Shared between Host.IsConcealed and
// Memory.IsConcealed.
var concealedTypes = []string{
	"org.nspasteboard.ConcealedType",
	"org.nspasteboard.TransientType",
	"org.nspasteboard.AutoGeneratedType",
}

// isConcealedIn reports whether types carries one of concealedTypes'
// UTIs — the pure check both Host.IsConcealed (against the real
// pasteboard's Types()) and Memory.IsConcealed (against its own
// in-memory type set) apply identically.
func isConcealedIn(types []string) bool {
	for _, t := range types {
		for _, c := range concealedTypes {
			if t == c {
				return true
			}
		}
	}
	return false
}

// selfWriteTracker is WriteText's self-echo marker, embedded in both
// Host and Memory so each Port implementation tracks its OWN most
// recent write independently — goal 0234: a clipboard-history poll
// cycle immediately following Mill's own write must not re-capture that
// write as a new history entry.
type selfWriteTracker struct {
	mu   sync.Mutex
	text string
}

func (t *selfWriteTracker) markSelfWrite(text string) {
	t.mu.Lock()
	t.text = text
	t.mu.Unlock()
}

// ConsumeSelfWrite reports whether text matches the tracker's marker,
// clearing it on a match. One-shot by design: only the poll cycle
// immediately following a self-write is treated as an echo — a later,
// separate user copy of identical text is recorded normally rather than
// permanently blacklisted.
func (t *selfWriteTracker) ConsumeSelfWrite(text string) bool {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.text != "" && t.text == text {
		t.text = ""
		return true
	}
	return false
}

// watchChanges is WatchChanges' shared poll loop, parameterized by
// readText so Host (real pbpaste) and Memory (its own stored text) run
// the identical polling/dedup/empty-transition logic — goal 0356: the
// clipboard-history trigger must see the same watcher behavior
// regardless of which Port is selected. Build, not adopt — confirmed no
// clipboard-changed event exists via osascript (docs/SPEC.md §3.4), so
// this is the same poll-loop shape every clipboard manager uses under
// the hood (goal 0234's own research: changeCount polling is the
// converged mechanism, and unlike a content read it triggers no macOS
// pasteboard-privacy prompt on any shipping release). Plain text, not
// HTML: the HTML flavor is frequently absent (e.g. copying a filename
// or plain text produces none), so watching it would miss most real
// clipboard activity — text is the one flavor almost everything
// copyable sets.
func watchChanges(interval time.Duration, fn func(text string), readText func() (string, error)) (stop func()) {
	done := make(chan struct{})
	go func() {
		last, _ := readText() // baseline; ignore error (nothing on clipboard yet)
		ticker := time.NewTicker(interval)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				last = pollOnce(readText, last, fn)
			case <-done:
				return
			}
		}
	}()
	return func() { close(done) }
}

// pollOnce reads the current text via readText and, if it differs from
// last, calls fn -- except for a transition TO empty, which never fires:
// pbcopy's own clear-then-set exposes a transient empty pasteboard to a
// concurrent poll (measured live: baseline -> "" -> new value at a 20ms
// interval), and a non-text clipboard (an image copy) also reads as
// empty -- neither is a text change worth capturing. Returns the value
// the next poll should compare against. A read error leaves last
// unchanged, retried on the next tick.
func pollOnce(readText func() (string, error), last string, fn func(string)) string {
	text, err := readText()
	if err != nil || text == last {
		return last
	}
	if text != "" {
		fn(text)
	}
	return text
}
