// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Event is what a producer hands to Publish -- Record's input-facing
 * counterpart, the same input/full-record split MCPWriteRequest/
 * MCPWriteRecord already establish (millmcpservice_approval.go).
 */
export interface Event {
    "type": string;
    "title": string;
    "body": string;
    "dedupeKey": string;
    "sourceRef"?: string;

    /**
     * Focused is the producer's own presence reading for the surface
     * that originated this event (a frontend's document.hasFocus()),
     * threaded through rather than read here since only the caller
     * knows it. The zero value (false) fails toward "away" -- a
     * backend-originated event with no window to read focus from (a
     * run finishing unattended) is exactly the case a channel's
     * presence gate should err toward delivering for, not suppressing.
     */
    "focused": boolean;
}

/**
 * Record is one durable notification, keyed by DedupeKey so publishing
 * the same logical event twice (a restart, two independent producers
 * for the same underlying item) resolves to the same Record rather than
 * a duplicate. Field names follow CloudEvents' own id/type/time/data
 * shape (id, type, time here as CreatedAt, data as Title+Body) --
 * naming alignment only, the CloudEvents SDK itself is not imported
 * (docs/goals/0171's own commodity verdict: adopt the envelope shape,
 * defer the SDK).
 */
export interface Record {
    "id": string;
    "type": string;
    "title": string;
    "body": string;
    "dedupeKey": string;

    /**
     * SourceRef names the underlying item this notification is about
     * (a run ID, an MCP write ID, an update version) -- what a click
     * would navigate to, kept separate from DedupeKey since a future
     * producer's dedupe key and navigation target could genuinely
     * differ even though today every producer sets them equal.
     */
    "sourceRef"?: string;
    "createdAt": string;
    "readAt"?: string | null;
    "expiresAt"?: string | null;

    /**
     * DeliveredChannels names every Channel that has already run
     * Deliver for this Record -- the one dedupe mechanism (goal 0171),
     * persisted alongside the record itself so it survives a reload
     * instead of resetting the way two separate in-memory Sets used to.
     * A channel appears here at most once; a Publish call for an
     * already-published DedupeKey re-attempts only the channels still
     * missing from this list, so a second producer of the same logical
     * event (e.g. a second browser tab) still gets ITS OWN channel
     * delivered without re-delivering one that already fired.
     */
    "deliveredChannels"?: string[] | null;
}
