// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceInfo is Settings > Remote access's read model for one paired
 * device -- deliberately excludes Salt/Hash, which never leave the
 * server.
 */
export interface DeviceInfo {
    "id": string;
    "label": string;
    "createdAt": string;
    "lastSeenAt": string;
}

/**
 * PairingCodeInfo is what Settings > Remote access renders after
 * "Pair a device" is pressed.
 */
export interface PairingCodeInfo {
    "code": string;
    "expiresAt": string;
}
