// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RemoteAuthService is the Wails-bound owner of Mill's remote-access auth gate:
 * the AssetServer middleware (remoteauthservice_middleware.go), the
 * pairing-code lifecycle (remoteauthservice_pairing.go), the paired-
 * device store (remoteauthservice_devices.go), and the per-source
 * rate limiter (remoteauthservice_ratelimit.go).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GeneratePairingCode mints a new single-use enrollment code on
 * demand, replacing any code still outstanding (only one is ever
 * live at a time). Held in memory only -- see devicesSettingsKey's
 * doc comment for why nothing here touches the settings store. The
 * deliberate log line lets a headless/server-mode run (no Settings UI
 * to show the code in) still complete pairing from a terminal, but
 * only while the instance is unpaired -- once any device is paired,
 * the code is never logged again, no matter which caller generated
 * it (docs/goals/0132-remote-access.md SLICE 1b: "never log the code
 * once paired"). This is the RPC path (Settings > Remote access,
 * loopback-only): a desktop owner pairing a second device already
 * sees the code on screen, so logging it too would be redundant.
 * resendPairingCode below is the OTHER caller, unconditional on
 * purpose.
 */
export function GeneratePairingCode(): $CancellablePromise<$models.PairingCodeInfo> {
    return $Call.ByID(3056783632);
}

/**
 * ListDevices returns every currently paired device, oldest first, so
 * Settings renders a stable order across renders.
 */
export function ListDevices(): $CancellablePromise<$models.DeviceInfo[] | null> {
    return $Call.ByID(1365707411);
}

/**
 * RenameDevice updates a paired device's label -- a device is
 * pre-filled with a self-announced label at pairing time
 * (deviceLabelFor) and renameable afterwards. Empty (after trimming)
 * is rejected rather than silently keeping the old label, so the
 * caller gets an explicit signal a blank name didn't take.
 */
export function RenameDevice(id: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(1715703988, id, label);
}

/**
 * RevokeDevice deletes id's paired-device record. Any request still
 * carrying that device's cookie is rejected on its very next request
 * -- validateToken (below) only ever matches against the live list.
 * The device's phone-channel topic dies with it: a new subscribe
 * attempt gets the same 404 as any never-paired topic (recordTopicSeen
 * only matches the live list too), and forceCloseTopic drops any
 * subscribe connection already open right now, rather than waiting for
 * it to eventually reconnect into a 404.
 */
export function RevokeDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(1929952408, id);
}

/**
 * SeedTestDevice mints a paired device directly, bypassing the HTTP
 * pairing flow entirely -- e2e-only (see testAllowDeviceSeedEnv
 * above), never reachable in a real deployment.
 * baseURL is accepted (rather than always "") so e2e coverage can seed
 * a device whose SubscribeURL is already populated -- a real pairing
 * round trip sets it from the pairing request itself, which this seam
 * exists specifically to bypass.
 */
export function SeedTestDevice(label: string, baseURL: string): $CancellablePromise<$models.DeviceInfo> {
    return $Call.ByID(341728691, label, baseURL);
}
