// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";

/**
 * AIProvider is one reusable, named AI endpoint connection. Carries no
 * secret VALUE of its own -- same "the secret itself never lives on
 * the domain value" rule httprequest.HTTPRequest/ADR-0007 already
 * established. A BYO endpoint's API key (or Anthropic's x-api-key)
 * lives in the secret store and this entity names it (KeyRef, goal
 * 0306); empty for a local endpoint that needs no credential at all.
 */
export interface AIProvider {
    "ID": string;
    "Label": string;
    "Kind": Kind;
    "BaseURL": string;
    "Model": string;

    /**
     * KeyRef names this endpoint's API key in the secret store (goal
     * 0306) -- a reference (internal/domain/vaultref), never a value.
     * Empty means the endpoint needs no credential, which is the whole
     * configuration for a local one.
     */
    "KeyRef": string;

    /**
     * BuiltIn marks a seeded example AIProvider (BuiltIn() below) --
     * purely informational, same as mcpserver.MCPServer.BuiltIn/
     * decision.Decision.BuiltIn/list.List.BuiltIn: drives a "built-in"
     * badge only, never gates Edit/Delete.
     */
    "BuiltIn": boolean;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (SPEC.md
     * §3.2.2's reserved-column pattern), stamped server-side at every
     * persisted mutation (ConfigureService), never trusted from the
     * wire. Zero value means pre-timestamp data -- migration-free.
     */
    "CreatedAt": string;
    "UpdatedAt": string;

    /**
     * Seed is this provider's seed provenance (docs/goals/0037) -- zero
     * value means "not of seed origin," migration-free. See
     * composition.Workflow.Seed's doc comment for the full reasoning.
     */
    "Seed": seedorigin$0.Origin;
}

/**
 * Kind is a provider's wire-protocol family -- a closed, typed choice
 * (execenv.Shell's own "typed choice, not free text" precedent), each
 * value dispatched to its own adapter in internal/adapters/aiclient.
 * Deliberately just two: docs/goals/0031-ai-node-family.md's own
 * research verdict is that every real BYO/local endpoint (Ollama, LM
 * Studio, vLLM, OpenAI itself, Groq, ...) speaks the OpenAI-compatible
 * /v1/chat/completions shape, and Anthropic's Messages API is the one
 * documented exception (its own docs disqualify the OpenAI compat shim
 * for production) -- not an extensible plugin registry, since no third
 * wire shape is known to exist today (CLAUDE.md's "don't build for a
 * decision that doesn't exist yet").
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindOpenAICompat = "openai-compatible",
    KindAnthropic = "anthropic",
};
