// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ObjectRef names one live board object that references a Configure
 * entity -- BoardID is the object's own ParentID (the canvas/board it
 * is placed on, per BoardObject's own doc comment); ObjectID is the
 * object itself. Label is the object's own display name (its Payload
 * title, falling back to its kind) for an error/listing that has to
 * name it, the same way WorkflowsReferencing already names workflows
 * by Label rather than id.
 */
export interface ObjectRef {
    "BoardID": string;
    "ObjectID": string;
    "Label": string;
}

/**
 * Refs is the combined answer to "what still references this Configure
 * entity" -- board objects (Atlas) and workflow nodes (compositionsvc),
 * the two sources refIntegrityError and Configure's own usage
 * indicator both read (docs/goals/0392 Decision 3, extending ADR-0040
 * decision 3's workflow-only reverse lookup).
 */
export interface Refs {
    "Boards": ObjectRef[] | null;
    "Workflows": string[] | null;
}
