// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Effect is a rule's (or the final evaluation's) verdict. Ordered by
 * precedence: deny always beats ask, ask always beats allow, no matter
 * which scope a rule attaches at (ADR-0019's categorical deny-first
 * resolution, modeled on Claude Code's, not Kong's specificity-wins).
 */
export enum Effect {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EffectAllow = "allow",
    EffectAsk = "ask",
    EffectDeny = "deny",
};

/**
 * EffectClass is a NodeType's declared side-effect classification
 * (docs/adr/0022's purity model -- also what ADR-0021's deferred shadow
 * evaluation was blocked on).
 */
export enum EffectClass {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ClassNone: no I/O at all (pure transforms, in-memory lookups).
     */
    ClassNone = "none",

    /**
     * ClassRead: reads external state, mutates nothing.
     */
    ClassRead = "read",

    /**
     * ClassLocal: mutates local, user-visible state (clipboard write) --
     * the native baseline a person already performs by hand, so it
     * defaults to allow per §1's not-harder-than-baseline hard lock.
     */
    ClassLocal = "local",

    /**
     * ClassExternal: calls out of the machine or into another process --
     * where §8's fail-safe default bites.
     */
    ClassExternal = "external",
};

/**
 * Rule is one guardrail rule. Scope is expressed by which fields are
 * set: every non-empty scope field must match the step being evaluated
 * (docs/adr/0019's three scopes are all expressible -- NodeTypeID alone
 * is a node-type rule, RequestID alone is a request/connector rule,
 * WorkflowID+NodeID is an instance rule).
 */
export interface Rule {
    "ID": string;
    "Label": string;
    "Effect": Effect;

    /**
     * Scope fields -- all non-empty ones must match.
     */
    "NodeTypeID": string;
    "RequestID": string;
    "WorkflowID": string;
    "NodeID": string;

    /**
     * Condition is an optional expr-lang boolean over the step's
     * evaluation environment (Payload/Attributes/Config). Empty means
     * the rule matches unconditionally within its scope.
     */
    "Condition": string;
}
