// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigureService is the Wails-facing layer over Configure-authored data
 * (docs/SPEC.md §3.5): HTTPRequests, Lists, and (delegated to
 * CompositionService) a workflow's Attributes schema. Mirrors
 * CompositionService's own shape -- state + persistence a stateless
 * domain package can't own, no domain logic of its own.
 * 
 * It also owns wiring composition.go's request-lookup and list-lookup
 * seams (SetHTTPRequestLookup/SetListLookup) to its own resolve*
 * methods -- composition.go doesn't (and shouldn't) import this
 * package directly, same reasoning as CompositionService's Syncer
 * interface for TriggerService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpclient$0 from "../../adapters/mcpclient/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as openapispec$0 from "../../adapters/openapispec/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aiprovider$0 from "../../domain/aiprovider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composition$0 from "../../domain/composition/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as decision$0 from "../../domain/decision/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execenv$0 from "../../domain/execenv/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httprequest$0 from "../../domain/httprequest/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as list$0 from "../../domain/list/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpserver$0 from "../../domain/mcpserver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../../domain/typedfield/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AIProviders(): $CancellablePromise<aiprovider$0.AIProvider[] | null> {
    return $Call.ByID(3861562536);
}

/**
 * AddListRow appends a new, Active row to a List, minting its ID here
 * (row-ID generation stays a service-layer concern, same as List IDs
 * themselves via seeding.NewSlugID -- internal/domain/list stays pure
 * per .claude/rules/backend.md).
 */
export function AddListRow(listID: string, values: { [_ in string]?: string } | null): $CancellablePromise<list$0.List> {
    return $Call.ByID(197919857, listID, values);
}

/**
 * CaptureShellPath returns the user's real login-shell $PATH -- the
 * ExecEnv form's "Capture from my shell" affordance (ADR-0026's
 * Amendment: determinism through materialization; the captured value
 * lands in the stored, visible, editable Env, never re-derived at run
 * time). A plain read with no side effects; the frontend decides what
 * to do with the value (upsert its PATH row).
 */
export function CaptureShellPath(): $CancellablePromise<string> {
    return $Call.ByID(759717731);
}

export function CreateAIProvider(label: string, kind: aiprovider$0.Kind, baseURL: string, model: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(427493887, label, kind, baseURL, model);
}

export function CreateDecision(label: string, category: decision$0.Category, outputs: decision$0.OutputField[] | null, webhookRequestID: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(2725151274, label, category, outputs, webhookRequestID);
}

export function CreateExecEnv(label: string, shell: execenv$0.Shell, profileMode: execenv$0.ProfileMode, dir: string, env: string[] | null): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(2549731420, label, shell, profileMode, dir, env);
}

/**
 * CreateHTTPRequest/UpdateHTTPRequest's positional-param list is
 * getting long (9 now, after ADR-0016 Phase B's method) -- a real
 * ergonomics cost (every call site needs a scripted-regex patch when a
 * field like Auth/JOSE is added), worth an
 * options-struct pass at some point, but that's a separate, bigger
 * refactor than "add a field" -- not done speculatively here.
 */
export function CreateHTTPRequest(label: string, baseURL: string, method: string, body: string, authType: httprequest$0.AuthType, headers: { [_ in string]?: string } | null, openAPISpec: string, auth: httprequest$0.AuthConfig | null, jose: httprequest$0.JOSEConfig | null, description: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(2634895949, label, baseURL, method, body, authType, headers, openAPISpec, auth, jose, description);
}

export function CreateList(label: string, description: string, columns: typedfield$0.Field[] | null): $CancellablePromise<list$0.List> {
    return $Call.ByID(1760985996, label, description, columns);
}

export function CreateMCPServer(label: string, command: string, args: string[] | null): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(1284256739, label, command, args);
}

export function Decisions(): $CancellablePromise<decision$0.Decision[] | null> {
    return $Call.ByID(3569228287);
}

/**
 * DeleteAIProvider also removes any keychain secret for id -- best-
 * effort (a delete on an id with no stored secret is a harmless no-op-
 * shaped error, not surfaced), same reasoning DeleteHTTPRequest's own
 * c.credentials.Delete call already documents.
 */
export function DeleteAIProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(2537752540, id);
}

/**
 * DeleteAIProviderSecret clears id's secret without deleting the
 * provider itself -- e.g. switching a BYO endpoint back to no
 * credential.
 */
export function DeleteAIProviderSecret(id: string): $CancellablePromise<void> {
    return $Call.ByID(2178752064, id);
}

export function DeleteDecision(id: string): $CancellablePromise<void> {
    return $Call.ByID(3396624017, id);
}

export function DeleteExecEnv(id: string): $CancellablePromise<void> {
    return $Call.ByID(2790333249, id);
}

/**
 * DeleteHTTPRequest also removes any keychain secret for id --
 * best-effort (c.credentials.Delete on an id with no stored secret, e.g.
 * an AuthNone request, is a harmless no-op-shaped error, not
 * surfaced), so a deleted request never leaves an orphaned secret
 * behind in the OS keychain.
 */
export function DeleteHTTPRequest(id: string): $CancellablePromise<void> {
    return $Call.ByID(1529049956, id);
}

/**
 * DeleteHTTPRequestJOSEPrivateKey clears id's JOSE private key without
 * touching its AuthType secret or deleting the request itself.
 */
export function DeleteHTTPRequestJOSEPrivateKey(id: string): $CancellablePromise<void> {
    return $Call.ByID(2323902085, id);
}

/**
 * DeleteHTTPRequestSecret clears id's secret without deleting the
 * request itself -- e.g. switching a request back to AuthNone.
 */
export function DeleteHTTPRequestSecret(id: string): $CancellablePromise<void> {
    return $Call.ByID(4090960168, id);
}

export function DeleteList(id: string): $CancellablePromise<void> {
    return $Call.ByID(1223896803, id);
}

export function DeleteListRow(listID: string, rowID: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(2135971241, listID, rowID);
}

export function DeleteMCPServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3847603582, id);
}

export function ExecEnvs(): $CancellablePromise<execenv$0.ExecEnv[] | null> {
    return $Call.ByID(1392956673);
}

export function ExportAIProvider(id: string): $CancellablePromise<string> {
    return $Call.ByID(677240817, id);
}

export function ExportDecision(id: string): $CancellablePromise<string> {
    return $Call.ByID(1497100540, id);
}

export function ExportExecEnv(id: string): $CancellablePromise<string> {
    return $Call.ByID(1292699062, id);
}

export function ExportHTTPRequest(id: string): $CancellablePromise<string> {
    return $Call.ByID(1052411683, id);
}

export function ExportList(id: string): $CancellablePromise<string> {
    return $Call.ByID(2193499122, id);
}

export function ExportMCPServer(id: string): $CancellablePromise<string> {
    return $Call.ByID(766088645, id);
}

/**
 * HTTPRequestOperationFields resolves one request operation's declared
 * input/output fields (ADR-0007 Phase 3) -- the data the canvas
 * Inspector's binding editor renders once a user picks an operation
 * from ListHTTPRequestOperations above. Mirrors that method's own
 * lookup/parse shape.
 */
export function HTTPRequestOperationFields(id: string, path: string, method: string): $CancellablePromise<openapispec$0.Operation> {
    return $Call.ByID(4287723439, id, path, method);
}

export function HTTPRequests(): $CancellablePromise<httprequest$0.HTTPRequest[] | null> {
    return $Call.ByID(1886035734);
}

/**
 * ImportAIProvider always creates a new AIProvider with no secret set --
 * exportedAIProvider never carries one, same as ImportMCPServer's own
 * no-credential-to-import shape.
 */
export function ImportAIProvider(jsonData: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(2109937718, jsonData);
}

export function ImportDecision(jsonData: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(4077937019, jsonData);
}

export function ImportExecEnv(jsonData: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(785482531, jsonData);
}

/**
 * ImportHTTPRequest always creates a new HTTPRequest with no secret set
 * -- exportedHTTPRequest never carries one, so the imported request
 * starts exactly like a freshly hand-authored one that hasn't had
 * SetHTTPRequestSecret called yet, same as CreateHTTPRequest's own
 * existing behavior for a request with AuthType != AuthNone.
 */
export function ImportHTTPRequest(jsonData: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(4183227914, jsonData);
}

export function ImportList(jsonData: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(2746040697, jsonData);
}

export function ImportMCPServer(jsonData: string): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(337785048, jsonData);
}

/**
 * ListHTTPRequestOperations parses id's stored OpenAPISpec and returns
 * every operation it declares -- the discoverability answer for an
 * HTTPRequest's schema, same shape as ListMCPServerTools
 * (configuremcpserver.go, §3.6): a user finds the exact path+method to
 * reference from a workflow node here, not by guessing. Returns an
 * error for a request with no OpenAPISpec set, rather than an empty
 * list, so the frontend can distinguish "nothing declared yet" from
 * "real spec, zero operations."
 */
export function ListHTTPRequestOperations(id: string): $CancellablePromise<openapispec$0.OperationRef[] | null> {
    return $Call.ByID(415197675, id);
}

/**
 * ListMCPServerTools is a live, on-demand reference lookup (connects to
 * the server, lists its tools, disconnects) -- not persisted or synced,
 * same "occasional reference lookup, not a live feed" shape HTTPRequests()/
 * Lists() themselves already have (the frontend polls them on demand,
 * nothing pushes). This is docs/SPEC.md §3.6's actual discoverability
 * answer: a user finds the exact toolName to paste into an mcp-tool-call
 * node here, not by guessing.
 */
export function ListMCPServerTools(id: string): $CancellablePromise<mcpclient$0.Tool[] | null> {
    return $Call.ByID(949169294, id);
}

export function Lists(): $CancellablePromise<list$0.List[] | null> {
    return $Call.ByID(2461513153);
}

export function MCPServers(): $CancellablePromise<mcpserver$0.MCPServer[] | null> {
    return $Call.ByID(4060206780);
}

/**
 * ResetAIProviderToSeed mirrors ResetMCPServerToSeed for AI providers.
 */
export function ResetAIProviderToSeed(id: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(2473880440, id);
}

/**
 * ResetDecisionToSeed mirrors ResetHTTPRequestToSeed for Decisions.
 */
export function ResetDecisionToSeed(id: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(3124176177, id);
}

/**
 * ResetExecEnvToSeed mirrors ResetHTTPRequestToSeed for ExecEnvs.
 */
export function ResetExecEnvToSeed(id: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(654567745, id);
}

/**
 * ResetHTTPRequestToSeed replaces id's content with the current
 * golden's and clears the Modified latch (docs/goals/0037 item 4) --
 * an explicit, on-demand act available regardless of current
 * Modified/revision state, unlike reconcile's own conditional upgrade.
 */
export function ResetHTTPRequestToSeed(id: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(3582620696, id);
}

/**
 * ResetListToSeed mirrors ResetHTTPRequestToSeed for Lists -- also
 * replaces Rows wholesale (upgradeListToGolden's own doc comment).
 */
export function ResetListToSeed(id: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(418099123, id);
}

/**
 * ResetMCPServerToSeed mirrors ResetHTTPRequestToSeed for MCP Servers.
 */
export function ResetMCPServerToSeed(id: string): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(1063578386, id);
}

/**
 * RestorableAIProviders mirrors RestorableMCPServers for AI providers.
 */
export function RestorableAIProviders(): $CancellablePromise<aiprovider$0.AIProvider[] | null> {
    return $Call.ByID(3321973737);
}

/**
 * RestorableDecisions mirrors RestorableHTTPRequests for Decisions.
 */
export function RestorableDecisions(): $CancellablePromise<decision$0.Decision[] | null> {
    return $Call.ByID(1640071762);
}

/**
 * RestorableExecEnvs mirrors RestorableHTTPRequests for ExecEnvs.
 */
export function RestorableExecEnvs(): $CancellablePromise<execenv$0.ExecEnv[] | null> {
    return $Call.ByID(334028898);
}

/**
 * RestorableHTTPRequests returns every built-in request the user
 * deliberately deleted (tombstoned) and not since restored -- the read
 * model for a "Restore example…" affordance, shown only when non-empty.
 */
export function RestorableHTTPRequests(): $CancellablePromise<httprequest$0.HTTPRequest[] | null> {
    return $Call.ByID(3137483177);
}

/**
 * RestorableLists mirrors RestorableHTTPRequests for Lists.
 */
export function RestorableLists(): $CancellablePromise<list$0.List[] | null> {
    return $Call.ByID(415549196);
}

/**
 * RestorableMCPServers mirrors RestorableHTTPRequests for MCP Servers.
 */
export function RestorableMCPServers(): $CancellablePromise<mcpserver$0.MCPServer[] | null> {
    return $Call.ByID(4091392795);
}

/**
 * RestoreAIProvider mirrors RestoreMCPServer for AI providers.
 */
export function RestoreAIProvider(id: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(3669826701, id);
}

/**
 * RestoreDecision mirrors RestoreHTTPRequest for Decisions.
 */
export function RestoreDecision(id: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(490914664, id);
}

/**
 * RestoreExecEnv mirrors RestoreHTTPRequest for ExecEnvs.
 */
export function RestoreExecEnv(id: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(3109139362, id);
}

/**
 * RestoreHTTPRequest un-tombstones id and re-seeds it (docs/goals/0037
 * item 5) -- the reverse of DeleteHTTPRequest for a built-in. Also
 * re-seeds the demo secret, same as a fresh install's own
 * seedBuiltInSecrets.
 */
export function RestoreHTTPRequest(id: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(2725388135, id);
}

/**
 * RestoreList mirrors RestoreHTTPRequest for Lists.
 */
export function RestoreList(id: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(3916346846, id);
}

/**
 * RestoreMCPServer mirrors RestoreHTTPRequest for MCP Servers.
 */
export function RestoreMCPServer(id: string): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(3242563609, id);
}

/**
 * SeedRevisions returns the CURRENTLY SHIPPED revision of every golden
 * Configure entity (every type this service owns), keyed by its own
 * ID -- IDs are unique across all five entity types (each domain
 * package's own ExampleXID constants), so one flat map is enough,
 * unlike seeding.AllSeedFingerprints' kind-namespaced keys (that one
 * also needs to disambiguate an entity from a workflow sharing the
 * same map; this map never mixes with CompositionService.SeedRevisions'
 * own separate call). Lets the frontend's reset affordance render an
 * accurate "Reset to shipped example vN" (docs/goals/0037 item 4).
 */
export function SeedRevisions(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(2403654017);
}

/**
 * SetAIProviderSecret writes id's secret (an API key, or Anthropic's
 * x-api-key) to the OS keychain. Write-only by design (docs/SPEC.md
 * §3.5): no GetSecret binding exists on this service -- the frontend
 * can set a secret but never read one back.
 */
export function SetAIProviderSecret(id: string, secret: string): $CancellablePromise<void> {
    return $Call.ByID(970513691, id, secret);
}

/**
 * SetHTTPRequestJOSEPrivateKey writes id's JOSE private key (Phase 3)
 * to its own, separate keychain entry -- write-only, same reasoning as
 * SetHTTPRequestSecret, but namespaced (joseKeychainID) so it can
 * coexist with whatever AuthType secret the same request also stores.
 */
export function SetHTTPRequestJOSEPrivateKey(id: string, privateKeyPEM: string): $CancellablePromise<void> {
    return $Call.ByID(4110071984, id, privateKeyPEM);
}

/**
 * SetHTTPRequestOAuth1Secret writes id's OAuth 1.0a dual secret
 * (consumer secret + token secret) to the OS keychain. AuthOAuth1's
 * own documented storage shape (ADR-0015 §3, httprequest.OAuth1Config's
 * doc comment): both values are JSON-encoded into the request's single
 * existing keychain string via composition.EncodeOAuth1Secret rather
 * than Mill inventing a multi-secret-per-request storage model. A
 * separate method (not a third SetHTTPRequestSecret param) so the
 * plain single-secret AuthTypes (APIKey/Bearer/HMAC) keep their
 * existing, simpler call shape unchanged -- addon, not a rewrite.
 */
export function SetHTTPRequestOAuth1Secret(id: string, consumerSecret: string, tokenSecret: string): $CancellablePromise<void> {
    return $Call.ByID(1346266163, id, consumerSecret, tokenSecret);
}

/**
 * SetHTTPRequestSecret writes id's secret to the OS keychain.
 * Write-only by design (docs/SPEC.md §3.5): there is deliberately no
 * GetSecret binding anywhere on this service -- the frontend can set a
 * secret but can never read one back, matching 1Password's own
 * pattern.
 */
export function SetHTTPRequestSecret(id: string, secret: string): $CancellablePromise<void> {
    return $Call.ByID(3011440021, id, secret);
}

/**
 * TestHTTPRequestOperation executes one real HTTP call against a
 * request draft's current configuration -- docs/adr/0013's
 * test-before-save flow. Runs server-side (not a browser fetch) so it
 * can resolve a keychain secret and reuses httpconnector.Execute, the
 * same commodity HTTP client + retry policy a real workflow's
 * integration-http node already goes through, deliberately not
 * special-cased faster/slower.
 */
export function TestHTTPRequestOperation(req: $models.TestHTTPRequestInput): $CancellablePromise<$models.TestHTTPRequestResult> {
    return $Call.ByID(2859699262, req);
}

export function UpdateAIProvider(id: string, label: string, kind: aiprovider$0.Kind, baseURL: string, model: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(3997420794, id, label, kind, baseURL, model);
}

/**
 * UpdateDecision rejects a category change server-side (docs/adr/0027:
 * category is immutable after creation -- Duplicate is the migration
 * path, same as the reference no-code platform this was designed
 * against). category is still a real parameter (not silently dropped
 * from the call shape) so the RPC mirrors CreateDecision's own shape;
 * the frontend disables the control and always resubmits the existing
 * value, but this check is the actual authority, not the disabled
 * control alone -- a save-time error and a run-time error never
 * disagree, same discipline ValidateGraph's own doc comment names.
 */
export function UpdateDecision(id: string, label: string, category: decision$0.Category, outputs: decision$0.OutputField[] | null, webhookRequestID: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(793782335, id, label, category, outputs, webhookRequestID);
}

export function UpdateExecEnv(id: string, label: string, shell: execenv$0.Shell, profileMode: execenv$0.ProfileMode, dir: string, env: string[] | null): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(375575575, id, label, shell, profileMode, dir, env);
}

export function UpdateHTTPRequest(id: string, label: string, baseURL: string, method: string, body: string, authType: httprequest$0.AuthType, headers: { [_ in string]?: string } | null, openAPISpec: string, auth: httprequest$0.AuthConfig | null, jose: httprequest$0.JOSEConfig | null, description: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(248664070, id, label, baseURL, method, body, authType, headers, openAPISpec, auth, jose, description);
}

export function UpdateList(id: string, label: string, description: string, columns: typedfield$0.Field[] | null): $CancellablePromise<list$0.List> {
    return $Call.ByID(437956429, id, label, description, columns);
}

/**
 * UpdateListRow replaces one row's Values/Status (its ID/CreatedAt
 * stay put; UpdatedAt is stamped here, not client-supplied).
 */
export function UpdateListRow(listID: string, rowID: string, values: { [_ in string]?: string } | null, status: list$0.RowStatus): $CancellablePromise<list$0.List> {
    return $Call.ByID(783553507, listID, rowID, values, status);
}

export function UpdateMCPServer(id: string, label: string, command: string, args: string[] | null): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(2916384132, id, label, command, args);
}

export function UpdateWorkflowAttributes(workflowID: string, attrs: composition$0.AttributeDef[] | null): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(1541426661, workflowID, attrs);
}
