// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigureService is the Wails-facing layer over Configure-authored data
 * (docs/SPEC.md §3.5): HTTPRequests, Lists, and (delegated to
 * CompositionService) a workflow's Attributes schema. Mirrors
 * CompositionService's own shape -- state + persistence a stateless
 * domain package can't own, no domain logic of its own.
 * 
 * It also owns wiring composition.go's request-lookup and list-lookup
 * seams (SetHTTPRequestLookup/SetListLookup) to its own resolve*
 * methods -- composition.go doesn't (and shouldn't) import this
 * package directly, same reasoning as CompositionService's Syncer
 * interface for TriggerService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpclient$0 from "../../adapters/mcpclient/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as openapispec$0 from "../../adapters/openapispec/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aiprovider$0 from "../../domain/aiprovider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clientcert$0 from "../../domain/clientcert/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composition$0 from "../../domain/composition/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as conversionprofile$0 from "../../domain/conversionprofile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as decision$0 from "../../domain/decision/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as declaredsteptype$0 from "../../domain/declaredsteptype/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as environment$0 from "../../domain/environment/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execenv$0 from "../../domain/execenv/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httprequest$0 from "../../domain/httprequest/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as list$0 from "../../domain/list/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpserver$0 from "../../domain/mcpserver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as secretsource$0 from "../../domain/secretsource/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../../domain/typedfield/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AIProviderFields exposes AIProvider's declared shape (docs/adr/0029)
 * to the frontend's generic entity-field renderer
 * (frontend/src/configure/EntityConfigFields.tsx) -- a static
 * descriptor, not per-instance data, mirroring how ListNodeTypes
 * already exposes each NodeType's own ConfigFields.
 */
export function AIProviderFields(): $CancellablePromise<typedfield$0.Field[] | null> {
    return $Call.ByID(2576237682);
}

export function AIProviders(): $CancellablePromise<aiprovider$0.AIProvider[] | null> {
    return $Call.ByID(3861562536);
}

/**
 * AddListRow appends a new, Active row to a List, minting its ID here
 * (row-ID generation stays a service-layer concern, same as List IDs
 * themselves via seeding.NewSlugID -- internal/domain/list stays pure
 * per .claude/rules/backend.md).
 */
export function AddListRow(listID: string, values: { [_ in string]?: string } | null): $CancellablePromise<list$0.List> {
    return $Call.ByID(197919857, listID, values);
}

/**
 * AddListRowAt inserts the new row at index (goal 0105 part 2: the
 * boundary-insert affordance -- a row lands exactly where the user
 * pointed, not only at the end). Any out-of-range index appends,
 * which is also AddListRow's own behavior.
 */
export function AddListRowAt(listID: string, values: { [_ in string]?: string } | null, index: number): $CancellablePromise<list$0.List> {
    return $Call.ByID(2366446572, listID, values, index);
}

/**
 * ApplyListRow implements composition.go's applyListRowFn seam
 * (docs/goals/0070's write path): creates a new Active row when no
 * existing row's keyColumn value matches the resolved key, otherwise
 * merges values into the first matching row -- unbound columns stay
 * untouched, the same "only the named fields change" precedent
 * apply-atlas-card-update's own AtlasCard merge documents. Typed-column
 * validation happens here (not composition), since Columns is this
 * service's own domain knowledge: an invalid value is rejected before
 * anything is persisted, never silently coerced. Always writes the
 * LIVE list -- never a published/pinned snapshot (list.Resolve's own
 * doc comment: a write always targets the draft).
 */
export function ApplyListRow(listID: string, keyColumn: string, values: { [_ in string]?: string } | null): $CancellablePromise<list$0.Row> {
    return $Call.ByID(3108720728, listID, keyColumn, values);
}

/**
 * CaptureShellPath returns the user's real login-shell $PATH -- the
 * ExecEnv form's "Capture from my shell" affordance (ADR-0026's
 * Amendment: determinism through materialization; the captured value
 * lands in the stored, visible, editable Env, never re-derived at run
 * time). A plain read with no side effects; the frontend decides what
 * to do with the value (upsert its PATH row).
 */
export function CaptureShellPath(): $CancellablePromise<string> {
    return $Call.ByID(759717731);
}

/**
 * ClientCertificateStatuses answers one status per configured
 * certificate. It returns the certificate's identity and validity
 * window only, never the material.
 */
export function ClientCertificateStatuses(): $CancellablePromise<clientcert$0.Status[] | null> {
    return $Call.ByID(3084260004);
}

export function ClientCertificates(): $CancellablePromise<clientcert$0.ClientCertificate[] | null> {
    return $Call.ByID(3430562167);
}

export function ConversionProfiles(): $CancellablePromise<conversionprofile$0.Profile[] | null> {
    return $Call.ByID(1251097066);
}

export function CreateAIProvider(label: string, kind: aiprovider$0.Kind, baseURL: string, model: string, keyRef: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(427493887, label, kind, baseURL, model, keyRef);
}

export function CreateClientCertificate(label: string, host: string, certRef: string, keyRef: string, passphraseRef: string, caRef: string, notes: string): $CancellablePromise<clientcert$0.ClientCertificate> {
    return $Call.ByID(656621746, label, host, certRef, keyRef, passphraseRef, caRef, notes);
}

export function CreateConversionProfile(label: string, description: string, ruleSets: string[] | null): $CancellablePromise<conversionprofile$0.Profile> {
    return $Call.ByID(716040745, label, description, ruleSets);
}

export function CreateDecision(label: string, category: decision$0.Category, outputs: decision$0.OutputField[] | null, webhookRequestID: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(2725151274, label, category, outputs, webhookRequestID);
}

export function CreateDeclaredStepType(label: string, description: string, paletteGroup: declaredsteptype$0.PaletteGroup, engine: declaredsteptype$0.Engine, requestID: string, mcpServerID: string, toolName: string, workflowID: string, pinnedConfig: { [_ in string]?: string } | null, hiddenFields: string[] | null): $CancellablePromise<declaredsteptype$0.DeclaredStepType> {
    return $Call.ByID(2864826736, label, description, paletteGroup, engine, requestID, mcpServerID, toolName, workflowID, pinnedConfig, hiddenFields);
}

export function CreateEnvironment(label: string, vars: environment$0.Variable[] | null): $CancellablePromise<environment$0.Environment> {
    return $Call.ByID(2125057365, label, vars);
}

export function CreateExecEnv(label: string, shell: execenv$0.Shell, profileMode: execenv$0.ProfileMode, dir: string, env: string[] | null, environmentID: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(2549731420, label, shell, profileMode, dir, env, environmentID);
}

/**
 * CreateHTTPRequest/UpdateHTTPRequest's positional-param list is
 * getting long (9 now, after ADR-0016 Phase B's method) -- a real
 * ergonomics cost (every call site needs a scripted-regex patch when a
 * field like Auth/JOSE is added), worth an
 * options-struct pass at some point, but that's a separate, bigger
 * refactor than "add a field" -- not done speculatively here.
 */
export function CreateHTTPRequest(label: string, baseURL: string, method: string, body: string, authType: httprequest$0.AuthType, secretRef: string, headers: { [_ in string]?: string } | null, openAPISpec: string, auth: httprequest$0.AuthConfig | null, jose: httprequest$0.JOSEConfig | null, description: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(2634895949, label, baseURL, method, body, authType, secretRef, headers, openAPISpec, auth, jose, description);
}

export function CreateList(label: string, description: string, columns: typedfield$0.Field[] | null): $CancellablePromise<list$0.List> {
    return $Call.ByID(1760985996, label, description, columns);
}

/**
 * CreateListWithRows creates a list and appends its first rows in one
 * door -- the table noun's and the plugin content door's shared
 * creation path (goal 0310): one round trip, and the rows are on the
 * list before any reader sees it.
 */
export function CreateListWithRows(label: string, description: string, columns: typedfield$0.Field[] | null, rows: ({ [_ in string]?: string } | null)[] | null): $CancellablePromise<list$0.List> {
    return $Call.ByID(2579741481, label, description, columns, rows);
}

export function CreateMCPServer(label: string, command: string, args: string[] | null, env: string[] | null): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(1284256739, label, command, args, env);
}

export function CreateSecretSource(label: string, kind: secretsource$0.Kind, path: string): $CancellablePromise<secretsource$0.Source> {
    return $Call.ByID(2593717437, label, kind, path);
}

export function Decisions(): $CancellablePromise<decision$0.Decision[] | null> {
    return $Call.ByID(3569228287);
}

export function DeclaredStepTypes(): $CancellablePromise<declaredsteptype$0.DeclaredStepType[] | null> {
    return $Call.ByID(514404165);
}

/**
 * DeleteAIProvider also removes any keychain secret for id -- best-
 * effort (a delete on an id with no stored secret is a harmless no-op-
 * shaped error, not surfaced), same reasoning DeleteHTTPRequest's own
 * c.credentials.Delete call already documents.
 */
export function DeleteAIProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(2537752540, id);
}

export function DeleteClientCertificate(id: string): $CancellablePromise<void> {
    return $Call.ByID(2356464611, id);
}

export function DeleteConversionProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3998413764, id);
}

export function DeleteDecision(id: string): $CancellablePromise<void> {
    return $Call.ByID(3396624017, id);
}

export function DeleteDeclaredStepType(id: string): $CancellablePromise<void> {
    return $Call.ByID(3604894371, id);
}

/**
 * DeleteEnvironment refuses while a workflow still names this
 * environment -- as its per-run default, or through a shell that
 * borrows its variables (compositionsvc.WorkflowsReferencing knows
 * both, ADR-0040 decision 3).
 */
export function DeleteEnvironment(id: string): $CancellablePromise<void> {
    return $Call.ByID(118824196, id);
}

export function DeleteExecEnv(id: string): $CancellablePromise<void> {
    return $Call.ByID(2790333249, id);
}

/**
 * DeleteHTTPRequest leaves the secret store untouched: a request only
 * ever NAMED its secrets (goal 0306), and the same entry may be named
 * by other requests or wanted again -- deleting the last thing that
 * pointed at a credential is not consent to destroy it.
 */
export function DeleteHTTPRequest(id: string): $CancellablePromise<void> {
    return $Call.ByID(1529049956, id);
}

export function DeleteList(id: string): $CancellablePromise<void> {
    return $Call.ByID(1223896803, id);
}

export function DeleteListRow(listID: string, rowID: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(2135971241, listID, rowID);
}

export function DeleteMCPServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3847603582, id);
}

export function DeleteSecretSource(id: string): $CancellablePromise<void> {
    return $Call.ByID(4158252478, id);
}

/**
 * DeriveSecretLabels answers, statically from a node's own type and
 * config -- never by resolving a real secret VALUE -- which vault
 * entries its execution will resolve, as sorted, deduped LABELS (goal
 * 0203 S2). This must compute the exact same answer a real run's own
 * vault-reference resolution (vaultref.go) would reach: WorkflowVerdicts
 * (the canvas nothing-hidden badge) calls this before anyone runs the
 * workflow, so a step that will actually touch a secret can never show
 * a clean badge the live gate then contradicts.
 */
export function DeriveSecretLabels(nodeTypeID: string, config: { [_ in string]?: string } | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(3138098164, nodeTypeID, config);
}

/**
 * DescribeReference answers a summary for kind (a ConfigField RefKind)
 * and id. An unknown kind or id is an error naming it.
 */
export function DescribeReference(kind: string, id: string): $CancellablePromise<$models.ReferenceSummary> {
    return $Call.ByID(3538022950, kind, id);
}

/**
 * DuplicateClientCertificate copies one entity's fields onto a new one,
 * so a second host reusing the same material is one action rather than
 * a re-pick of every reference.
 */
export function DuplicateClientCertificate(id: string): $CancellablePromise<clientcert$0.ClientCertificate> {
    return $Call.ByID(2719279045, id);
}

export function Environments(): $CancellablePromise<environment$0.Environment[] | null> {
    return $Call.ByID(2726528166);
}

export function ExecEnvs(): $CancellablePromise<execenv$0.ExecEnv[] | null> {
    return $Call.ByID(1392956673);
}

export function ExportAIProvider(id: string): $CancellablePromise<string> {
    return $Call.ByID(677240817, id);
}

export function ExportDecision(id: string): $CancellablePromise<string> {
    return $Call.ByID(1497100540, id);
}

export function ExportDeclaredStepType(id: string): $CancellablePromise<string> {
    return $Call.ByID(1679238510, id);
}

export function ExportEnvironment(id: string): $CancellablePromise<string> {
    return $Call.ByID(2995620899, id);
}

export function ExportExecEnv(id: string): $CancellablePromise<string> {
    return $Call.ByID(1292699062, id);
}

export function ExportHTTPRequest(id: string): $CancellablePromise<string> {
    return $Call.ByID(1052411683, id);
}

export function ExportList(id: string): $CancellablePromise<string> {
    return $Call.ByID(2193499122, id);
}

export function ExportMCPServer(id: string): $CancellablePromise<string> {
    return $Call.ByID(766088645, id);
}

/**
 * GetList returns one List by id -- the grid's schema edits read the
 * current record through this instead of fetching every list (goal
 * 0147's O(all-lists)-per-column-edit finding).
 */
export function GetList(id: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(1888930756, id);
}

/**
 * HTTPRequestOperationFields resolves one request operation's declared
 * input/output fields (ADR-0007 Phase 3) -- the data the canvas
 * Inspector's binding editor renders once a user picks an operation
 * from ListHTTPRequestOperations above. Mirrors that method's own
 * lookup/parse shape.
 */
export function HTTPRequestOperationFields(id: string, path: string, method: string): $CancellablePromise<openapispec$0.Operation> {
    return $Call.ByID(4287723439, id, path, method);
}

export function HTTPRequests(): $CancellablePromise<httprequest$0.HTTPRequest[] | null> {
    return $Call.ByID(1886035734);
}

/**
 * ImportAIProvider applies the uniform import rule. No secret ever
 * round-trips -- exportedAIProvider never carries one; an updated
 * provider's key reference is replaced by the imported one, like every
 * other field: a reference is a name, never a credential.
 */
export function ImportAIProvider(jsonData: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(2109937718, jsonData);
}

/**
 * ImportDecision applies ADR-0036 decision 3's uniform import rule
 * (this file's own header comment). WebhookRequestID is never part of
 * the wire shape (exportedDecision's own doc comment); an update
 * through this path clears it to the same "re-author it after import"
 * state a create already left it in, since UpdateDecision has no other
 * value to preserve it from.
 */
export function ImportDecision(jsonData: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(4077937019, jsonData);
}

/**
 * ImportDeclaredStepType applies ADR-0036 decision 3's uniform import
 * rule (configureservice_export.go's own header comment carries the
 * full statement).
 */
export function ImportDeclaredStepType(jsonData: string): $CancellablePromise<declaredsteptype$0.DeclaredStepType> {
    return $Call.ByID(4258139761, jsonData);
}

export function ImportEnvironment(jsonData: string): $CancellablePromise<environment$0.Environment> {
    return $Call.ByID(4137668610, jsonData);
}

export function ImportExecEnv(jsonData: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(785482531, jsonData);
}

/**
 * ImportHTTPRequest applies ADR-0036 decision 3's uniform import rule
 * (this file's own header comment). No secret ever round-trips --
 * exportedHTTPRequest never carries one, so a created-preserving-id or
 * freshly created request starts exactly like a hand-authored one that
 * hasn't had SetHTTPRequestSecret called yet; an updated request keeps
 * its existing local secret untouched (UpdateHTTPRequest never touches
 * it either).
 */
export function ImportHTTPRequest(jsonData: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(4183227914, jsonData);
}

/**
 * ImportList applies ADR-0036 decision 3's uniform import rule (this
 * file's own header comment); the id-present-and-known path routes
 * through UpdateList rather than the create-only path Entries-migration
 * legacy exports also used, then applies rows the same way as a fresh
 * create.
 */
export function ImportList(jsonData: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(2746040697, jsonData);
}

/**
 * ImportMCPServer applies the uniform import rule.
 */
export function ImportMCPServer(jsonData: string): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(337785048, jsonData);
}

/**
 * ListHTTPRequestOperations parses id's stored OpenAPISpec and returns
 * every operation it declares -- the discoverability answer for an
 * HTTPRequest's schema, same shape as ListMCPServerTools
 * (configuremcpserver.go, §3.6): a user finds the exact path+method to
 * reference from a workflow node here, not by guessing. Returns an
 * error for a request with no OpenAPISpec set, rather than an empty
 * list, so the frontend can distinguish "nothing declared yet" from
 * "real spec, zero operations."
 */
export function ListHTTPRequestOperations(id: string): $CancellablePromise<openapispec$0.OperationRef[] | null> {
    return $Call.ByID(415197675, id);
}

/**
 * ListMCPServerTools is a live, on-demand reference lookup (connects to
 * the server, lists its tools, disconnects) -- not persisted or synced,
 * same "occasional reference lookup, not a live feed" shape HTTPRequests()/
 * Lists() themselves already have (the frontend polls them on demand,
 * nothing pushes). This is docs/SPEC.md §3.6's actual discoverability
 * answer: a user finds the exact toolName to paste into an mcp-tool-call
 * node here, not by guessing.
 */
export function ListMCPServerTools(id: string): $CancellablePromise<mcpclient$0.Tool[] | null> {
    return $Call.ByID(949169294, id);
}

export function Lists(): $CancellablePromise<list$0.List[] | null> {
    return $Call.ByID(2461513153);
}

/**
 * MCPServerFields exposes MCPServer's declared scalar shape
 * (docs/adr/0029) to the frontend's generic entity-field renderer
 * (frontend/src/configure/EntityConfigFields.tsx) -- see
 * AIProviderFields' identical doc comment.
 */
export function MCPServerFields(): $CancellablePromise<typedfield$0.Field[] | null> {
    return $Call.ByID(2171620574);
}

export function MCPServers(): $CancellablePromise<mcpserver$0.MCPServer[] | null> {
    return $Call.ByID(4060206780);
}

/**
 * MatchClientCertificate answers which certificate a URL's host would
 * use. An unparseable or host-less URL matches nothing.
 */
export function MatchClientCertificate(rawURL: string): $CancellablePromise<[$models.ClientCertificateMatch, boolean]> {
    return $Call.ByID(3491633573, rawURL);
}

/**
 * ParseXlsxFile decodes base64Data (standard encoding) as an .xlsx
 * workbook and returns its rows in the same header-row, string-cell
 * shape parseImportFile's CSV branch produces (Papa Parse's
 * `header: true`), so xlsx and CSV imports behave identically once
 * parsed.
 * 
 * First sheet only (GetSheetList()[0], the workbook's own declared
 * order): the smallest honest v1 rather than a sheet picker -- a real
 * future addition, not built here.
 * 
 * The first row is the header. A ragged data row -- GetRows trims
 * each row to its own last non-empty cell -- reads its missing
 * trailing cells as "", the same as a short CSV row against a longer
 * header; a row with MORE cells than the header has its extra
 * trailing cells dropped, since there is no column name to hold them.
 * A fully blank row (no cells at all) is skipped, matching Papa
 * Parse's skipEmptyLines the CSV branch already sets.
 */
export function ParseXlsxFile(base64Data: string): $CancellablePromise<$models.ParsedXlsxFile> {
    return $Call.ByID(552870390, base64Data);
}

/**
 * PublishDecision snapshots id's current draft (Label/Category/
 * Outputs/WebhookRequestID) as the next immutable DecisionVersion and
 * advances PublishedVersion to it -- the audit-stamp reference point a
 * run's "live@N" label reads (docs/adr/0040 decision 5). Unlike
 * PublishWorkflow, this does NOT change what an unpinned decision-outcome
 * node resolves (decision.ResolveOutcome always reads the live draft) --
 * only what a NEW pin created after this call can pin to, and what an
 * unpinned run's audit stamp names as "the last publish."
 */
export function PublishDecision(id: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(4203628193, id);
}

/**
 * PublishList snapshots id's current draft (Columns+Rows) as the next
 * immutable ListVersion and advances PublishedVersion to it -- the
 * audit-stamp reference point a pinned/unpinned list-lookup/list-search
 * run's "v<N>"/"live@<N>" label reads (docs/adr/0040 decision 5).
 */
export function PublishList(id: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(3818004691, id);
}

/**
 * ResetAIProviderToSeed mirrors ResetMCPServerToSeed for AI providers,
 * via aiProviderDescriptor (configureaiprovider.go, goal 0165).
 */
export function ResetAIProviderToSeed(id: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(2473880440, id);
}

/**
 * ResetDecisionToSeed mirrors ResetHTTPRequestToSeed for Decisions,
 * via decisionDescriptor (configuredecision.go, goal 0165).
 */
export function ResetDecisionToSeed(id: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(3124176177, id);
}

/**
 * ResetEnvironmentToSeed restores a seeded Environment's shipped
 * content, via environmentDescriptor.
 */
export function ResetEnvironmentToSeed(id: string): $CancellablePromise<environment$0.Environment> {
    return $Call.ByID(442297280, id);
}

/**
 * ResetExecEnvToSeed mirrors ResetHTTPRequestToSeed for ExecEnvs, via
 * execEnvDescriptor (configureexecenv.go, goal 0165).
 */
export function ResetExecEnvToSeed(id: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(654567745, id);
}

/**
 * ResetHTTPRequestToSeed replaces id's content with the current
 * golden's and clears the Modified latch (docs/goals/0037 item 4) --
 * an explicit, on-demand act available regardless of current
 * Modified/revision state, unlike reconcile's own conditional upgrade.
 * Via httpRequestDescriptor (configureservice_builtin.go, goal 0165).
 */
export function ResetHTTPRequestToSeed(id: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(3582620696, id);
}

/**
 * ResetListToSeed mirrors ResetHTTPRequestToSeed for Lists -- also
 * replaces Rows wholesale (upgradeListToGolden's own doc comment), via
 * listDescriptor (configurelist.go, goal 0165).
 */
export function ResetListToSeed(id: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(418099123, id);
}

/**
 * ResetMCPServerToSeed mirrors ResetHTTPRequestToSeed for MCP Servers,
 * via mcpServerDescriptor (configuremcpserver.go, goal 0165).
 */
export function ResetMCPServerToSeed(id: string): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(1063578386, id);
}

/**
 * RestorableAIProviders mirrors RestorableMCPServers for AI providers.
 */
export function RestorableAIProviders(): $CancellablePromise<aiprovider$0.AIProvider[] | null> {
    return $Call.ByID(3321973737);
}

/**
 * RestorableDecisions mirrors RestorableHTTPRequests for Decisions.
 */
export function RestorableDecisions(): $CancellablePromise<decision$0.Decision[] | null> {
    return $Call.ByID(1640071762);
}

/**
 * RestorableEnvironments lists deleted seeds this install can bring
 * back.
 */
export function RestorableEnvironments(): $CancellablePromise<environment$0.Environment[] | null> {
    return $Call.ByID(9699537);
}

/**
 * RestorableExecEnvs mirrors RestorableHTTPRequests for ExecEnvs.
 */
export function RestorableExecEnvs(): $CancellablePromise<execenv$0.ExecEnv[] | null> {
    return $Call.ByID(334028898);
}

/**
 * RestorableHTTPRequests returns every built-in request the user
 * deliberately deleted (tombstoned) and not since restored -- the read
 * model for a "Restore example…" affordance, shown only when non-empty.
 */
export function RestorableHTTPRequests(): $CancellablePromise<httprequest$0.HTTPRequest[] | null> {
    return $Call.ByID(3137483177);
}

/**
 * RestorableLists mirrors RestorableHTTPRequests for Lists.
 */
export function RestorableLists(): $CancellablePromise<list$0.List[] | null> {
    return $Call.ByID(415549196);
}

/**
 * RestorableMCPServers mirrors RestorableHTTPRequests for MCP Servers.
 */
export function RestorableMCPServers(): $CancellablePromise<mcpserver$0.MCPServer[] | null> {
    return $Call.ByID(4091392795);
}

/**
 * RestoreAIProvider mirrors RestoreMCPServer for AI providers.
 */
export function RestoreAIProvider(id: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(3669826701, id);
}

/**
 * RestoreDecision mirrors RestoreHTTPRequest for Decisions.
 */
export function RestoreDecision(id: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(490914664, id);
}

/**
 * RestoreEnvironment brings one deleted seed back.
 */
export function RestoreEnvironment(id: string): $CancellablePromise<environment$0.Environment> {
    return $Call.ByID(2787993823, id);
}

/**
 * RestoreExecEnv mirrors RestoreHTTPRequest for ExecEnvs.
 */
export function RestoreExecEnv(id: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(3109139362, id);
}

/**
 * RestoreHTTPRequest un-tombstones id and re-seeds it (docs/goals/0037
 * item 5) -- the reverse of DeleteHTTPRequest for a built-in. Also
 * re-seeds the demo secret, same as a fresh install's own
 * seedBuiltInSecrets.
 */
export function RestoreHTTPRequest(id: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(2725388135, id);
}

/**
 * RestoreList mirrors RestoreHTTPRequest for Lists.
 */
export function RestoreList(id: string): $CancellablePromise<list$0.List> {
    return $Call.ByID(3916346846, id);
}

/**
 * RestoreMCPServer mirrors RestoreHTTPRequest for MCP Servers.
 */
export function RestoreMCPServer(id: string): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(3242563609, id);
}

export function SecretSources(): $CancellablePromise<secretsource$0.Source[] | null> {
    return $Call.ByID(421745118);
}

/**
 * SeedRevisions returns the CURRENTLY SHIPPED revision of every golden
 * Configure entity (every type this service owns), keyed by its own
 * ID -- IDs are unique across all five entity types (each domain
 * package's own ExampleXID constants), so one flat map is enough,
 * unlike seeding.AllSeedFingerprints' kind-namespaced keys (that one
 * also needs to disambiguate an entity from a workflow sharing the
 * same map; this map never mixes with CompositionService.SeedRevisions'
 * own separate call). Lets the frontend's reset affordance render an
 * accurate "Reset to shipped example vN" (docs/goals/0037 item 4).
 */
export function SeedRevisions(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(2403654017);
}

/**
 * SyncListRows is the apply-list-sync node's wired writer (docs/goals/
 * 0299): every incoming row goes through ApplyListRow -- the same
 * upsert-by-key, typed-validation, persist-and-emit path a single
 * apply-list-row takes -- and, when asked, rows whose key the batch
 * did not carry are marked expired through UpdateListRow. Never a
 * delete: an issue that left the source's result set is still a row
 * someone may have annotated.
 */
export function SyncListRows(listID: string, keyColumn: string, rows: ({ [_ in string]?: string } | null)[] | null, expireMissing: boolean): $CancellablePromise<composition$0.ListSyncResult> {
    return $Call.ByID(883733198, listID, keyColumn, rows, expireMissing);
}

/**
 * TestClientCertificate opens a TLS connection to the entity's host
 * and closes it, sending nothing. User-initiated, so it is the person
 * asking Mill to reach that host, never Mill reaching out on its own.
 * A nil error is a completed handshake; the sentence reporting it is
 * the caller's, so this returns no copy of its own.
 */
export function TestClientCertificate(id: string): $CancellablePromise<void> {
    return $Call.ByID(165922770, id);
}

/**
 * TestHTTPRequestOperation executes one real HTTP call against a
 * request draft's current configuration -- docs/adr/0013's
 * test-before-save flow. Runs server-side (not a browser fetch) so it
 * can resolve a keychain secret and reuses httpconnector.Execute, the
 * same commodity HTTP client + retry policy a real workflow's
 * integration-http node already goes through, deliberately not
 * special-cased faster/slower.
 */
export function TestHTTPRequestOperation(req: $models.TestHTTPRequestInput): $CancellablePromise<$models.TestHTTPRequestResult> {
    return $Call.ByID(2859699262, req);
}

/**
 * UndoDelete restores an entity deleted while the app has been running. entity
 * is the family's data-event name ("list", "request", "decision", ...),
 * id the deleted entity's id. Credential material purged by the delete
 * is not restored: the entity comes back with its secret unset, which
 * its own status reads report honestly.
 */
export function UndoDelete(entity: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(2705919001, entity, id);
}

export function UpdateAIProvider(id: string, label: string, kind: aiprovider$0.Kind, baseURL: string, model: string, keyRef: string): $CancellablePromise<aiprovider$0.AIProvider> {
    return $Call.ByID(3997420794, id, label, kind, baseURL, model, keyRef);
}

export function UpdateClientCertificate(id: string, label: string, host: string, certRef: string, keyRef: string, passphraseRef: string, caRef: string, notes: string): $CancellablePromise<clientcert$0.ClientCertificate> {
    return $Call.ByID(2004917573, id, label, host, certRef, keyRef, passphraseRef, caRef, notes);
}

export function UpdateConversionProfile(id: string, label: string, description: string, ruleSets: string[] | null): $CancellablePromise<conversionprofile$0.Profile> {
    return $Call.ByID(2782308242, id, label, description, ruleSets);
}

/**
 * UpdateDecision rejects a category change server-side (docs/adr/0027:
 * category is immutable after creation -- Duplicate is the migration
 * path, same as the reference no-code platform this was designed
 * against). category is still a real parameter (not silently dropped
 * from the call shape) so the RPC mirrors CreateDecision's own shape;
 * the frontend disables the control and always resubmits the existing
 * value, but this check is the actual authority, not the disabled
 * control alone -- a save-time error and a run-time error never
 * disagree, same discipline ValidateGraph's own doc comment names.
 * newFieldTombstones names any Key+Type this call is deleting from
 * Outputs/Columns right now -- the explicit, UI-declared half of
 * docs/adr/0040 decision 3's evolution check (typedfield.
 * ValidateFieldEvolution's own doc comment has the full rule).
 */
export function UpdateDecision(id: string, label: string, category: decision$0.Category, outputs: decision$0.OutputField[] | null, newFieldTombstones: typedfield$0.FieldTombstone[] | null, webhookRequestID: string): $CancellablePromise<decision$0.Decision> {
    return $Call.ByID(793782335, id, label, category, outputs, newFieldTombstones, webhookRequestID);
}

export function UpdateDeclaredStepType(id: string, label: string, description: string, paletteGroup: declaredsteptype$0.PaletteGroup, engine: declaredsteptype$0.Engine, requestID: string, mcpServerID: string, toolName: string, workflowID: string, pinnedConfig: { [_ in string]?: string } | null, hiddenFields: string[] | null): $CancellablePromise<declaredsteptype$0.DeclaredStepType> {
    return $Call.ByID(2416169229, id, label, description, paletteGroup, engine, requestID, mcpServerID, toolName, workflowID, pinnedConfig, hiddenFields);
}

export function UpdateEnvironment(id: string, label: string, vars: environment$0.Variable[] | null): $CancellablePromise<environment$0.Environment> {
    return $Call.ByID(3954481542, id, label, vars);
}

export function UpdateExecEnv(id: string, label: string, shell: execenv$0.Shell, profileMode: execenv$0.ProfileMode, dir: string, env: string[] | null, environmentID: string): $CancellablePromise<execenv$0.ExecEnv> {
    return $Call.ByID(375575575, id, label, shell, profileMode, dir, env, environmentID);
}

export function UpdateHTTPRequest(id: string, label: string, baseURL: string, method: string, body: string, authType: httprequest$0.AuthType, secretRef: string, headers: { [_ in string]?: string } | null, openAPISpec: string, auth: httprequest$0.AuthConfig | null, jose: httprequest$0.JOSEConfig | null, description: string): $CancellablePromise<httprequest$0.HTTPRequest> {
    return $Call.ByID(248664070, id, label, baseURL, method, body, authType, secretRef, headers, openAPISpec, auth, jose, description);
}

/**
 * newFieldTombstones names any Column Key+Type this call is deleting
 * right now -- the explicit, UI-declared half of docs/adr/0040
 * decision 3's evolution check (typedfield.ValidateFieldEvolution's
 * own doc comment has the full rule).
 */
export function UpdateList(id: string, label: string, description: string, columns: typedfield$0.Field[] | null, newFieldTombstones: typedfield$0.FieldTombstone[] | null): $CancellablePromise<list$0.List> {
    return $Call.ByID(437956429, id, label, description, columns, newFieldTombstones);
}

/**
 * UpdateListRow replaces one row's Values/Status (its ID/CreatedAt
 * stay put; UpdatedAt is stamped here, not client-supplied).
 */
export function UpdateListRow(listID: string, rowID: string, values: { [_ in string]?: string } | null, status: list$0.RowStatus): $CancellablePromise<list$0.List> {
    return $Call.ByID(783553507, listID, rowID, values, status);
}

export function UpdateMCPServer(id: string, label: string, command: string, args: string[] | null, env: string[] | null): $CancellablePromise<mcpserver$0.MCPServer> {
    return $Call.ByID(2916384132, id, label, command, args, env);
}

export function UpdateSecretSource(id: string, label: string, kind: secretsource$0.Kind, path: string): $CancellablePromise<secretsource$0.Source> {
    return $Call.ByID(2006063992, id, label, kind, path);
}

export function UpdateWorkflowAttributes(workflowID: string, attrs: composition$0.AttributeDef[] | null): $CancellablePromise<composition$0.Workflow> {
    return $Call.ByID(1541426661, workflowID, attrs);
}
