// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MenuEntry is one item. Kind is "command" (ID/Label/Accelerator/
 * Enabled), "role" (Role), or "submenu" (Label plus nested Groups).
 * 
 * Groups are separator bands: they render in order with a separator
 * between consecutive bands, so a band is how the projection expresses
 * "these belong together" without counting separators itself.
 */
export interface MenuEntry {
    "Kind": string;
    "ID": string;
    "Label": string;
    "Accelerator": string;
    "Enabled": boolean;
    "Role": string;

    /**
     * ReleaseAccelerator strips the key equivalent the platform ships a
     * role with, so the combo reaches the page instead. The item stays
     * in the menu and stays clickable -- only its shortcut is given up.
     */
    "ReleaseAccelerator": boolean;
    "Groups": (MenuEntry[] | null)[] | null;
}

/**
 * MenuNode is one top-level menu. Kind is "menu" (Label plus Groups) or
 * "roleMenu" (a menu the platform builds whole from Role, contents
 * included -- Edit).
 */
export interface MenuNode {
    "Kind": string;
    "Label": string;
    "Role": string;
    "Groups": (MenuEntry[] | null)[] | null;
}

/**
 * MenuSpec is the whole menu bar, menus in bar order.
 */
export interface MenuSpec {
    "Menus": MenuNode[] | null;
}

/**
 * Window wraps a single *application.WebviewWindow -- the port every
 * service package uses instead of holding the toolkit type directly
 * (mainthread.go's package doc has the full boundary reasoning).
 * WebviewWindow's own Show/Hide/Restore/Focus already marshal onto the
 * main thread internally (confirmed against the pinned SDK source,
 * unlike the App-level calls in app_actions.go), so these methods call
 * straight through with no extra dispatch.
 */
export interface Window {
}
