// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Field is the canonical "name + typed value" declaration, exactly as
 * recorded in ADR-0029's Decision section. Every existing consumer's
 * field set is a subset of this one (composition.ConfigField already
 * carries Key/Label/Description/Default/Type/Options/RefKind/Multiline/
 * Suggestions; composition.AttributeDef only Key/Label/Type;
 * decision.OutputField only Key/Label/Type/EnumValues-renamed-Options)
 * -- Phase 1/2 make those three type aliases of this struct rather than
 * hand-copying it three times.
 */
export interface Field {
    "Key": string;
    "Label": string;
    "Type": Type;
    "Required": boolean;
    "Default": string;
    "Description": string;

    /**
     * Options is only meaningful when Type == TypeOptions -- the set of
     * values a field's value must be one of. Named Options rather than
     * keeping decision.OutputField's own EnumValues, since Options is
     * what two of the three converging types (ConfigField/AttributeDef)
     * already called the identical concept.
     */
    "Options": string[] | null;

    /**
     * Suggestions offers non-restrictive autocomplete hints (an HTML5
     * datalist on the frontend) -- unlike Options, any value is still
     * accepted. Only meaningful for TypeText fields today (ADR-0016).
     */
    "Suggestions": string[] | null;

    /**
     * Secret marks a field whose value must never be echoed back once
     * set (a write-only credential) -- not consumed by any Phase 1/2
     * converging type yet (none of ConfigField/AttributeDef/OutputField
     * declare secrets today; httprequest/openapispec's own IsSecret
     * concept is Phase 3, out of scope), included now because it's part
     * of ADR-0029's accepted Field shape.
     */
    "Secret": boolean;

    /**
     * RefKind marks a field whose value is the ID of a Configure-
     * authored entity ("request" | "list" | "mcpserver" | "decision" |
     * "workflow" | "execenv", docs/adr/0009) -- empty for an ordinary
     * field. Orthogonal to Type: the wire value is still a plain string
     * ID.
     */
    "RefKind": string;

    /**
     * Multiline marks a text field whose values are naturally
     * multi-line documents (an HTML payload, a JSON arguments object).
     */
    "Multiline": boolean;

    /**
     * SystemManaged marks a field as platform-owned/reserved (goal
     * 0011's audit columns -- created/updated by/at, Active/Expired row
     * lifecycle on a future typed List) rather than user-declarable.
     * Not consumed by Phase 1/2's converging types yet.
     */
    "SystemManaged": boolean;
}

/**
 * Type is a field's declared value shape. TypeText/TypeNumber/
 * TypeBoolean/TypeOptions are wire-identical to today's
 * composition.ConfigFieldType values ("text"/"number"/"boolean"/
 * "options") -- no migration needed for anything already persisted.
 * TypeInteger/TypeObject/TypeArray/TypeMap/TypeDate/TypeDatetime are
 * additive, a strict superset covering what §4.1's reference-platform
 * review already named as real future field types (goal 0011's List
 * columns, ADR-0011's schema-authoring maturity) -- not consumed by
 * Phase 1/2 of ADR-0029 yet, declared now so a later capability doesn't
 * need a sixth enum value added to a type nobody else references.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeText = "text",
    TypeNumber = "number",
    TypeBoolean = "boolean",
    TypeOptions = "options",
    TypeInteger = "integer",
    TypeObject = "object",
    TypeArray = "array",
    TypeMap = "map",
    TypeDate = "date",
    TypeDatetime = "datetime",
};
