// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Field is the canonical "name + typed value" declaration, exactly as
 * recorded in ADR-0029's Decision section. Every existing consumer's
 * field set is a subset of this one (composition.ConfigField already
 * carries Key/Label/Description/Default/Type/Options/RefKind/Multiline/
 * Suggestions; composition.AttributeDef only Key/Label/Type;
 * decision.OutputField only Key/Label/Type/EnumValues-renamed-Options)
 * -- Phase 1/2 make those three type aliases of this struct rather than
 * hand-copying it three times.
 */
export interface Field {
    "Key": string;
    "Label": string;
    "Type": Type;
    "Required": boolean;
    "Default": string;
    "Description": string;

    /**
     * Options is only meaningful when Type == TypeOptions -- the set of
     * values a field's value must be one of. Named Options rather than
     * keeping decision.OutputField's own EnumValues, since Options is
     * what two of the three converging types (ConfigField/AttributeDef)
     * already called the identical concept.
     */
    "Options": string[] | null;

    /**
     * OptionColors optionally pairs Options by index with a semantic
     * color name (goal 0105: the select-option-color convergence --
     * a color belongs to the option's definition). Empty/short slices
     * are legal: any option without an explicit color auto-assigns
     * deterministically from the standard palette by index, so the
     * same field renders identically on every surface. omitempty
     * keeps color-less fields' JSON byte-identical to pre-field data
     * (persisted stores and seed fingerprints untouched).
     */
    "OptionColors"?: string[] | null;

    /**
     * Suggestions offers non-restrictive autocomplete hints (an HTML5
     * datalist on the frontend) -- unlike Options, any value is still
     * accepted. Only meaningful for TypeText fields today (ADR-0016).
     */
    "Suggestions": string[] | null;

    /**
     * Secret marks a field whose value must never be echoed back once
     * set (a write-only credential) -- not consumed by any Phase 1/2
     * converging type yet (none of ConfigField/AttributeDef/OutputField
     * declare secrets today; httprequest/openapispec's own IsSecret
     * concept is Phase 3, out of scope), included now because it's part
     * of ADR-0029's accepted Field shape.
     */
    "Secret": boolean;

    /**
     * RefKind marks a field whose value is the ID of a Configure-
     * authored entity ("request" | "list" | "mcpserver" | "decision" |
     * "workflow" | "execenv", docs/adr/0009) -- empty for an ordinary
     * field. Orthogonal to Type: the wire value is still a plain string
     * ID.
     */
    "RefKind": string;

    /**
     * ShowOnCard surfaces this field's value on a card's compact face
     * (docs/goals/0152) -- read by Atlas Kinds only; other
     * schema-carrying surfaces (List columns, Decision outputs) ignore
     * it, the same per-surface-facet convention Multiline/Secret
     * already follow. A presentation facet, freely togglable -- never
     * part of the Key/Type identity ValidateFieldEvolution pins.
     */
    "ShowOnCard"?: boolean;

    /**
     * Multiline marks a text field whose values are naturally
     * multi-line documents (an HTML payload, a JSON arguments object).
     */
    "Multiline": boolean;

    /**
     * SystemManaged marks a field as platform-owned/reserved (goal
     * 0011's audit columns -- created/updated by/at, Active/Expired row
     * lifecycle on a future typed List) rather than user-declarable.
     * Not consumed by Phase 1/2's converging types yet.
     */
    "SystemManaged": boolean;

    /**
     * Deprecated marks a field as soft-retired (docs/adr/0040 decision
     * 2): still valid on every value already bound to it, rendered
     * de-emphasized in an entity's own edit form, and excluded from a
     * picker offering fields for a NEW binding. JSON-tagged with
     * omitempty -- unlike every field above -- so an entity with no
     * deprecated fields marshals byte-identical to before this field
     * existed (every other Field member has no tag at all and is
     * always emitted, even at its zero value; this one field must stay
     * invisible at its zero value instead).
     */
    "deprecated"?: boolean;

    /**
     * StampOnChange names a companion field on the same Kind (a
     * TypeDate) to stamp with today's date whenever THIS field's own
     * value changes away from its Default (docs/goals/0164) -- e.g. a
     * lifecycle Options field ("pending-verify" -> "verified") paired
     * with a date field recording when that transition happened.
     * Write-path only (internal/services/atlassvc applies it); this
     * package stays storage-free and never stamps anything itself.
     * Empty means no stamping. JSON-tagged with omitempty, matching
     * Deprecated's own reasoning: a field declaring no pairing marshals
     * byte-identical to before this facet existed.
     */
    "StampOnChange"?: string;
}

/**
 * FieldTombstone records one schema field a Configure entity has
 * deleted (docs/adr/0040 decision 3): the Key stays reserved after
 * deletion, so ValidateFieldEvolution can reject the same Key
 * resurrecting under a different Type.
 */
export interface FieldTombstone {
    "Key": string;
    "Type": Type;
}

/**
 * Type is a field's declared value shape. TypeText/TypeNumber/
 * TypeBoolean/TypeOptions are wire-identical to today's
 * composition.ConfigFieldType values ("text"/"number"/"boolean"/
 * "options") -- no migration needed for anything already persisted.
 * TypeInteger/TypeObject/TypeArray/TypeMap/TypeDate/TypeDatetime are
 * additive, a strict superset covering what §4.1's reference-platform
 * review already named as real future field types (goal 0011's List
 * columns, ADR-0011's schema-authoring maturity) -- not consumed by
 * Phase 1/2 of ADR-0029 yet, declared now so a later capability doesn't
 * need a sixth enum value added to a type nobody else references.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeText = "text",
    TypeNumber = "number",
    TypeBoolean = "boolean",
    TypeOptions = "options",
    TypeInteger = "integer",
    TypeObject = "object",
    TypeArray = "array",
    TypeMap = "map",
    TypeDate = "date",
    TypeDatetime = "datetime",

    /**
     * TypeCardRef is a single reference to another Atlas card
     * (docs/goals/0152 slice 2): the wire value is the target card's
     * ID, and RefKind carries the TARGET ATLAS KIND's id -- safe reuse,
     * the field's own Type discriminates the interpretation (for every
     * other type RefKind names a Configure entity family). Single-value
     * and single-target-kind deliberately: the converged relation shape
     * (one target database/table) recorded in the goal file. Existence/
     * kind checks against live cards belong to the atlas service's own
     * write path, never here -- this package stays storage-free.
     */
    TypeCardRef = "cardref",
};
