// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one captured clipboard text, already redacted (known secret
 * values and secret-shaped patterns scrubbed) and already screened
 * (never a confidential-marked or Mill-self-written value) by the time
 * it reaches this package -- see the apply-clipboard-history-store
 * node's own doc comment for where those checks happen.
 */
export interface Entry {
    "ID": string;
    "Text": string;
    "CreatedAt": string;
    "Pinned": boolean;
}
