// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";

/**
 * ClientCertificate is one host's client-certificate configuration.
 */
export interface ClientCertificate {
    "ID": string;
    "Label": string;

    /**
     * Host is an exact host ("api.example.com"), or a wildcard whose
     * only "*" is the leftmost label ("*.example.com"). A port may be
     * appended ("api.example.com:8443"); a Host with no port matches
     * every port.
     */
    "Host": string;

    /**
     * CertRef names the certificate: a PEM chain (kind certificate), or
     * a PKCS#12 bundle (kind file) that carries its own key.
     */
    "CertRef": string;

    /**
     * KeyRef names the private key (kind key). Empty when CertRef is a
     * PKCS#12 bundle.
     */
    "KeyRef": string;

    /**
     * PassphraseRef names the passphrase (kind text) for an encrypted
     * PKCS#8 key or a PKCS#12 bundle.
     */
    "PassphraseRef": string;

    /**
     * CARef names a private root the server presents (kind
     * certificate). It is ADDED to the system pool, never a
     * replacement for it.
     */
    "CARef": string;
    "Notes": string;
    "BuiltIn": boolean;
    "Seed": seedorigin$0.Origin;
    "CreatedAt": string;
    "UpdatedAt": string;
}

/**
 * State is what a Certificates row reports about one entity, computed
 * from the certificate's own validity window. It never carries the
 * material, and never the reason a read failed beyond "could not be
 * read" -- a status line is not a diagnostic channel.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StateIncomplete: the entity names no certificate yet, or names a
     * PEM certificate with no key beside it.
     */
    StateIncomplete = "incomplete",

    /**
     * StateUnreadable: the material is named but cannot be read right
     * now -- the vault is locked, an entry was deleted, or a
     * passphrase does not open the bundle.
     */
    StateUnreadable = "unreadable",
    StateReady = "ready",

    /**
     * StateExpiring: valid, but inside ExpiryWarningDays of its end.
     */
    StateExpiring = "expiring",
    StateExpired = "expired",
};

/**
 * Status is one entity's certificate identity and validity. Subject/
 * Issuer/NotBefore/NotAfter are the ONLY fields read out of the
 * certificate: never the PEM, never anything derived from the key.
 */
export interface Status {
    "id": string;
    "state": State;
    "daysLeft": number;
    "subject": string;
    "issuer": string;
    "notBefore": string;
    "notAfter": string;
}
