// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DocsService from "./docsservice.js";
export {
    DocsService
};

export type {
    DocsIndexEntry
} from "./models.js";
