// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocsIndexEntry is one nav row, in reading order.
 */
export interface DocsIndexEntry {
    "rel": string;
    "title": string;
    "note": string;
}
