// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocSearchEntry is one page's contribution to the client-side search
 * index: title plus the page's full text (rendered then stripped to
 * plain text, so matches land on prose, not markdown syntax).
 */
export interface DocSearchEntry {
    "rel": string;
    "title": string;
    "text": string;
    "kind": string;
}

/**
 * DocsIndexEntry is one nav row, in reading order. Kind is the page's
 * quadrant (tutorial, how-to, reference, explanation) -- the nav groups
 * by it.
 */
export interface DocsIndexEntry {
    "rel": string;
    "title": string;
    "note": string;
    "kind": string;
}
