// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompanionService is goal 0101 slice 1's bound surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SendMessage streams one chat turn against aiProviderID. system is the
 * caller-assembled context -- AtlasService.SpaceContextEnvelope for a
 * fresh turn, AtlasService.CorrectionEnvelope for a re-propose turn --
 * the panel's own choice of which envelope to fetch, never decided in
 * here. messages is the full conversation history including the
 * just-typed user turn (the panel resends it whole every call; this
 * service persists nothing). Progressive text arrives as
 * DeltaEventName events while this call is in flight; the return value
 * is the complete text plus its parsed reply preview.
 */
export function SendMessage(aiProviderID: string, system: string, messages: $models.ChatMessage[] | null): $CancellablePromise<$models.CompanionReply> {
    return $Call.ByID(3416446661, aiProviderID, system, messages);
}
