// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Changed is the live-sync event payload: which kind of entity changed
 * (e.g. "workflow", "request", "list", "mcpserver", "decision",
 * "execenv", "aiprovider", "steptype", "guardrail-rule", "run",
 * "hotkey", "keybinding", "atlas") and its ID -- "hotkey" carries the
 * workflow ID its combo binds to, "keybinding" carries the command ID
 * its combo overrides. "steptype" is a declared step type (docs/adr/
 * 0037, goal 0054 slice A). "atlas" covers every Atlas entity family
 * (Kind/LinkKind/Card/Link/lens, docs/adr/0038, docs/goals/0061) --
 * one shared entity string rather than one per family, since they all
 * persist as a single blob (atlassvc's own atlasStateKey) and a
 * change to any of them means the whole surface should refresh.
 * "extension" carries the canvas-extension id whose enabled/disabled
 * state just changed (Settings > Extensions).
 * Kind narrows the change to the entity's own family inside Entity
 * ("atlas" events carry "card", "kind", "note", "link", "linkKind", a
 * perspective, or a board object's own kind string -- the same
 * vocabulary the content index's ContentEntry.Kind uses), resolved
 * once at this ONE fan-out point through a resolver the owning
 * service registers (RegisterKindResolver below), never re-derived
 * per listener. Empty when no resolver knows the entity, or the id.
 */
export interface Changed {
    "entity": string;
    "id": string;
    "kind"?: string;
}

/**
 * LifecycleBy names what added or removed one reference to an entity:
 * a board object (BoardID+ObjectID), a workflow (WorkflowID), or a
 * plugin's own declared setting (PluginID+SettingKey, docs/goals/0400)
 * -- the three sources reference.Refs distinguishes. Exactly one
 * group populated per event; a pointer field on LifecycleEvent so an
 * event with no By (entity.created/entity.deleted) carries neither.
 */
export interface LifecycleBy {
    "boardId"?: string;
    "objectId"?: string;
    "workflowId"?: string;
    "pluginId"?: string;
    "settingKey"?: string;
}

/**
 * LifecycleEvent is the one entity/object lifecycle event family (docs/
 * goals/0392 Decision 4). Event discriminates which of the six
 * transitions fired; every other field is populated only by the
 * Emit* function that produces that event (see each one's own doc
 * comment below) -- ids and kinds only, never the entity's own
 * content, so a subscriber queries what it needs instead of trusting a
 * payload that could go stale.
 */
export interface LifecycleEvent {
    "event": string;

    /**
     * EntityKind/EntityID: every entity.* event.
     */
    "entityKind"?: string;
    "entityId"?: string;

    /**
     * By: entity.referenced/entity.dereferenced only -- which board
     * object added or removed the reference.
     */
    "by"?: LifecycleBy | null;

    /**
     * Remaining: entity.dereferenced only -- how many live references
     * (board objects plus workflow nodes) survive this one's removal;
     * 0 means the entity is now unused anywhere.
     */
    "remaining"?: number | null;

    /**
     * BoardID/ObjectID: object.created/object.deleted only.
     */
    "boardId"?: string;
    "objectId"?: string;

    /**
     * Kind: object.created only -- the board object's own kind.
     */
    "kind"?: string;

    /**
     * EntityRef: object.created only -- the Configure entity kind this
     * object's kind declares a reference to ("list" for table), empty
     * for a kind with none declared.
     */
    "entityRef"?: string;
}
