// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Category is a Decision's outcome classification -- immutable once
 * created (ConfigureService.UpdateDecision rejects a category change;
 * Duplicate is the migration path, mirroring the reference no-code
 * platform ADR-0027 was designed against). Validate below only checks
 * shape validity, not immutability -- that's an update-time-only
 * concern a pure value has no way to express (it would need the
 * previously-stored value to compare against).
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CategoryApprove = "approve",
    CategoryDeny = "deny",
    CategoryManualReview = "manual-review",
    CategoryActionNeeded = "action-needed",
    CategoryUncategorized = "uncategorized",
};

/**
 * Decision is one reusable, Configure-authored terminal outcome.
 * WebhookRequestID optionally references an HTTPRequest entity by ID --
 * deliberately NOT a second outbound-HTTP config surface of its own
 * (URL/auth/retry fields), by direct decision recorded in ADR-0027: the
 * governed outbound capability (auth strategies, keychain secrets,
 * retries, guardrail effect) already exists once via HTTPRequest/
 * integration-http, and duplicating it here is exactly the anti-pattern
 * the reference platform's own review warned against.
 */
export interface Decision {
    "ID": string;
    "Label": string;
    "Category": Category;
    "Outputs": OutputField[] | null;
    "WebhookRequestID": string;

    /**
     * BuiltIn marks a seeded, top-up example (builtin.go) -- purely
     * informational, same as composition.Workflow.BuiltIn /
     * httprequest.HTTPRequest.BuiltIn: the UI badges it, and a deleted
     * built-in gets a tombstone (internal/services/seeding) so top-up
     * seeding never resurrects it.
     */
    "BuiltIn": boolean;
}

/**
 * OutputField declares one named, typed field in a Decision's terminal
 * result contract. Deliberately the same minimal vocabulary
 * composition.AttributeDef already uses (Key/Label/Type -- "text" /
 * "number" / "boolean" / "options", ConfigFieldType's own string
 * values) plus EnumValues (composition.ConfigField.Options's own
 * equivalent, one level down) -- NOT a fourth schema system (ADR-0027's
 * own explicit non-goal: convergence onto one canonical schema editor
 * stays SPEC.md §4.1's named future work). Type stays a plain string
 * here (not composition.ConfigFieldType) so this package never has to
 * import composition -- composition imports decision instead, the same
 * direction it already imports internal/domain/httprequest.
 */
export interface OutputField {
    "Key": string;
    "Label": string;
    "Type": string;
    "EnumValues": string[] | null;
}
