// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../typedfield/models.js";

/**
 * Category is a Decision's outcome classification -- immutable once
 * created (ConfigureService.UpdateDecision rejects a category change;
 * Duplicate is the migration path, mirroring the reference no-code
 * platform ADR-0027 was designed against). Validate below only checks
 * shape validity, not immutability -- that's an update-time-only
 * concern a pure value has no way to express (it would need the
 * previously-stored value to compare against).
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CategoryApprove = "approve",
    CategoryDeny = "deny",
    CategoryManualReview = "manual-review",
    CategoryActionNeeded = "action-needed",
    CategoryUncategorized = "uncategorized",
};

/**
 * Decision is one reusable, Configure-authored terminal outcome.
 * WebhookRequestID optionally references an HTTPRequest entity by ID --
 * deliberately NOT a second outbound-HTTP config surface of its own
 * (URL/auth/retry fields), by direct decision recorded in ADR-0027: the
 * governed outbound capability (auth strategies, keychain secrets,
 * retries, guardrail effect) already exists once via HTTPRequest/
 * integration-http, and duplicating it here is exactly the anti-pattern
 * the reference platform's own review warned against.
 */
export interface Decision {
    "ID": string;
    "Label": string;
    "Category": Category;
    "Outputs": OutputField[] | null;
    "WebhookRequestID": string;

    /**
     * BuiltIn marks a seeded, top-up example (builtin.go) -- purely
     * informational, same as composition.Workflow.BuiltIn /
     * httprequest.HTTPRequest.BuiltIn: the UI badges it, and a deleted
     * built-in gets a tombstone (internal/services/seeding) so top-up
     * seeding never resurrects it.
     */
    "BuiltIn": boolean;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (SPEC.md
     * §3.2.2's reserved-column pattern), stamped server-side at every
     * persisted mutation (ConfigureService), never trusted from the
     * wire. Zero value means pre-timestamp data -- migration-free.
     */
    "CreatedAt": string;
    "UpdatedAt": string;

    /**
     * Seed is this decision's seed provenance (docs/goals/0037) --
     * zero value means "not of seed origin," migration-free. See
     * composition.Workflow.Seed's doc comment for the full reasoning.
     */
    "Seed": seedorigin$0.Origin;

    /**
     * FieldTombstones records every Outputs Key this Decision has ever
     * deleted (docs/adr/0040 decision 3) -- typedfield.
     * ValidateFieldEvolution reads this at every UpdateDecision call to
     * tell an explicit, declared delete apart from a silently dropped
     * field, and to reject the same Key resurrecting under a different
     * Type. Empty for every Decision that has never had an output
     * deleted, migration-free.
     */
    "FieldTombstones": typedfield$0.FieldTombstone[] | null;

    /**
     * Versions/PublishedVersion give Decision the same draft/publish
     * lifecycle Workflow already has (docs/adr/0021, applied to a
     * second entity type by docs/adr/0040 decision 4): the fields above
     * (Label/Category/Outputs/WebhookRequestID) are this Decision's own
     * DRAFT, edited in place exactly as before this existed; Versions
     * holds immutable snapshots frozen by Publish (versioning.go), and
     * PublishedVersion (0 = never published) names which snapshot is
     * the audit-stamp's "live@N" reference point -- unlike Workflow,
     * unpinned resolution always reads the current draft, never the
     * published pointer (see versioning.go's ResolveOutcome doc
     * comment for why). Both zero-valued for every Decision persisted
     * before this existed, migration-free.
     */
    "Versions": DecisionVersion[] | null;
    "PublishedVersion": number;
}

/**
 * DecisionVersion is one immutable snapshot of a Decision's
 * schema-carrying definition (docs/adr/0040 decision 4) -- the same
 * draft/publish shape composition.WorkflowVersion gives Workflow
 * (ADR-0021), built on the shared internal/domain/versioning mechanism
 * rather than a second hand-rolled copy of the numbering logic.
 */
export interface DecisionVersion {
    "Version": number;
    "SavedAt": string;
    "Label": string;
    "Category": Category;
    "Outputs": OutputField[] | null;
    "WebhookRequestID": string;
}

/**
 * OutputField declares one named, typed field in a Decision's terminal
 * result contract. A type alias of typedfield.Field (docs/adr/0029,
 * Phase 2) -- the same canonical leaf composition.ConfigField/
 * AttributeDef converged onto in Phase 1, not a fourth schema system
 * (ADR-0027's own explicit non-goal: convergence onto one canonical
 * schema editor stays SPEC.md §4.1's named future work). typedfield is
 * a leaf package with zero internal imports, so decision importing it
 * creates no cycle -- composition already imports decision (and now
 * also typedfield directly, Phase 1), the same direction it already
 * imports internal/domain/httprequest.
 * 
 * Wire change from this alias: the field this package used to call
 * EnumValues is now Options (typedfield.Field's own name for the
 * identical concept -- ConfigField/AttributeDef already called it
 * that). Decision's own UnmarshalJSON below migrates an
 * already-persisted {"EnumValues": [...]} document forward at decode
 * time, the same "migrate the old shape forward on load, never drop
 * real data" precedent ADR-0016's configure-connectors ->
 * configure-requests key rename already established -- just applied at
 * the field level here instead of the settings-key level, since
 * Decision unmarshals directly via encoding/json rather than through a
 * keyed settings-store migration.
 */
export type OutputField = typedfield$0.Field;
