// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as typedfield$0 from "../typedfield/models.js";

/**
 * Category is a Decision's outcome classification -- immutable once
 * created (ConfigureService.UpdateDecision rejects a category change;
 * Duplicate is the migration path, mirroring the reference no-code
 * platform ADR-0027 was designed against). Validate below only checks
 * shape validity, not immutability -- that's an update-time-only
 * concern a pure value has no way to express (it would need the
 * previously-stored value to compare against).
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CategoryApprove = "approve",
    CategoryDeny = "deny",
    CategoryManualReview = "manual-review",
    CategoryActionNeeded = "action-needed",
    CategoryUncategorized = "uncategorized",
};

/**
 * Decision is one reusable, Configure-authored terminal outcome.
 * WebhookRequestID optionally references an HTTPRequest entity by ID --
 * deliberately NOT a second outbound-HTTP config surface of its own
 * (URL/auth/retry fields), by direct decision recorded in ADR-0027: the
 * governed outbound capability (auth strategies, keychain secrets,
 * retries, guardrail effect) already exists once via HTTPRequest/
 * integration-http, and duplicating it here is exactly the anti-pattern
 * the reference platform's own review warned against.
 */
export interface Decision {
    "ID": string;
    "Label": string;
    "Category": Category;
    "Outputs": OutputField[] | null;
    "WebhookRequestID": string;

    /**
     * BuiltIn marks a seeded, top-up example (builtin.go) -- purely
     * informational, same as composition.Workflow.BuiltIn /
     * httprequest.HTTPRequest.BuiltIn: the UI badges it, and a deleted
     * built-in gets a tombstone (internal/services/seeding) so top-up
     * seeding never resurrects it.
     */
    "BuiltIn": boolean;
}

/**
 * OutputField declares one named, typed field in a Decision's terminal
 * result contract. A type alias of typedfield.Field (docs/adr/0029,
 * Phase 2) -- the same canonical leaf composition.ConfigField/
 * AttributeDef converged onto in Phase 1, not a fourth schema system
 * (ADR-0027's own explicit non-goal: convergence onto one canonical
 * schema editor stays SPEC.md §4.1's named future work). typedfield is
 * a leaf package with zero internal imports, so decision importing it
 * creates no cycle -- composition already imports decision (and now
 * also typedfield directly, Phase 1), the same direction it already
 * imports internal/domain/httprequest.
 * 
 * Wire change from this alias: the field this package used to call
 * EnumValues is now Options (typedfield.Field's own name for the
 * identical concept -- ConfigField/AttributeDef already called it
 * that). Decision's own UnmarshalJSON below migrates an
 * already-persisted {"EnumValues": [...]} document forward at decode
 * time, the same "migrate the old shape forward on load, never drop
 * real data" precedent ADR-0016's configure-connectors ->
 * configure-requests key rename already established -- just applied at
 * the field level here instead of the settings-key level, since
 * Decision unmarshals directly via encoding/json rather than through a
 * keyed settings-store migration.
 */
export type OutputField = typedfield$0.Field;
