// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notification$0 from "../../domain/notification/models.js";

/**
 * PublishResult is Publish's return shape: the durable Record (created
 * fresh, or the existing one a repeat DedupeKey resolved to) plus which
 * channel names newly delivered on THIS call specifically -- distinct
 * from Record.DeliveredChannels' cumulative history, since a caller
 * (e.g. the browser-tab channel's own frontend half) needs to know
 * whether ITS delivery just happened, not the record's full history.
 */
export interface PublishResult {
    "record": notification$0.Record;
    "delivered": string[] | null;
}
