// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as seedorigin$0 from "../seedorigin/models.js";

/**
 * MCPServer is one reusable, named MCP server connection -- Command is
 * run with Args over stdio (mcp.CommandTransport, wrapped by
 * internal/adapters/mcpclient) each time a workflow resolves it.
 */
export interface MCPServer {
    "ID": string;
    "Label": string;
    "Command": string;
    "Args": string[] | null;

    /**
     * Env is the child process's own environment additions, KEY=VALUE
     * per entry (execenv.ExecEnv.Env's own shape) -- merged onto Mill's
     * ambient environment at spawn (unlike ExecEnv's fully-explicit
     * posture: an MCP server subprocess still needs PATH etc. to run at
     * all). A value of the form "vault:<entry-id>" (vaultref.Parse,
     * goal 0185 S3) is resolved to that vault entry's password at spawn
     * time, never written to disk in resolved form -- the MCP spec's
     * own delivery contract ("retrieve credentials from the
     * environment"), Mill's storage answer for the client side it
     * leaves unspecified.
     */
    "Env": string[] | null;

    /**
     * BuiltIn marks a seeded example MCP Server (BuiltIn() below) --
     * purely informational, same as httprequest.HTTPRequest.BuiltIn/
     * decision.Decision.BuiltIn/list.List.BuiltIn: drives a "built-in"
     * badge only, never gates Edit/Delete.
     */
    "BuiltIn": boolean;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (SPEC.md
     * §3.2.2's reserved-column pattern), stamped server-side at every
     * persisted mutation (ConfigureService), never trusted from the
     * wire. Zero value means pre-timestamp data -- migration-free.
     */
    "CreatedAt": string;
    "UpdatedAt": string;

    /**
     * Seed is this MCP server's seed provenance (docs/goals/0037) --
     * zero value means "not of seed origin," migration-free. See
     * composition.Workflow.Seed's doc comment for the full reasoning.
     */
    "Seed": seedorigin$0.Origin;
}
