// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPServer is one reusable, named MCP server connection -- Command is
 * run with Args over stdio (mcp.CommandTransport, wrapped by
 * internal/adapters/mcpclient) each time a workflow resolves it.
 */
export interface MCPServer {
    "ID": string;
    "Label": string;
    "Command": string;
    "Args": string[] | null;

    /**
     * BuiltIn marks a seeded example MCP Server (BuiltIn() below) --
     * purely informational, same as httprequest.HTTPRequest.BuiltIn/
     * decision.Decision.BuiltIn/list.List.BuiltIn: drives a "built-in"
     * badge only, never gates Edit/Delete.
     */
    "BuiltIn": boolean;

    /**
     * CreatedAt/UpdatedAt are system-managed audit timestamps (SPEC.md
     * §3.2.2's reserved-column pattern), stamped server-side at every
     * persisted mutation (ConfigureService), never trusted from the
     * wire. Zero value means pre-timestamp data -- migration-free.
     */
    "CreatedAt": string;
    "UpdatedAt": string;
}
