// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as CapabilitiesService from "./capabilitiesservice.js";
export {
    CapabilitiesService
};
