// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuditService owns the shared store's export and retention surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ExportAuditTrail returns every audit_entries row matching kinds
 * (empty means every kind) as JSON lines -- one exportRow object per
 * line, oldest matches of each page first -- goal 0351 Decision 5's
 * "one export door, filtered by kind": the same shared reader backs
 * both this general export and (unchanged since it already reads
 * through this same table) PluginService.ExportPluginAudit's own
 * plugin-secret-access slice.
 */
export function ExportAuditTrail(kinds: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1382846865, kinds);
}
