// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Field is one declared input or output field of an Operation.
 */
export interface Field {
    "Name": string;

    /**
     * "path" | "query" | "header" | "cookie" | "body"
     */
    "In": string;

    /**
     * "string" | "number" | "integer" | "boolean" | "object" | "array" | "map" | "date" | "datetime"
     */
    "Type": string;
    "Required": boolean;

    /**
     * IsSecret flags a field composition.ValidateGraph's save-time
     * guardrail (ADR-0007) refuses to let a workflow bind into an
     * output Attribute -- true when the field's schema declares the
     * OpenAPI-standard `format: "password"` (the spec's own documented
     * convention for "mask this in a UI"), or its name looks
     * secret-shaped (token/secret/password/apikey/authorization) as a
     * defensive fallback for specs that don't bother with the format
     * annotation. Applies uniformly to input and output fields -- a
     * response can legitimately echo a sensitive field too.
     */
    "IsSecret": boolean;

    /**
     * Alias is a friendlier reference name for this field (docs/adr/0011),
     * read from the standard OpenAPI x-mill-alias vendor extension --
     * empty when unset. Display-only: nothing in this package or
     * composition's binding resolution treats Alias as a lookup key,
     * only Name is ever used for that.
     */
    "Alias": string;

    /**
     * Path is a dot-separated path into (possibly nested) response JSON
     * for extracting this field's value (docs/adr/0011), read from the
     * x-mill-path extension -- empty means "read Name as a flat
     * top-level key," the behavior every field had before this existed.
     * Only meaningful for output fields.
     */
    "Path": string;

    /**
     * Default is the field's declared OpenAPI `default` value,
     * stringified (Default is `any` in the underlying schema -- Mill's
     * own config/binding values are uniformly strings on the wire, same
     * convention Node.Config/runInput.Values already use). Empty when
     * unset -- OpenAPI's own `default` keyword, no vendor extension
     * needed (unlike Alias/Path, which have no OpenAPI-standard
     * equivalent).
     */
    "Default": string;

    /**
     * Description is the field's declared OpenAPI `description`.
     */
    "Description": string;

    /**
     * EnumValues is the field's declared OpenAPI `enum` list,
     * stringified -- empty when unset. Same idea as ConfigField's
     * FieldOptions (docs/SPEC.md §3.4), one level down: a connector
     * schema field's own allowed-value constraint, not a NodeType
     * config field's.
     */
    "EnumValues": string[] | null;
}

/**
 * Operation is one path+method's declared input/output schema.
 */
export interface Operation {
    "InputFields": Field[] | null;
    "OutputFields": Field[] | null;

    /**
     * ResponseExtractPath is a document-level root extraction applied
     * to the whole response *before* any per-field Path extraction
     * (docs/SPEC.md §4.1) -- e.g. an envelope like {"data":{...}} where
     * every declared field actually lives under "data". Read from the
     * x-mill-response-extract-path vendor extension on the operation
     * itself (OpenAPI's own x-* mechanism, same as Field's Alias/Path).
     * Deliberately narrower than the reference platform's own syntax
     * (no bracket-array-index or "$."-JSONPath-prefix support) --
     * reuses the exact same dot-path + numeric-segment grammar
     * extractPath (attributebinding.go) already has, rather than a
     * second parser for a grammar that was never fully specified
     * (docs/SPEC.md §10). Empty or "*" means no extraction (the
     * original, unwrapped response) -- "*" is the one reference-platform
     * example this can represent exactly, since "identity" needs no
     * real path grammar at all.
     */
    "ResponseExtractPath": string;
}

/**
 * OperationRef identifies one callable operation in a Document, for a
 * Configure-time operation picker.
 */
export interface OperationRef {
    "Path": string;
    "Method": string;
    "Summary": string;
}
