// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecutionService is the Wails-facing layer over
 * internal/adapters/execution's durable-workflow runtime -- it holds no
 * domain logic of its own (that's composition.ExecuteWorkflowWithStepRunner),
 * only the DBOS wiring and the Mill-specific run/step shapes a stateless
 * adapter package can't own, mirroring CompositionService's own split.
 * See docs/adr/0004's Update for the full workflow/step mapping this
 * implements.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelRun stops an in-flight run (docs/adr/0026): kills every
 * currently-registered live process belonging to runID (in practice at
 * most one -- composition's graph walk executes nodes serially, no
 * concurrent node execution exists yet) via procexec's own real
 * process-group SIGTERM-then-SIGKILL escalation, and marks the DBOS
 * workflow CANCELLED so ListRuns/GetRun reflect it even for a run with
 * no code-execution step currently live (e.g. cancelling a parked
 * approval instead of, or in addition to, a running process). Safe to
 * call on a run with no registered process at all -- the kill loop is
 * simply a no-op, and the DBOS-level cancel still applies.
 */
export function CancelRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3711740411, runID);
}

/**
 * GetRun returns one run's full per-node step breakdown, joined against
 * its workflow definition's current Nodes (by ID) for display labels --
 * falls back to a bare step list (no labels) if the definition was
 * since edited/deleted, rather than failing the whole call over
 * missing display metadata.
 */
export function GetRun(runID: string): $CancellablePromise<$models.RunDetail> {
    return $Call.ByID(1904471609, runID);
}

/**
 * HomeMetrics computes docs/goals/0014's full Home payload for every
 * run created in [fromISO, toISO) (RFC3339 instants -- the frontend
 * computes the boundary for its "last 7/30 days" selector directly, so
 * Go only ever parses an exact instant, never a fuzzy date string).
 * includeTest widens ErrorRate/Series to also count "test" runs -- see
 * each returned field's own doc comment for which of the five numbers
 * that flag actually affects.
 */
export function HomeMetrics(fromISO: string, toISO: string, includeTest: boolean): $CancellablePromise<$models.HomeMetrics> {
    return $Call.ByID(583988216, fromISO, toISO, includeTest);
}

/**
 * ListRuns returns recent runs across every workflow, most recent
 * first -- the data behind Activity's cross-workflow "did anything run"
 * feed and any other surface needing every run regardless of which
 * workflow it belongs to.
 */
export function ListRuns(): $CancellablePromise<$models.RunSummary[] | null> {
    return $Call.ByID(2559917642);
}

/**
 * ListRunsForWorkflow returns recent runs for one workflow only, most
 * recent first -- the data behind a workflow's own Runs tab
 * (docs/SPEC.md §7's Update: durable-run visibility moved from a
 * standalone page into the workflow it belongs to, per real precedent
 * -- n8n/Retool/Airflow all scope this to the individual workflow's own
 * page, never a global page reached via a workflow picker). DBOS has no
 * native filter on runInput.WorkflowID (an arbitrary field inside the
 * generically-serialized Input, not something ListWorkflows' own
 * filters -- WithFilterWorkflowIDs et al. -- can query against), so this
 * filters post-decode the same way summaryFromStatus already decodes
 * runInput for every other field.
 */
export function ListRunsForWorkflow(workflowID: string): $CancellablePromise<$models.RunSummary[] | null> {
    return $Call.ByID(3062409004, workflowID);
}

/**
 * RedriveRun forks runID from the given node's step, reusing every
 * earlier step's checkpointed output instead of re-executing it --
 * Mill's "fix forward" mechanism (docs/adr/0004's Update), most useful
 * after correcting an HTTPRequest/List/MCP Server's Configure-page setup
 * in between, since those resolve live at execution time.
 */
export function RedriveRun(runID: string, fromNodeID: string): $CancellablePromise<$models.RunSummary> {
    return $Call.ByID(2260934620, runID, fromNodeID);
}

/**
 * ResolveApproval delivers the human's decision to a parked run -- the
 * Approve/Deny buttons' RPC. values is the reviewer's typed input for
 * a human-review checkpoint (nil/empty for a plain approve or an
 * ambient-gate ask). Send works from outside a workflow (verified
 * against the installed DBOS source).
 */
export function ResolveApproval(runID: string, nodeID: string, approve: boolean, values: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(3409756583, runID, nodeID, approve, values);
}

/**
 * RunWorkflow is the one execution entrypoint for the running app
 * (docs/adr/0008) -- every run, whether started from Composition's
 * canvas, the Runs page's own quick-run picker, or (once TriggerService
 * is wired to this path, ADR-0008's named follow-on) a real headless
 * trigger, goes through here. Every node's result is checkpointed and
 * the run stays visible/redrivable afterward (ListRuns/GetRun/
 * RedriveRun) regardless of kind -- a "test" run gets exactly the same
 * durability guarantees as a "triggered" one, only the Kind label
 * differs. composition.ExecuteWorkflow (no DBOS, no checkpointing)
 * still exists as the tested primitive internal/domain/composition's
 * own unit tests call directly -- no Wails-bound service calls it
 * anymore.
 * values overrides this run's starting Attribute values, keyed by
 * AttributeDef.Key (docs/adr/0008's test-input form) -- nil for a
 * workflow with no declared Attributes, or any caller (TriggerService's
 * headless fire path) that has no user-supplied values to offer.
 */
export function RunWorkflow(workflowID: string, kind: $models.RunKind, values: { [_ in string]?: string } | null): $CancellablePromise<$models.RunSummary> {
    return $Call.ByID(2199477208, workflowID, kind, values);
}
