// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ListSecretAccessRequest is the bound read API's request shape --
 * EntryID empty means "no filter" (the Secrets view's global Access
 * history list); set means "this one entry's own history" (the detail
 * dialog's own filtered view). Mirrors mcpauditsvc.ListMCPCallsRequest's
 * own shape.
 */
export interface ListSecretAccessRequest {
    "entryId": string;

    /**
     * ActorPrefix narrows to actors starting with it (the plugin audit
     * export passes "plugin:"); empty means every actor.
     */
    "actorPrefix": string;
    "limit": number;
    "offset": number;
}

/**
 * ListSecretAccessResponse carries one page plus the total matching-row
 * count, same "showing X-Y of Z" reasoning ListMCPCallsResponse gives.
 */
export interface ListSecretAccessResponse {
    "records": SecretAccessRecord[] | null;
    "total": number;
}

/**
 * SecretAccessRecord is the frontend-facing JSON shape for one audit
 * row -- mirrors secretaudit.Record with JSON tags added, same
 * "adapter type stays free of a frontend-JSON concern" reasoning
 * mcpauditsvc.MCPCallRecord's own doc comment gives.
 */
export interface SecretAccessRecord {
    "id": number;
    "timestamp": string;
    "entryId": string;
    "label": string;
    "context": string;
    "runId": string;
    "workflowId": string;
    "actor": string;
    "outcome": string;
    "errorText": string;
}

/**
 * SourcesLister hands the service the user's enabled secret sources
 * (the Configure entity); wired late like every other seam.
 */
export type SourcesLister = any;

/**
 * Status is VaultStatus's return shape -- the one read the frontend
 * needs to decide which of "set up," "unlock," or "browse" to show.
 * PresenceProtected is a plain credential.Store read (never a prompt),
 * safe on every build including server mode -- goal 0204's status line
 * depends on it working even where the presence-gated read itself
 * cannot.
 */
export interface Status {
    "Exists": boolean;
    "Unlocked": boolean;
    "PresenceProtected": boolean;
}
