// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is VaultStatus's return shape -- the one read the frontend
 * needs to decide which of "set up," "unlock," or "browse" to show.
 */
export interface Status {
    "Exists": boolean;
    "Unlocked": boolean;
}
