// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecretService is the Wails-facing layer over the vault. credentials is
 * shared with ConfigureService's own HTTPRequest/AIProvider secrets
 * (main.go wires the same credential.Store into both) -- the vault
 * master key lives in the identical OS keychain, just under its own id.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as secret$0 from "../../domain/secret/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopySecretToClipboard reveals id's password and writes it to the
 * clipboard, then clears the clipboard after clipboardAutoClear --
 * but ONLY if the clipboard still holds exactly that value at that
 * point (the same "don't clobber something the user copied since"
 * check KeePassXC's own auto-clear makes), never unconditionally.
 * Records one ContextUICopy audit line (goal 0203 S3), same not-gated-
 * but-visible posture as RevealSecret.
 */
export function CopySecretToClipboard(id: string): $CancellablePromise<void> {
    return $Call.ByID(2769882406, id);
}

/**
 * CreateSecret validates and inserts a new entry.
 */
export function CreateSecret(title: string, username: string, password: string, url: string, notes: string, tags: string): $CancellablePromise<secret$0.Entry> {
    return $Call.ByID(2352687000, title, username, password, url, notes, tags);
}

/**
 * DeleteSecret permanently removes id (and its history) -- no undo.
 */
export function DeleteSecret(id: string): $CancellablePromise<void> {
    return $Call.ByID(2164504395, id);
}

/**
 * GeneratePassword returns a fresh CSPRNG password from the given
 * character-class options -- stateless, doesn't touch the vault at all
 * (a user can generate before the vault is even unlocked).
 */
export function GeneratePassword(length: number, upper: boolean, lower: boolean, digits: boolean, symbols: boolean): $CancellablePromise<string> {
    return $Call.ByID(2111800646, length, upper, lower, digits, symbols);
}

/**
 * ListProviderSecrets lists every key of every enabled source as a
 * Summary whose ID is the reference itself and whose Title names the
 * key and its source -- titles only, never a value; a source whose
 * file cannot be read contributes nothing (the picker stays honest,
 * the source's own row reports the problem).
 */
export function ListProviderSecrets(): $CancellablePromise<secret$0.Summary[] | null> {
    return $Call.ByID(4191075382);
}

/**
 * ListSecretAccess is the bound read API the Secrets view's Access
 * history list calls -- newest first, optionally filtered to one entry,
 * limit/offset paged. Returns an empty page (never an error) when no
 * audit store is wired yet -- structurally unreachable in the real app
 * (main.go wires OpenAudit before any window/frontend exists), kept
 * graceful rather than surfacing a confusing error on a race that can't
 * actually happen.
 */
export function ListSecretAccess(req: $models.ListSecretAccessRequest): $CancellablePromise<$models.ListSecretAccessResponse> {
    return $Call.ByID(2793339806, req);
}

/**
 * ListSecrets returns every entry's masked Summary (no password) --
 * the browse surface's own list, sorted by title
 * (secretvault.Vault.List's own contract).
 */
export function ListSecrets(): $CancellablePromise<secret$0.Summary[] | null> {
    return $Call.ByID(1693971957);
}

/**
 * LockVault discards the in-memory decrypted vault -- manual lock, same
 * effect as auto-lock firing.
 */
export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(3317886945);
}

/**
 * RedactKnownSecrets scrubs every currently-stored password out of
 * text (secret.Redact, goal 0185 S4 -- Finding 4's "no enumerable set
 * of secret values to redact against" gap). Best-effort: an unlocked-
 * vault error is swallowed here rather than propagated, since a caller
 * on the error-formatting path (composition.SetSecretRedactor) has no
 * good way to surface a SECOND error about redaction failing while
 * already reporting a first one -- text passes through unredacted
 * rather than the whole error path failing outright.
 * 
 * Deliberately unaudited (goal 0203 S3 contract): this reads every
 * vault entry on a failure path purely to SCRUB output, never to expose
 * a value to anyone -- recording it would bury real reads (a workflow
 * that actually used a credential) under one audit line per error
 * message formatted anywhere in the app.
 */
export function RedactKnownSecrets(text: string): $CancellablePromise<string> {
    return $Call.ByID(2598084233, text);
}

/**
 * ResetVault archives the current vault file beside itself as a
 * timestamped ".bak" and creates a fresh one in its place. The archived
 * file's own key, if this device still holds one, is left exactly where
 * it is: restoring the backup must still work. Only reachable from the
 * locked state where the stored key can't open the file -- the one
 * situation where the entries are unreadable anyway.
 */
export function ResetVault(): $CancellablePromise<void> {
    return $Call.ByID(2341448377);
}

/**
 * RevealSecret returns one entry in full, password included -- a
 * distinct, explicit call from ListSecrets (never incidental to
 * browsing), matching SetHTTPRequestSecret's own write-only-elsewhere
 * posture but inverted: this vault's whole point is a human can read
 * their own password back, unlike the write-only integration-secret
 * slots. Records one ContextUIReveal audit line (goal 0203 S3) -- a
 * human's own click, not gated (S2 contract), but visible in their own
 * Access history.
 */
export function RevealSecret(id: string): $CancellablePromise<secret$0.Entry> {
    return $Call.ByID(1414222929, id);
}

/**
 * SecretHistory returns id's past versions, most-recently-superseded
 * first.
 */
export function SecretHistory(id: string): $CancellablePromise<secret$0.Entry[] | null> {
    return $Call.ByID(3113557004, id);
}

export function SetSourcesLister(fn: $models.SourcesLister): $CancellablePromise<void> {
    return $Call.ByID(3955565257, fn);
}

/**
 * SetTouchIDProtection turns the unlock requirement on or off. The
 * vault must already be unlocked: changing how a vault opens while you
 * can't see inside it is a surface with no honest read-back. Turning it
 * on is refused where this Mac cannot authenticate at all, so the
 * requirement never lands in a state that would lock the vault shut.
 */
export function SetTouchIDProtection(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(556293705, enabled);
}

/**
 * SetupVault creates a brand-new vault: mints a random master key,
 * creates the KDBX file (which mints the vault's own identity), stores
 * the key under that identity's slot in the OS keychain, and seeds one
 * obviously-fake demo entry (secret.BuiltInDemo) so the browse surface
 * is never empty on a fresh vault (.claude/rules/testing.md's "every
 * capability ships a seeded example"). Fails if a vault already exists
 * -- SetupVault is one-time, never an implicit reset; ResetVault is the
 * explicit door.
 */
export function SetupVault(): $CancellablePromise<void> {
    return $Call.ByID(1816045847);
}

/**
 * SourceProblems reports, per source id, why a source currently lists
 * nothing ("" for a healthy one): a missing or locked CLI, an
 * unreadable file or collection. The Configure row shows it.
 */
export function SourceProblems(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2210922477);
}

/**
 * UnlockVault authenticates the person at the keyboard when the unlock
 * requirement is on (secretservice_auth.go), fetches the key stored for
 * THIS vault file, and holds the decrypted database in memory for this
 * app session (goal 0185: "unlock once per app session, hold the vault
 * key in memory, auto-lock on idle").
 */
export function UnlockVault(): $CancellablePromise<void> {
    return $Call.ByID(1094954264);
}

/**
 * UpdateSecret validates and overwrites id's current values, pushing the
 * PREVIOUS values onto its history (secretvault.Vault.Upsert's own
 * contract).
 */
export function UpdateSecret(id: string, title: string, username: string, password: string, url: string, notes: string, tags: string): $CancellablePromise<secret$0.Entry> {
    return $Call.ByID(2518896629, id, title, username, password, url, notes, tags);
}

/**
 * VaultStatus reports whether a vault exists on this device, whether
 * it's currently unlocked, and which key protection is active -- the
 * one read the frontend's browse surface polls/subscribes to decide
 * what to render.
 */
export function VaultStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1119020926);
}
